### ISSUE TITLE
Clean up 700$4 in Institutions

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#1002]
In Institutions https://muscat.rism.info/admin/institutions/new, field 700 $4: 
That list of relator codes reflects a very early state of the relator codes prior to the ZR's adoption of Muscat. We reduced this list prior to introducing Muscat. Furthermore, the list uses terminology that we don't use elsewhere in Muscat ("scribe" for "copyist" for example). I don't see a reason to maintain this old list in Institutions. I think it would be better to have this list at least in line with the Sources list.  
This also would simplify translations because these terms are being translated for a very obscure corner of Muscat.

**Comment by xhero** [comment]
Copying over the list is easy, but what about the data that uses the current relator codes? Should that be fixed?

**Comment by xhero** [comment]
I made it in line with the Sources, we can then fine-tune the list.

**Comment by xhero** [comment]
BTW we still have "scribe" in the list from sources! :grin:
