### ISSUE TITLE
Improve template change MSR to EDT 

### ISSUE THREAD

**Issue by Docudoctor** [rism-digital/muscat#1010]
Section Library information and relations
Following fields are missing in the exemplar information after a template change:
1) Other shelfmark (591)
2) Local number (035) wrongly directed to the bibliographical record. 
3) Access restrictions (506)
4) Provenance note (561)
5) Source of acquisition (541) including all subfields!

Many thanks,
Guido

**Comment by jenniferward** [comment]
Binding note (563)

**Comment by MFalletta** [comment]
Watermark description (592)
