### ISSUE TITLE
Strange 'catalogue' entry

### ISSUE THREAD

**Issue by baccia** [rism-digital/muscat#1022]
@xhero 
All 691 links pointing to 
https://muscat.rism.info/admin/catalogues/50003862 
'Musical fragments in book bindings' (143 records from Frey-Gryn collections) should be changed to links pointing to
https://muscat.rism.info/admin/catalogues/50006297 
'MusicalFragments'
@baccia 
Then delete 210 in https://muscat.rism.info/admin/catalogues/50003862

**Comment by xhero** [comment]
Do you know if there is more to do here?

**Comment by baccia** [comment]
Yes, this still needs to be done. In the links above: read 'publications' instead of 'catalogues'.
All 143 691 links pointing to 
https://muscat.rism.info/admin/publications/50003862
should be changed to links pointing to
https://muscat.rism.info/admin/publications/50006297
Then I'll delete the 210 in 50003862 and write a reply to the comment in the record.

**Comment by xhero** [comment]
OK! I fixed it in muscat-test, can you have a look? I could do all of them except 990069254, because the note is in the CH-Bf holding, can you fix it by hand?

**Comment by baccia** [comment]
Wait: When I tried to delete the 210 in 50003862 on the test server I got this error message:
![Screen Shot 2021-12-14 at 15 09 34](https://user-images.githubusercontent.com/10451420/146014239-40228cb2-d557-46f7-8828-1534d1fd0338.png)
Do you know what it means?

**Comment by xhero** [comment]
Can you try again? I think I forgot to restart muscat-test after a change. Should i go in production?

**Comment by baccia** [comment]
Excellent, it worked on muscat-test. As far as I am concerned, go in production!

**Comment by ahankinson** [comment]
:shipit: 

(See: https://www.quora.com/GitHub/On-GitHub-what-is-the-significance-of-the-Ship-It-squirrel)

**Comment by xhero** [comment]
Ship it squirrel? :sweat_smile: In any case, done in production, if it is ok please close this ticket ;)
