### ISSUE TITLE
Proposal: rename the "name" column to "short_name" in the Secondary literature table

### ISSUE THREAD

**Issue by fjorba** [rism-digital/muscat#1027]
(I'm preparing an issue that gathers and links to all name and db migrations for the Secondary literature Catalogues to Publication change, see #975.  However, I think that each one should be discussed separately, to reach consensus.)

In the current "catalogues" (secondary literature) table there is a column (field) named "name":
https://github.com/rism-ch/muscat/blob/02aca2baf1d5e169b2f1fbbf29326a1a107d1c75/db/schema.rb#L41

The current usage of this field is to univocally identify a secondary literature publication with a short name or identifier. Currently, RISM extracts this value from Marc 210 $a (https://www.loc.gov/marc/bibliographic/bd210.html).  Some RISM examples:

```
210 __ $a Sacriconcentus
210 10 $a DTB 27-28
210 __ $a TerP
210 10 $a SzkL
210 __ $a BaranyaiHelytörténetirás
210 __ $a RennoP 2018
210 __ $a IlonaM 1989
210 __ $a FogD 1984
210 __ $a LesureP 1975
210 __ $a FogN 1976
```

I think that "name" doesn't match its real use, as in the secondary literature cataloguing template it is shown as "Short title (210)", and in the Active Record label, also "Short title" (https://github.com/rism-ch/muscat/blob/02aca2baf1d5e169b2f1fbbf29326a1a107d1c75/app/admin/catalogue.rb#L154).

My proposal to change it to "short_name" is double: first, that "name" it is not a visible name, because the visible one is "Short title" (introduced in 26661d4c3bf6aedc0721dd23a558dd5a0f3bc791 and 9d7dc1b83f39ce97a1d3b0c519b4ddd25f6ea86a).  Second, to have a less ambiguous name: searching for "name" in Muscat gives too many false positives, whilst "short_name" currently is not used anywhere (even this sentence is confusing due to that!).

If we rename it to "short_name" (in the db table and the Active Record screen, not in the cataloguing template!) it can embrace not only its current usage (short title), but also other short standard identifiers, like DOI, PMID, ISSN or ISBN.  This other alternative usage does not compromise RISM catalogue, but it may be an implementation option for Muscat users other than RISM, or a chained decision (first, take 210 $a; if it does not exist, 024 $a; if not, 020 $a, etc).  However, I think that the hypotetical future usage does not compromise the name change that I propose.  The same way, the preference for displaying "Short title" or "Short name" would be just a matter of a yaml translation files, it will not require a software change.

**Comment by xhero** [comment]
This is ok for me, AFAIK we indeed use it only for the short name, @jenniferward is it ok for you?

**Comment by jenniferward** [comment]
Sure that sounds fine if it runs behind the scenes and not in the interface.

**Comment by fjorba** [comment]
Yes, just behind the scenes.
