### ISSUE TITLE
Make catalog controller configurable

### ISSUE THREAD

**Issue by ahankinson** [rism-digital/muscat#1031]
Currently there are dedicated catalog controllers for the different variants of Muscat (CH, UK, ZR). In talking with @xhero we thought that post-7.0 we can consolidate these to a single controller, and make their behaviours configurable with the central application configuration.

This will remove the possibility of running several catalogues on the same instance of Blacklight, but will simplify deployment by consolidating the configuration for dedicated Muscat installations.

**Comment by xhero** [comment]
If we need to run different catalogs we can simply have different instances of Muscat with different configuration (like for muscat-training and muscat-test)

**Comment by fjorba** [comment]
Yes, please. And one of the things that I patch for each new Muscat release I install is the record type that can be searched, as suggested by @xhero in https://github.com/rism-ch/muscat/issues/958#issuecomment-654628671. So, can this `Source` vs `Publication` can be considered in this configuration?

And, at the same time, I'm also patching https://github.com/rism-ch/muscat/blob/develop/app/views/catalog/_show_default.html.erb, that also has a reference to the CatalogController:

```diff
--- a/app/views/catalog/_show_default.html.erb                                                                                       
+++ b/app/views/catalog/_show_default.html.erb                                                                                       
@@ -4,7 +4,7 @@                                                                                                                      
   This is pretty hackish for now - figure out a better way to do this into the CatalogController! -%>

 <%
-       @item = Source.find(@document.id.split(" ")[1]) # hackady-hack! Source 1234567 -> 1234567                                    
+       @item = Publication.find(@document.id.split(" ")[1]) # hackady-hack! Publication 1234567 -> 1234567                               
        @editor_profile = EditorConfiguration.get_show_layout @item
 %>
 <dl class="dl-horizontal  dl-invert">
@@ -35,4 +35,4 @@ window.cookieconsent.initialise({                                                                                  
     href: '<%=get_cookie_link()%>',
   }
 })});
-</script>
\ No newline at end of file
+</script>
```

**Comment by fjorba** [comment]
> If we need to run different catalogs we can simply have different instances of Muscat with different configuration (like for muscat-training and muscat-test)

The purpose of #1052 is to facilitate it. Another step, that I have (yet) no idea how easy would it be is to make database and solr depend of SITE_ID.  The differences between my 3 test Muscat installations are getting narrower; my goal would be to have a single local patch with my customisations in all my sites, and just change SITE_ID to deploy each of them. Even if it is not 100% completed, the closer I get, the better.

**Comment by fjorba** [comment]
> Yes, please. And one of the things that I patch for each new Muscat release I install is the record type that can be searched, as suggested by @xhero in [#958 (comment)](https://github.com/rism-digital/muscat/issues/958#issuecomment-654628671). So, can this `Source` vs `Publication` can be considered in this configuration?

Done in #1106
