### ISSUE TITLE
file institutions, field type of institution (MARC 368 $a), add more attributes

### ISSUE THREAD

**Issue by Docudoctor** [rism-digital/muscat#1063]
Dear colleagues,
please add following attributes in the German version of Muscat:
- Interpret
- Kopistenwerkstatt
- Musikalienhändler
- Papierhersteller

please add following attributes in the German version of Muscat:
- Bookseller
- Copyist
- Papermaker
- Performer

Many thanks in advance.
Guido

**Comment by ahankinson** [comment]
These are already available in the translations:

Papermaker: https://github.com/rism-digital/translations/blob/master/locales/de.yml#L650-L651
Bookseller: https://github.com/rism-digital/translations/blob/master/locales/de.yml#L280
Performer: https://github.com/rism-digital/translations/blob/master/locales/de.yml#L661
Copyist: https://github.com/rism-digital/translations/blob/master/locales/de.yml#L345

**Comment by jenniferward** [comment]
Speaking only for the EN: We use Guido's proposed EN terms in the 700 and 710 fields for Sources. I am fine if we use the same terms in 368 $a; I can explain it in the guidelines.

**Comment by jenniferward** [comment]
We still need these terms in the Institutions; see also https://github.com/rism-digital/muscat/issues/1208

**Comment by xhero** [comment]
What is missing? In `Institutions` 368 I see:

```yml
 codes:
      - "Archive" 
      - "Bookseller"
      - "Copyist"
      - "Documentation center"
      - "Institution"
      - "Library"
      - "Museum"
      - "Papermaker"
      - "Performer"
      - "Publisher"
      - "Other"
      - "Printer"
      - "Research institute"```

**Comment by jenniferward** [comment]
Sorry, my mistake!
