### ISSUE TITLE
Should we open Muscat Discussions?

### ISSUE THREAD

**Issue by fjorba** [rism-digital/muscat#1066]
Github has opened a new feature, called Discussions (https://docs.github.com/en/discussions/quickstart). I've discovered because Github offered to open it in my Muscat fork, so probably this offer also exists for upstream Muscat. For I have seen, it would be useful to discuss features or issues that are not exactly bugs, but doubts or clarifications for future directions.  This feature also allows current issues to be moved to discussions. 

Myself, I have several things (like some Marc tags and subfields) regarding secondary literature that I'd love to discuss with @jenniferward, for example, that I feel unfit to be treated as an issue.

**Comment by jenniferward** [comment]
I have nothing against this, but I don't know anything about this feature.

**Comment by fjorba** [comment]
Due to lack of enthusiasm, I think I'd better close it.  Thanks anyway, @jenniferward.
