### ISSUE TITLE
file institutions, full record, set links to authority references

### ISSUE THREAD

**Issue by Docudoctor** [rism-digital/muscat#1067]
Dear colleagues,
please set links to the authority references like VIAF, Wikidata etc. 
Ex. I-SGVcc

Many thanks
Guido

**Comment by xhero** [comment]
What should be done here in practice?

**Comment by jenniferward** [comment]
He means that the authority references in the 024 should be linked to the actual external authorities, as in what the Personal Names do:
https://muscat-test.rism.info/admin/people/2561
![image](https://user-images.githubusercontent.com/18663291/121392137-64763580-c94f-11eb-9ce7-703abd55f51c.png)

Currently in Institutions they do not link out. I agree it would be useful, so I'll reopen this.

**Comment by Docudoctor** [comment]
Especially for VIAF, DNB and Wikidata.
Examples: "C. A. Fahrmbacher" and "I-SGVcc".
Is now urgently needed for the FID project of publishers and printers operated by Dresden D-Dl and RISM Frankfurt.
