### ISSUE TITLE
Help text missing from Secondary Literature (?)

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#1069]
I don't see it any more!
https://muscat.rism.info/admin/publications/new?locale=en

**Comment by fjorba** [comment]
Do you remember which text used to be here?  (sorry, I don't have access to your server, but I should have the same local system)

In principle, now your url should redirect automatically to https://muscat.rism.info/admin/publications/select_new_template?locale=en

Are you seeing this on the left:

> Legacy templates for compatibility
> Secondary literature unified template

And that on the right of the screen?

>Currently there is only the Legacy record type, that is the same unified template that Muscat has used, for all kind of secondary literature material.
>
> New templates will be created for specific record types.

**Comment by jenniferward** [comment]
There are supposed to be question marks next to each field so that the help text is displayed. I only just noticed that they are missing:
![image](https://user-images.githubusercontent.com/18663291/108362379-f23ce200-71f3-11eb-96f9-8c1fb0d10353.png)

They should look something like this:
![image](https://user-images.githubusercontent.com/18663291/108362412-fd900d80-71f3-11eb-8319-54ddac45dc5f.png)


@fjorba I don't see any of what you linked to.

**Comment by fjorba** [comment]
I don't see those question marks, but not in Sources nor in any authority record in my local systems. I understand that they used to exist for all Marc editing templates, right? Do they exist in any other one in your server?

**Comment by jenniferward** [comment]
MARC editing templates: I think so but am not certain.

**Comment by fjorba** [comment]
At this moment I don't have a diagnostic whether it is due to the catalogues-to-publications rename or the new translation mechanism (#1004). Maybe @ahankinson has an insight?

**Comment by HirschSt** [comment]
Yes, it's related to the renaming to publication. I am preparing a fix for 7.1 by changing the guidelines app

**Comment by xhero** [comment]
Help is back!

**Comment by jenniferward** [comment]
I don't see it on muscat-test!
