### ISSUE TITLE
340$m: add oblong formats

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#1075]
Please add the following to the drop-down list in 340$m:
obl. 2°
obl. 4°
obl. 8°

German is:
qu-2°
qu-4°
qu-8°

**Comment by xhero** [comment]
This field is not localisable (it is inserted as-is in the marc), are the english ones ok?

**Comment by xhero** [comment]
Fixed in 3dafbb9

**Comment by jenniferward** [comment]
Just found a case where we need oblong duodecimo: `obl. 12°`

(Note to self: https://muscat.rism.info/admin/sources/990041498 )
