### ISSUE TITLE
700 and 710 $4 relator code should not be repeatable

### ISSUE THREAD

**Issue by xhero** [rism-digital/muscat#1078]
And a script to fix split the eventual duplicate ones should follow.

**Comment by xhero** [comment]
Muscat updated, will need script to fix this

**Comment by jenniferward** [comment]
Do you know when the script will run? I'm running into situations where it would be useful to have them separate. 
Example from 710: https://muscat.rism.info/admin/sources/990036686

**Comment by jenniferward** [comment]
Holdings needs to have the same functionality in 700 and 710 (example: https://muscat.rism.info/admin/holdings/154201/edit ).

In addition, a script needs to be run in Sources and Holdings. For records with multiple $4 in 700 or 710, the $a needs to be duplicated and the additional $4 moved to it - so 
Adam Berg [Publisher] [Printer] will become
Adam Berg [Publisher] 
Adam Berg [Printer]

**Comment by jenniferward** [comment]
It looks good on muscat-test: the "repeat subfield" button is gone in the holdings for 700 and 710, and the script split the functions in both Sources and Holdings, 700 and 710.
