### ISSUE TITLE
551 $a on People is not linked to the Place authority

### ISSUE THREAD

**Issue by ahankinson** [rism-digital/muscat#1080]
The documentation for the 551 $a field says "Geographic names are connected with the Places authority file". However, it seems that the values in this field are not linked or controlled by the Places authority file. 

This should be corrected to link the 551 $a to the Places authority.

Tagging @HirschSt  -- @xhero thinks there may be some overlap with the SRU interface on this?

**Comment by HirschSt** [comment]
thanks for spotting, yes, it should also link to places. No overlap with sru IMO since DBN uses some specific marc layout, and we need some wrapper between both classes (see eg https://github.com/rism-digital/muscat/blob/develop/config/viaf/person_dnb.xsl)

**Comment by ahankinson** [comment]
I just noticed that this is also a problem for the 043 field on institutions.

**Comment by xhero** [comment]
This will be included in 8.0, the fix script should be run at the upgrade.
