### ISSUE TITLE
Discrepancy between note subfields on 856 for people

### ISSUE THREAD

**Issue by ahankinson** [rism-digital/muscat#1081]
In Person records the `$y` subfield on the 856 field is given as the "Note about external resource", but MARC21 specifies `$y` as the "Link text" field. 

In the Source records and the Institution authority records, and in the MARC specification, `$z` is the field for notes.

The Person authority configuration should be changed to have the note field be `$z`.

**Comment by xhero** [comment]
@jenniferward Can you have a look at this?

**Comment by jenniferward** [comment]
I think what we input as $y is meant to act like a MARC $z - so I agree with Andrew.

**Comment by xhero** [comment]
@BernLutz Would this work for you guys? It is quite minor and there are like 30 records to fix.

**Comment by BernLutz** [comment]
Sehr geehrte Damen und Herren,  
 
vielen Dank für Ihre E-Mail. Bis einschließlich 05.06.2024 bin ich leider nicht erreichbar.
Ab 06.05.2024 stehe ich wieder für Ihre Fragen und Anliegen zur Verfügung. 

Mit freundlichen Grüßen 
Bernhard Lutz

**Comment by BaMikusi** [comment]
I see that Herr Lutz is not available, but since the BSB was informed about the ticket on 11 April, and on 15 May it was confirmed that this would form part of the upcoming release, it should certainly be OK to move on with this now.
