### ISSUE TITLE
Selecting text in the record editor activates drag-and-drop

### ISSUE THREAD

**Issue by ahankinson** [rism-digital/muscat#1084]
<img width="1472" alt="drag-drop" src="https://user-images.githubusercontent.com/163183/112470470-fd42df00-8d6a-11eb-98f9-d200fd962c10.png">

When trying to select text in the 'help' section for fields in the editor, the mouse activates the 'drag-and-drop' feature, making it so that you cannot copy and paste text from these fields. (This makes it difficult to, for example, show where guidelines should be updated).

**Comment by xhero** [comment]
Fixing this requires some surgery to the editor. More specifically we have to move the help box from the single repeated tags directly under the the title of the tag group. For the first tag it will make no difference, but if the tag is repeated it will always show on the top one.
I personally don't mind and I don't think it is particularly confusing, but I'm also not sure if users _really_ want to have the help on each tag.

<img width="993" alt="Schermata 2021-03-29 alle 12 29 17" src="https://user-images.githubusercontent.com/1691778/112824472-da763a80-908a-11eb-961b-0b3ddb04f5d3.png">

**Comment by jenniferward** [comment]
I agree with Andrew that this is irritating. My workaround is that I go to the main Guidelines page i.e. here https://muscat-test.rism.info/admin/guidelines but then I have to hunt for the text again.

**Comment by cgueggi** [comment]
Looks good to me, thanks! Although we have to see that we don't have too many icons in the end...

**Comment by jenniferward** [comment]
I like it too, thanks. My mouse changes to arrows as soon as I am over the icon, so it is intuitive. 

Could you add it to:

-  the 744 in printed collections, e.g. https://muscat-test.rism.info/admin/sources/993121419/edit
![image](https://user-images.githubusercontent.com/18663291/164224160-9f22e219-02ec-4e30-a633-4f6fef26fa40.png)

- the 774 in MS coll, e.g. https://muscat-test.rism.info/admin/sources/1001206352/edit
![image](https://user-images.githubusercontent.com/18663291/164224349-f3f2c311-a0fa-4354-9d71-65e0cad59b59.png)

- the 774 in composites, e.g. https://muscat-test.rism.info/admin/sources/1001206231/edit 
![image](https://user-images.githubusercontent.com/18663291/164224546-bdda996d-309d-46c0-9c9d-82be37439ea8.png)
