### ISSUE TITLE
Map older Kallisto institution type values to allowed values

### ISSUE THREAD

**Issue by ahankinson** [rism-digital/muscat#1086]
The 368 $a field has a number of values that do not correspond to the allowed values. This is from the older Kallisto data. Non-standard values are listed below, along with the number of records.

```
"K",32421        
"B; K",5113
"K; B",2652
"V",830
"K; V",438
"C",368
"B",330
"VALUE_ERROR",39
"V; K",38
"K; B; V",16
"B; K; V",12
"K; F",8
"L",7
"C; K",5
"F",4
"B; V; K",2
"K; F; V",2
"K; L",2
"K; V; L",2
"2",1
"K; C",1
"K; L; V",1
"K; V; B",1
"K; V; F",1
"L; K",1
"L; V; K",1
"V; B; K",1
"V; K; B",1
"t",1
```

**Comment by ahankinson** [comment]
Updated with the numbers broken down into specific letters:

```
"K": 40.719 institution records
"B": 8.128 institution records
"V": 1.346 institution records
"C": 374 institution records
"F": 15 institution records
"L": 14 institution records
"VALUE_ERROR": 39 institution records (e.g., Regensburg [Hochstift], institution #49573)
"2": 1 institution record (e.g., Zámek, institution #30078781)
"t": 1 institution record (e.g., Fabritzius Landschaftsbau [Essen], institution #42166)
```

**Comment by xhero** [comment]
Did we ever get to clean these up? There was some effort some time ago IIRC.

**Comment by ahankinson** [comment]
Muscat is still showing some records with `K`, e.g., https://muscat.rism.info/admin/institutions/30077065

**Comment by BaMikusi** [comment]
@Docudoctor should take a look.

**Comment by ahankinson** [comment]
@Docudoctor did send this to me. Here is the text of his e-mail from 14 April 2021:

---
after my Easter holidays and dealing with leftover questions during the last days I got time today working with your list of abbreviated institution types coming from Kallisto.
The following are the remaining values and their meaning for introducing the correct values into Muscat. The rest from your list is eliminated. 

German first:

K = Körperschaft   
B = Bibliothek
V = Verleger
C = Kongress
F = Forschungsinstitut

English second:

K = Institution
B = Library
V = Publisher
C = Congress
F = Research institute

My last request is to delete after that all useless Kallisto and Kalliope records without any link to other entries. Some of them can be linked with each other via the MARC field "Related institution (710)". Only in (710) you can also find links to RISM institution records as well. But this is rare. 
So you might keep these ones for a last review by me.
---

**Comment by Docudoctor** [comment]
Dear Andrew,
are there any further questions, or is it clear?
Best,
Guido

**Comment by ahankinson** [comment]
It's clear to me; it is already implemented in RISM Online. However, I think the data still needs to be updated in Muscat directly.

**Comment by HirschSt** [comment]
I think this is stuff for some maintenance, I can prepare a script accordingly (with a related issue)

**Comment by HirschSt** [comment]
maintenance https://github.com/rism-international/tasks/issues/965

probably this issue can be closed now

**Comment by ahankinson** [comment]
@HirschSt -- https://github.com/rism-international/tasks/issues/965 says this is already done. Is this not the case?
