### ISSUE TITLE
Standardize labels on person / place relationships

### ISSUE THREAD

**Issue by ahankinson** [rism-digital/muscat#1089]
The field labels for 500/510/551 on people, and the field labels for 700/710/551 on institutions differ. These should be made consistent. 

For people:
 - 500 is RELATED PERSONAL NAME
 - 510 is ASSOCIATED INSTITUTION
 - 551 is GEOGRAPHIC NAME

For institutions:
 - 700 is PERSON
 - 710 is RELATED INSTITUTION
 - 551 is PLACES

These should be made consistent, along with the work in #1087, to:

 - 700 RELATED PERSONAL NAME
 - 710 RELATED INSTITUTION
 - 751 RELATED PLACE

**Comment by jenniferward** [comment]
@Docudoctor and @alexandermarxen: Suggestions ok?

**Comment by alexandermarxen** [comment]
Yes, I agree, thank you very much.

**Comment by jenniferward** [comment]
Throwing Works into the mix so it gets revised at the same time:


- ADDITIONAL PERSONAL NAME (500)
- ADDITIONAL INSTITUTION (510)

We already have:
- RELATED WORK (530)
