### ISSUE TITLE
Create automatic message to owner (prints)

### ISSUE THREAD

**Issue by cgueggi** [rism-digital/muscat#1095]
We have noticed that thanks to the new structure in printing records, many changes/improvements within the bibliographical entries are made by cataloguers, which is basically very welcome and we do ourselves from time to time. Could the system be set up so that the owner of a bibliographic entry receives an automatic message when changes are made (analogous to the comment function)? Sometimes it would be desirable to know about certain changes and to discuss them if necessary.

**Comment by xhero** [comment]
You can add a notification for a particular siglum in the user settings, this way you can know when records from a certain library are modified.

**Comment by xhero** [comment]
7.1 contains a complete overhaul of the notification system, and this is now possible!
