### ISSUE TITLE
Proposal: record_sets for oai_sets and  web_sets

### ISSUE THREAD

**Issue by fjorba** [rism-digital/muscat#1109]
We are interested in having a couple of features in Muscat that have a similar behaviour: grouping the records in different sets.

This is a strong requirement when implementing an OAI server for Muscat, and having an OAI servir in Muscat is a strong requirement for using it as institutional or research repository.  There exists a couple of Ruby based oai servers, a generic one (https://github.com/code4lib/ruby-oai) and another one specific for Blacklight (https://github.com/projectblacklight/blacklight_oai_provider), based on the first one.

In OAI-PMH, the client can ask the server which oai sets does it offer (http://www.openarchives.org/OAI/openarchivesprotocol.html#ListSets), and can selectively request records of a single oaiset or without this constraint.  oaisets can support hierarchies or not.  Each of the softwares I kow (DSpace, OJS, Invenio, Pure) approaches this feature differently: DSpace is tied to the collections hierarchy; OJS oaisets depend on the journal sections, in Invenio they depend on collections, and in Pure depend on record types and publishing years.

As Invenio refugees, we are also interested in so called collections (and we kow that Muscat has another use for this word).  Collections, in Invenio, are the result of a search.  They can be hierarchical, regular, virtual, etc, and they are the starting point for creating oaisets.  They can also be used for visually organising the records in the web interface, ex:

* https://ddd.uab.cat/
* https://traces.uab.cat/
* https://ifmuc.uab.cat/

Both features have an id (short name or siglum) and a name or title.  Invenio collections can have more things, like description texts, in different languages, in different positions, etc.

I've spend some months thinking about how to implement both things in Muscat, and now I think that I can expose my draft conclusions:

Create a new model and table, called for example record_sets, that has relations with both Sources and Publications, like People, Institution or the other models.  A draft list of fields would be:

* short_name
* title (we need it to be in different languages, but we can hide this detail now)
* will it be used as oai_set?
* will it be used as web_set? (= Invenio collection; this is an ugly name, I'm trying to find a better alternative)
* description (we need it to be in different languages, but we can hide this detail now)
* something about where to appear on the screen

At this moment I'm experimenting reusing a model I don't need for anything else (Liturgical feasts), so I can do steps without modifying the db schema, that I will delay as much as possible.

However, I'm interested in your feedback, because I may have overlooked something in Muscat.  For example, my impression is that I cannot reuse folders because they are related to the internal, admin interface, while both oaisets and Invenio collections are for the public interface, but I may be wrong.

**Comment by xhero** [comment]
How would you manage the record_sets model? I suppose you would need to add data to that, so I think a suitable interface will need to be made?
I find the Blacklight OAI provider interesting, since it seems to build up on the existing solr index and we would not need to add a new model and maintain data into that.
Folders are more or less similar to this, but one Folder can contain only items of one type (i.e. Source) and there is a hard limit on the maximum number of FolderItems inside, and they are really not meant to be used outside the cataloguing interface (even it that could be made possible).
Would BL's OAI implementation work? That seems the simplest route to me.

**Comment by fjorba** [comment]
I'm thinking towards the Invenio model, adapted to the strong relations that Muscat provides; so they would be handled in the cataloguing form by librarians themselves.

Currently, in Invenio the (web) collections are set in 980, with $a as primary collection and $b as secondary or virtual collections, and oaisets are in 024 8#, with oaiset where the record belongs to in $9, and $a as the oai unique id for the record, for example:

* https://ddd.uab.cat/record/239267/export/hm
* https://ddd.uab.cat/record/180312/export/hm
* https://ifmuc.uab.cat/record/2175/export/hm

However, there are subtilities that have to be handled, like that the (Muscat) OAI server should remember that a record has been deleted, and/or at least deleted from an oaiset, and this value is kept as $z in 024, ex:

* https://ddd.uab.cat/record/204354/export/hm

This behaviour must be exposed in the Identify verb as `Deleted Record Policy`, for example:

* https://ddd.uab.cat/oai2d?verb=Identify
* https://ifmuc.uab.cat/oai2d?verb=Identify
* http://www.tdx.cat/oai/request?verb=Identify

I got the aha! moment when I thought to create a single model with a checkbox asking whether a specific set would be used as oaiset and/or webset, or even none (but useful for statistics, for example; we use this trick quite a lot). The relation would be many-to-many.  We must think if it makes sense to use two Marc tags or a single one; we'll do some brainstorming here at UAB before posting a proposal.

There are particularities of the Invenio model that probably don't make much sense in Muscat, for example, (calculated) hierarchies. Probably an explicit list of the oaisets a record belongs to is much simpler to handle and provides the same functionality.

So yes, in principle the Blacklight OAI server should work because most of this information are in the records themselves; maybe except the ListSets, that would have to query the database.

**Comment by fjorba** [comment]
As Blacklight is going to be removed from Muscat (#1113), this issue does no longer make sense, so I'm closing it.
