### ISSUE TITLE
Add Single Signon as an optional integration

### ISSUE THREAD

**Issue by tramuntanal** [rism-digital/muscat#1116]
This is a proposal for adding SSO to Muscat as an optional configuration.

By default, Muscat will still use Devise's database_authenticatable but now will allow to configure other authentication strategies. The requirement is to have all of them configured at the same time and allow the user to select which to use. This use case is for organizations like universities where internal users will be able to login via SSO and external users will persist the authentication into the database.

It happens that `database_authenticatable` and `cas_authenticatable` are incompatible, so both can not be enabled together.
What seems to bee a good option is to use `saml_authenticatable` instead, as this gem already has configuration options to use different routes that will not clash with `database_authenticatable`.

**Comment by ahankinson** [comment]
@xhero I think this can be closed?
