### ISSUE TITLE
DB migrate crashes with syntax error in test env

### ISSUE THREAD

**Issue by HirschSt** [rism-digital/muscat#1121]
rake db:migrate is unhappy with https://github.com/rism-digital/muscat/blob/cca3826581f4b6332ee889bd37951a41f7945619/db/migrate/20140401072119_create_catalogues.rb#L37:

`-- execute("ALTER TABLE catalogues AUTO_INCREMENT=")
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1: ALTER TABLE catalogues AUTO_INCREMENT=
/var/lib/gems/2.5.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `_query'
/var/lib/gems/2.5.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `block in query'
/var/lib/gems/2.5.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:130:in `handle_interrupt'
/var/lib/gems/2.5.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:130:in `query'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.6/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:187:in `block (2 levels) in execute'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.6/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.6/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.6/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.6/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:186:in `block in execute'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.6/lib/active_record/connection_adapters/abstract_adapter.rb:581:in `block (2 levels) in log'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.6/lib/active_record/connection_adapters/abstract_adapter.rb:580:in `block in log'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.6/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.6/lib/active_record/connection_adapters/abstract_adapter.rb:571:in `log'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.6/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:185:in `execute'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.6/lib/active_record/connection_adapters/mysql/database_statements.rb:28:in `execute'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.6/lib/active_record/migration.rb:871:in `block in method_missing'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.6/lib/active_record/migration.rb:840:in `block in say_with_time'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.6/lib/active_record/migration.rb:840:in `say_with_time'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.6/lib/active_record/migration.rb:860:in `method_missing'
/var/lib/gems/2.5.0/gems/activerecord-5.2.4.6/lib/active_record/migration.rb:604:in `method_missing'
/data/rails/muscat/db/migrate/20140401072119_create_catalogues.rb:37:in `up'
`

**Comment by xhero** [comment]
Did you manage to look at this? I think probably the configuration

```  BASE_NEW_IDS = { 
    :publication        => 95000000,
}
```

is missing in application.rb

**Comment by HirschSt** [comment]
Thanks! Yes, I have nearly that

```
:publication        => 0,
}
```

Should I take the new value? But I think this issue can be closed.
