### ISSUE TITLE
Refactor field 593

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#1122]
We are getting too many records that contain multiple material groups consisting of a print (any kind of print) plus a manuscript (any kind of handwritten material). This is not ideal because the print should be described separately so that other libraries can attach their holdings to it. Is it possible to add a friendly warning for records that:
1) Have one material group that is print, print with autograph annotations, print with non-autograph annotations, libretto printed, treatise printed
and
2) Have one material group that is autograph manuscript, possible autograph manuscript, partial autograph, manuscript copy, manuscript copy with autograph annotations, libretto handwritten, treatise handwritten

so that a message appears that says, "Please consider creating a separate record for the printed material."  ?

**Comment by cgueggi** [comment]
Sorry for intervening in this topic...
What about this idea: When using a manuscript template there should be no possibility to select a "print", "print with autograph annotations" etc. in the 593-dropdown list. Could this be a first step to prevent "wrong" multiple material entries?
However, it remains to be considered how to proceed in the print templates. It would be good there, especially in the hodlings, if additional handwritten materials could be mentioned.
But maybe a warning message will be enough.

**Comment by jenniferward** [comment]
Yes, a long-standing wish of mine: https://github.com/rism-digital/muscat/issues/311 ;-) 
But last time I asked, there is no way to restrict 593 to template type? (I get a lot of people who select "print" for printed libretti.)

**Comment by lpugin** [comment]
My understanding is that we need "Print" to be allowed for material group within the manuscript templates for cases where we have mixed content that cannot reasonably be catalogued separately. As @cgueggi pointed out https://github.com/rism-digital/muscat/issues/311#issuecomment-208302075 we have many of such cases. E.g, https://muscat.rism.info/catalog/469060400

Regarding the use of "Print" for "Printed libretti", I would suggest to decouple them. Basically have 593 $a for the source type (i.e., the document type), and introduce $b for a content type. Content type would be _libretto_ or _theoretica_ and would need to be given only when it is an additional material group of a different type (music is assumed by default) than the template. So for the example above, we would have
* Group 01: 593 $a Manuscript Copy
* Group 02: 593 $a Print $b Libretto

It does not remove the need of the warning, but does reduce the list. That reduced the risk of mistake and will improve search.

**Comment by cgueggi** [comment]
My statement was 5 years old, when I did not know anything about the new structure for print records (bibl. entry plus holding). At that time I thought we should have this possibility. When migrating our Swiss data, we separated all mixed materials (i.e. we have decided which group is more important and keep this one. The other one is mentioned in the 500 or in some cases it was deleted when not useful). So I think there are no more mixed materials from CH-*, except one of them is a libretto or a treatise. Can you verify this?

**Comment by lpugin** [comment]
We still have about 3,000 sources with mixed material groups
https://muscat.rism.info/catalog?f%5B593a_filter_sm%5D%5B%5D=Manuscript+copy&f%5B593a_filter_sm%5D%5B%5D=Print
A few in the CH data
http://www.rism-ch.org/catalog?f%5B593a_filter_sm%5D%5B%5D=Print&f%5B593a_filter_sm%5D%5B%5D=Manuscript+copy&locale=en&q=&search_field=any_field

**Comment by xhero** [comment]
The warning is (relatively) easy to add, but I'm not sure if we should hide print all-together - but we can if we need to

**Comment by cgueggi** [comment]
So I think this is a matter for the guidelines. If it is not wished to have mixed material...
- it has to be clear in the guidelines which cases are allowed and which are not
- we need to think about a procedure to correct the 3000+ records with mixed materials (the CH data should not make any problems)

For now, I think a warning, specifically for additional printed material in a manuscript template, would be useful.

**Comment by jenniferward** [comment]
This might be easier to discuss in a call? There are a lot of aspects here. 
But I don't think we will ever be able to correct most of the 3,000 mixed records - we will just never be able to split some of them. We simply don't have enough bibliographic information in the records and can't identify all of the prints. 

As to the guidelines https://muscat.rism.info/admin/guidelines#doc_cat_collections we have "Ideally, the printed material should be cataloged in a separate record". For 7.1 I strengthened this to "Always strive to catalog the printed material in a separate record".

**Comment by lpugin** [comment]
This would be my proposal for refactoring 595. The goal is two-fold:
1. Improve consistency between record types (templates) and the marc 593
2. Decouple concepts in 593 in order to reduce the number of values and to improve search capabilities

Some initial remarks. We assume that the distinction between manuscript and printed sources is given by the template. Search (filtering) for these would be based on this, and not on 593. The same is also assumed for the distinction between music, libretti and treatises.

The 593 should serve two roles
* Provide more precise information about the source type (autograph, annotations) than given by the template
* Provide information for additional material groups that deviate from the template. For example:
    * A libretto attached to a source
    * Additional manuscript material attached to a print

To that end, 593 should be split into three different subfields
* $a to record the source type
* $b to record the material group type when different from the template one

We would improve Muscat to the content of list shown in the editor will be dependent on the template. The use of $b would be necessary only in cases where we have more than one material group.

### Values

For manuscript sources, $a can be
* Autograph manuscript
* Possible autograph manuscript
* Partial autograph
* Manuscript copy
* Manuscript copy with autograph annotations
* Additional printed material

For printed sources, $a can be
* Print
* Print with autograph annotations
* Print with non-autograph annotations
* Additional manuscript material

For music sources, $b can be
* Libretto
* Treatise

For libretti, $b can be
* Music source
* Treatise

For treatises, $b can be
* Music source
* Libretto

(in theory "Manuscript copy" and "Print" in $a could be dropped because they to not bring any additional information, but we might want to leave them for the sake of simplicity)

**Comment by cgueggi** [comment]
Thanks Laurent. This looks like a good compromise.

**Comment by lpugin** [comment]
Regarding $b, it would probably be better not to make it optional. This means that value list would be the same for all templates:
* Music source
* Libretto
* Treatise

We can make sure Muscat prefills it appropriately for each template.

**Comment by lpugin** [comment]
An additional point that comes to my mind. Having 593 on the bibliographic record of print does actually not make much sense. So unless we want to have bibliographic records with material groups with different content (e.g., a material group with music, and a material group with a libretto), I would suggest to remove it completely. If we keep it, $a should have "Print" as only possible value, I think. "Print with manuscript annotation" (and similar) should be at the holding level anyway.

**Comment by jenniferward** [comment]
It is really convenient, when downloading records and using them outside of Muscat, to have a field that clearly states what kind of material you have. Is the LDR (where I think the template type is stored) really that obvious?

**Comment by lpugin** [comment]
Yes, I see your point. Than having just $a Print would do it.

**Comment by lpugin** [comment]
I updated the proposal in the comment [above](https://github.com/rism-digital/muscat/issues/1122#issuecomment-866802056)

**Comment by jenniferward** [comment]
I fully support Laurent's suggestion to refactor the field and decouple elements but I would like to go one step further and be more explicit with statements of material form (print or manuscript) in the data. This duplicates (or reinforces) template type and adds another subfield but I think it is good to have it clearly stated in this field alongside the other descriptive elements, so you can select what you want from this single field. 

Further, I think additional material could be stated in a separate subfield, making the subfields more uniform in purpose.

So I've added two subfields.

$a: Form of material
- Manuscript
- Print
- Composite 

$b: Category of material
- Notated music
- Libretto
- Treatise
- Composite

$c: Nature of material
- Autograph manuscript
- Possible autograph manuscript
- Partial autograph
- Manuscript copy
- Manuscript copy with autograph annotations
- Print with autograph annotations
- Print with non-autograph annotations

$d Accompanying matter
- Accompanying matter is present

The options in the drop-down menus would depend on the template. Please see this document for definitions as well as examples of templates and what would be offered:

https://docs.google.com/document/d/1oLOZWfuow_quPJ1DKqxiTX8Q_z5WL0lj1mKkZto5ipQ/edit?usp=sharing

**Comment by lpugin** [comment]
I added "Print proof" to the $b for material groups in holdings [above](https://github.com/rism-digital/muscat/issues/1122#issuecomment-866802056). I think this can be useful in some cases.

**Comment by jenniferward** [comment]
Please see this spreadsheet for an analysis of the items marked "Other" in Muscat (ca. 1,100 records). The column 593 indicates where multiple material types (material groups) are present. I've put things into rough categories which are visible in the "Notes" column.

https://docs.google.com/spreadsheets/d/1-scBFykKUWuT3y_7cr_Oo85BIZyOoVg4VqDbnP3V8qg/edit?usp=sharing

Note that similar issues are present elsewhere in Muscat but were cataloged using different strategies:
- Typed libretti (CH records)
https://muscat.rism.info/admin/sources/409000200

- Material type "print" but it is a reproduction 
https://muscat.rism.info/admin/sources/1001170942

- Manuscript template but 593 "Print" because it is a reproduction
https://muscat.rism.info/admin/sources/1001162601

**Comment by jenniferward** [comment]
Just posting a recent user question as a note-to-self but also as a case study for future reference: A RISM cataloger could not find 990025021 to add holdings, but did find 280001856 (4 material groups), 659003047 (5 material groups), and 452521142 (print in MS template but also a duplicate of 990025021, which was merged).

**Comment by xhero** [comment]
https://docs.google.com/spreadsheets/d/1-mk-PhfECqOl8f8U0W832Ke-ZpQkuK6gOBhw214CNWM/edit#gid=551228637

**Comment by ahankinson** [comment]
🎉 🥳  :shipit:

**Comment by lpugin** [comment]
Great!
