### ISSUE TITLE
Cannot create new users in 7.1

### ISSUE THREAD

**Issue by fjorba** [rism-digital/muscat#1129]
After filling all fields for a new user in 7.1, pressing the `Save and close` button does nothing, and the user is not created.  The `Cancel` button, instead, does work.

If the problem is some field validation, there is no message indicated where is the error.

**Comment by xhero** [comment]
Yes! Fixed in 7.1.1 here: 2cc60de5f1924dc6377eaa1e878767e39a0e7c23
I will make 7.1.1 later today with a couple other last minute fixes

**Comment by fjorba** [comment]
Great, I'll update my sites. Thanks!
