### ISSUE TITLE
Where to document Muscat authentication, including SSO config?

### ISSUE THREAD

**Issue by fjorba** [rism-digital/muscat#1130]
Now that @tramuntanal is finishing his #1111 patch, we are unsure where to document it.  At this moment there is no clear documentation how users are authenticated in Muscat, and it takes a while before getting familiarised with it to understand what does it offer.

In the #1111 patch, there are some instructions in 250c61b2980468690f6a5c9b6e9683dd44276f0e, but myself, I think that a more tutorial-like document would help newcomers.  My draft would be something like that:

> Default Muscat authentication is :database_authenticatable, that means that users are created in Muscat's own local database. If this is fine to you, there is no need to modify anything.
>
> There is an alternative Single Sign On authentication for corporate environments. If you are interested, please follow those steps:
>
> 1. In config/application.rb, add :saml_authenticatable to AUTHENTICATION_METHODS and save the file.
> 2. Then, execute `bin/rails generate muscat:install_saml`. This step will create two configuration files, that will exist only if :saml_authenticatable is added: config/initializers/devise_saml_authenticatable.rb and config/attribute-map.yml.
> 3. In config/initializers/devise_saml_authenticatable.rb, pay attention to the last section, where the settings.* values are set.  You will find some default values to help setting your own ones.
> 4. In config/attribute-map.yml, you can map the SSO server values (first column) with the local Muscat values (second column) if they don't match. There are a couple of example values.
> 5. Finally, back in config/application.rb, please uncomment the line SAML_AUTHENTICATION_CREATE_USER_ROLE = 'guest', that states which role assume new locally created users authenticated via SSO.

It could go into 2- INSTALL.rdoc, or redirect from there to some other file, like  lib/generators/muscat/install_saml_generator.rb

Depending on how would you prefer it, we could work on making a single document or split it into two.

**Comment by xhero** [comment]
I would add it in the main INSTALL document, so it is easy to find

**Comment by fjorba** [comment]
Done, thank you!
