### ISSUE TITLE
Add "e" designation to holdings containing links to digital sources

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#1132]
Referencing #930 where it was first brought up, and because a Muscat user asked about it today:

More than once I've wished there was a quick way to see which prints had links to digital surrogates (to save the step of going to the OPAC). Can you add a small symbol either on the right under "Exemplar information" or below by the holding libraries?

**Comment by xhero** [comment]
You mean in edit mode or both in edit/show (in muscat)?
