### ISSUE TITLE
Redirect to original link after logging in

### ISSUE THREAD

**Issue by ahankinson** [rism-digital/muscat#1134]
If I am not logged in to Muscat and I click a link to a record, it will take me to the login screen. When I log-in, though, it takes me to the front-page of the admin, instead of to the original record. 

It would be fantastic if after logging in it would take me to the original link.

**Comment by jenniferward** [comment]
Yes, this is annoying!

**Comment by xhero** [comment]
Fixed in 2b1b59e875b154804dba5df024fbd9a8e98f82af
