### ISSUE TITLE
Search for digital sources and order of 856s

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#1143]
Re this ticket: #1132 
It seems like the order of 856s makes a difference as to whether an "e" is displayed. 
https://muscat.rism.info/admin/sources/993122035 
I-Bc

https://muscat.rism.info/admin/holdings/327035

The 856 with the bib record was first and the digital source was second, and no "e" appeared.
Then the order was switched so that the digital source was first, and an "e" appeared.

**Comment by xhero** [comment]
This was actually fixed in 11.1!
