### ISSUE TITLE
Remove obsolete comments attribute from Person model

### ISSUE THREAD

**Issue by fjorba** [rism-digital/muscat#1168]
Person attributes are created from Marc authority fields.  Currently, Muscat takes person comments from 680 $i:

https://github.com/rism-digital/muscat/blob/c801afabd99b14b25b10609bd29ecbae15fc20d5/lib/marc_person.rb#L71

This field is as reasonable as $a, see:

https://www.loc.gov/marc/authority/ad680.html

However, it turns out that editing a Person authority record, the 680 field creates a single $a subfield.  So, as only 680 $a is used, probably the person model attribute should take it also from $a.

**Comment by xhero** [comment]
@jenniferward Can you have a look? It seems we never really use the "comments" field and just use 680 $a as a reference pointer (i.e. WollnyT 2016)

**Comment by jenniferward** [comment]
Strange. Thanks for catching this, @fjorba. I looked at the LC documentation for $i, and no, we don't record that kind of information in the personal names authorities (nor do we have to with people).

**Comment by fjorba** [comment]
From the personal authority records downloaded from https://opac.rism.info/main-menu-/kachelmenu/data, there are 19,995 records with 680 tag, and all them have a $a (and in different languages, whatever it means) and none of them has a $i, for example:

```
680    $a Seit 1891 Hofkantor in Dresden
680    $a Deutscher Seminaroberlehrer und seit 1896 Kantor an der Annenkirche Dresden
680    $a 1889-1895 Organist an der Dresdner Sophienkirche
680    $a Organist an der Dresdner Synagoge
680    $a Seit 1887 Kantor an der Martin-Luther-Kirche in Dresden
680    $a Musikdirektor und Kantor der Friedrichstädter Kirche in Dresden
680    $a Gemahlin des Fürsten Viktor Amadeus von Anhalt-Bernburg
680    $a Hofprediger
680    $a Pfarrer
680    $a 1891 Heirat mit dem Kaufmann Stefan Liebel
680    $a 1786-1817 Mitglied (Violoncello) der Dresdner Hofkapelle
680    $a He served the church as accounting officer, bookkeeper, cashier and responsible assistant to the administrator of properties and as a teacher in Gracehill, Ireland (1831-37), Zeist, Holland (1837-?), Neuwied, Germany (?-1840), and finally in Bethlehem, PA.
680    $a He served as organist and choir director from 1841-1867.  Professor of Mineralogy, Lehigh University, 1866-?
680    $a 1873 Heirat mit Hugo Weidel (1849-1899)
680    $a Landeskirchenmusikdirektor
680    $a casado en 1892
680    $a Casada en 1892
680    $a 1809 Heirat mit Georg Wilhelm Friedrich von Platen Hallermund (1785-1873)
680    $a Seit 1814 erster Oboist im Mannheimer Theaterorchester
680    $a 1832 Ernennung zum Hofmusikus
```

So, the 680 field is used; what I'm not sure if it used used is the internal, Rails attribute for Person Model

**Comment by jenniferward** [comment]
Correct, it's only $a, and it's a catch-all "general note" field to put into plain language some aspects that don't fit elsewhere.

**Comment by fjorba** [comment]
Correct, so just changing

```diff
-if node = first_occurance("680", "i")
+if node = first_occurance("680", "a")
```
in lib/marc_person.rb would make this field available as an internal, easy-to-reach Rails model attribute. However, I personally haven't found code that makes use of it; maybe I've just not looked enough.

**Comment by xhero** [comment]
But we already put $a in the `source` attribute of the model, I don't think we need to duplicate it. I think `comments` is just a residuate from pre-marc21 People, when all the properties were stored directly in the DB.

**Comment by fjorba** [comment]
I see.  So, this issue should be turned into something like _Remove obsolete comments attribute from Person model_?

I can create a patch, if you dare to trust me 🙃

**Comment by xhero** [comment]
Yes please! I think the `comments` attribute is never filled in
