### ISSUE TITLE
Orphaned holding records

### ISSUE THREAD

**Issue by ahankinson** [rism-digital/muscat#1174]
There are currently 71 holding records that have a source ID value for a source that no longer exists.

```
SELECT holdings.id AS id, holdings.source_id AS source_id, holdings.marc_source AS marc_source,
       sources.std_title AS source_title, sources.composer AS creator_name,
       sources.record_type as record_type, sources.marc_source AS source_record_marc
FROM muscat_development.holdings AS holdings
LEFT JOIN muscat_development.sources AS sources ON holdings.source_id = sources.id
WHERE sources.marc_source IS NULL;
```

**Comment by BaMikusi** [comment]
Thanks, but could one actually see a list of these? I am assuming these must have belonged to duplicate source records that were at some point deleted -- if so, the surviving source ID's likely feature the same holding records, and these could be deleted, but it would be nice to be sure.

**Comment by ahankinson** [comment]
Sure, but I'm not sure how useful it is -- all of the source records lead to a "This source has been deleted" notice, and I can't seem to link directly to the holding record. I've included the holding ID, though, in case you know how?

I don't think you would be able to tell if it was a duplicate or not. As a deleted record there is no other information in the database -- no title, composer, or otherwise. I've included the MARC records from the holdings, in case that's helpful.

| holding\_id | source\_id | marc\_source |
| :--- | :--- | :--- |
| 2032 | https://muscat.rism.info/admin/sources/1000000592 | =001  2032<br/>=852  10$aPL-Kj$cMus.ant.pract. S 930$eBiblioteka Jagiellońska$qS, A, T, B, 5$x30002079<br/> |
| 37723 | https://muscat.rism.info/admin/sources/990010216 | =001  37723<br/>=852  10$aCZ-Pk$c\[no indication\]$eKnihovna Pražské konzervatoře, specializovaná knihovna$x30000606<br/> |
| 66732 | https://muscat.rism.info/admin/sources/990018853 | =001  66732<br/>=852  10$aD-Ngm$c\[no indication\]$eGermanisches National-Museum, Bibliothek$qS, A, T II$x30000934<br/> |
| 73140 | https://muscat.rism.info/admin/sources/990020812 | =001  73140<br/>=852  10$aF-Pc$c\[no indication\]$eBibliothèque du Conservatoire$qunvollständig$x30001480<br/> |
| 73146 | https://muscat.rism.info/admin/sources/990020814 | =001  73146<br/>=852  10$aD-B$c\[no indication\]$eStaatsbibliothek zu Berlin - Preußischer Kulturbesitz, Musikabteilung$x30000655<br/> |
| 73147 | https://muscat.rism.info/admin/sources/990020814 | =001  73147<br/>=852  10$aGB-Lbl$c\[no indication\]$eThe British Library$q2 Ex., davon 1 Ex. unvollständig$x30001581<br/> |
| 85066 | https://muscat.rism.info/admin/sources/990024034 | =001  85066<br/>=852  10$aCZ-Bm$c\[no indication\]$eMoravské zemské muzeum, oddělení dějin hudby$x30000015<br/> |
| 85074 | https://muscat.rism.info/admin/sources/990024039 | =001  85074<br/>=852  10$aCZ-Bm$c\[no indication\]$eMoravské zemské muzeum, oddělení dějin hudby$x30000015<br/> |
| 123420 | https://muscat.rism.info/admin/sources/990031953 | =001  123420<br/>=852  10$aCH-Lz$c\[no indication\]$eZentral- und Hochschulbibliothek$q2 Ex.$x30000523<br/> |
| 123421 | https://muscat.rism.info/admin/sources/990031953 | =001  123421<br/>=852  10$aCH-P$c\[no indication\]$eBibliothèque cantonale jurassienne \(incl. Bibliothèque du lycée cantonal\)$x30000531<br/> |
| 123422 | https://muscat.rism.info/admin/sources/990031954 | =001  123422<br/>=852  10$aCH-Bu$c\[no indication\]$eUniversitätsbibliothek, Musiksammlung$q2 Ex.$x30000003<br/> |
| 138609 | https://muscat.rism.info/admin/sources/990036073 | =001  138609<br/>=852  10$aF-Pn$c\[no indication\]$eBibliothèque nationale de France, Département de la Musique$x30001488<br/> |
| 161522 | https://muscat.rism.info/admin/sources/990042188 | =001  161522<br/>=852  10$aGB-Lbl$cK.9.a.10.$eThe British Library$q34 f.$uhttp://purl.org/rism/BI/1550/4$x30001581<br/>=856  ##$uhttp://purl.org/rism/BI/1550/4$z\[digitized version\]<br/> |
| 161565 | https://muscat.rism.info/admin/sources/990042199 | =001  161565<br/>=852  10$aA-Wn$c\[no indication\]$eÖsterreichische Nationalbibliothek, Musiksammlung$qkpl.: S, A, T, B$x30000398<br/> |
| 161566 | https://muscat.rism.info/admin/sources/990042199 | =001  161566<br/>=852  10$aD-AN$c\[no indication\]$eStaatliche Bibliothek Ansbach, Schlossbibliothek$qA, B$x30000647<br/> |
| 161567 | https://muscat.rism.info/admin/sources/990042199 | =001  161567<br/>=852  10$aD-Mbs$c\[no indication\]$eBayerische Staatsbibliothek$x30000882<br/> |
| 161568 | https://muscat.rism.info/admin/sources/990042199 | =001  161568<br/>=852  10$aE-V$c\[no indication\]$eArchivo Musical de la Catedral de Valladolid$qA$x30001403<br/> |
| 161569 | https://muscat.rism.info/admin/sources/990042199 | =001  161569<br/>=852  10$aI-Bc$c\[no indication\]$eMuseo internazionale e biblioteca della musica di Bologna$x30001740<br/> |
| 161570 | https://muscat.rism.info/admin/sources/990042199 | =001  161570<br/>=852  10$aV-CVbav$c\[no indication\]$eBiblioteca Apostolica Vaticana$qB \[unvollständig\]$x30077306<br/> |
| 161571 | https://muscat.rism.info/admin/sources/990042199 | =001  161571<br/>=852  10$aI-Vnm$c\[no indication\]$eBiblioteca Nazionale Marciana$qB$x30000170<br/> |
| 161572 | https://muscat.rism.info/admin/sources/990042199 | =001  161572<br/>=852  10$aPL-Kj$cMus.ant.pract. M 1040$eBiblioteka Jagiellońska$qA, T$x30002079$zMORALIS HISPANI \| ET MVLTORVM EXIMIAE ARTIS VIRORVM MVSICA \| CVM VOCIBVS QVATVOR VVLGO \| MOTECTA COGNOMINATA \| QVATVOR VOCVM \| Venetijs Apud Antonium Gardane. \| M. D. XDXXXVI.$zNo names of composers in the publication; according to RISM.<br/> |
| 184963 | https://muscat.rism.info/admin/sources/990047077 | =001  184963<br/>=852  10$aA-Wn$c\[no indication\]$eÖsterreichische Nationalbibliothek, Musiksammlung$x30000398<br/> |
| 210134 | https://muscat.rism.info/admin/sources/990053747 | =001  210134<br/>=852  10$aGB-Lbl$c\[no indication\]$eThe British Library$x30001581<br/> |
| 210135 | https://muscat.rism.info/admin/sources/990053747 | =001  210135<br/>=852  10$aI-Ra$c\[no indication\]$eBiblioteca Angelica$x30001897<br/> |
| 240176 | https://muscat.rism.info/admin/sources/990061170 | =001  240176<br/>=852  10$aD-Dl$c\[no indication\]$eSächsische Landesbibliothek - Staats- und Universitätsbibliothek \(SLUB\)$x30000042<br/> |
| 240177 | https://muscat.rism.info/admin/sources/990061170 | =001  240177<br/>=852  10$aD-WRdn$c\[no indication\]$eDeutsches Nationaltheater, Archiv$qvorhanden nur vl I der 1. partie$x30000065<br/> |
| 240178 | https://muscat.rism.info/admin/sources/990061170 | =001  240178<br/>=852  10$aF-Pn$c\[no indication\]$eBibliothèque nationale de France, Département de la Musique$qzusätzlich 2. Ex.: 1.partie$x30001488<br/> |
| 240179 | https://muscat.rism.info/admin/sources/990061170 | =001  240179<br/>=852  10$aI-OS$c\[no indication\]$eBiblioteca musicale Giuseppe Greggiati$x30003098<br/> |
| 240180 | https://muscat.rism.info/admin/sources/990061170 | =001  240180<br/>=852  10$aUS-Wc$c\[no indication\]$eThe Library of Congress, Music Division$x30002492<br/> |
| 262516 | https://muscat.rism.info/admin/sources/990068153 | =001  262516<br/>=852  10$aCH-Zz$c\[no indication\]$eZentralbibliothek, Musikabteilung$x30000014<br/> |
| 272303 | https://muscat.rism.info/admin/sources/990070882 | =001  272303<br/>=852  10$aF-Pthibault$c\[no indication\]$eBibliothèque Geneviève Thibault$x30001496<br/> |
| 272304 | https://muscat.rism.info/admin/sources/990070882 | =001  272304<br/>=852  10$aGB-Lbl$cK.9.a.23.$eThe British Library$uhttp://purl.org/rism/BI/1528/1$x30001581<br/>=856  ##$uhttp://purl.org/rism/BI/1528/1$z\[digitized version\]<br/> |
| 273534 | https://muscat.rism.info/admin/sources/990071728 | =001  273534<br/>=852  10$aF-Pn$c\[no indication\]$eBibliothèque nationale de France, Département de la Musique$x30001488<br/> |
| 281583 | https://muscat.rism.info/admin/sources/991006518 | =001  281583<br/>=852  10$aUS-Bp$c\[no indication\]$eBoston Public Library, Music Department$x30002202<br/> |
| 284706 | https://muscat.rism.info/admin/sources/991011286 | =001  284706<br/>=852  10$aD-KIl$c\[no indication\]$eSchleswig-Holsteinische Landesbibliothek$x30000848<br/> |
| 284707 | https://muscat.rism.info/admin/sources/991011286 | =001  284707<br/>=852  10$aD-LÜh$c\[no indication\]$eStadtbibliothek, Musikabteilung$x30000877<br/> |
| 286492 | https://muscat.rism.info/admin/sources/991012997 | =001  286492<br/>=852  10$aD-OF$c\[no indication\]$eVerlagsarchiv André$x30000954<br/> |
| 297833 | https://muscat.rism.info/admin/sources/991019233 | =001  297833<br/>=852  10$aCH-BEl$c\[no indication\]$eSchweizerische Nationalbibliothek$x30000004<br/> |
| 313545 | https://muscat.rism.info/admin/sources/992004609 | =001  313545<br/>=852  10$aCH-E$c\[no indication\]$eKloster Einsiedeln, Musikbibliothek$qvl I \[p. 3-10, unvollständig\]$x30000006<br/> |
| 313791 | https://muscat.rism.info/admin/sources/992004972 | =001  313791<br/>=852  10$aUS-Charding$c\[no indication\]$eN. H. Harding private collection$qS$x30002224<br/> |
| 317890 | https://muscat.rism.info/admin/sources/993000197 | =001  317890<br/>=852  10$aD-Mbs$c4 Mus.pr. 62714/20$eBayerische Staatsbibliothek$qSingst. mit pf Umfang: 2 ungez. Bl.$x30000882<br/> |
| 318493 | https://muscat.rism.info/admin/sources/1000000426 | =001  318493<br/>=852  10$aPL-Kj$cMus.ant.pract. S 1130$eBiblioteka Jagiellońska$qT \[1 Ex.\]$x30002079<br/> |
| 318533 | https://muscat.rism.info/admin/sources/1000000466 | =001  318533<br/>=852  10$aPL-Kj$cMus.ant.pract. V 405$eBiblioteka Jagiellońska$qS, A, T, B, 5$x30002079<br/> |
| 318592 | https://muscat.rism.info/admin/sources/1000000528 | =001  318592<br/>=852  10$aPL-Kj$cMus.ant.pract. R 356$eBiblioteka Jagiellońska$q1 Ex.$x30002079$zShort monophonic melodies.<br/> |
| 318721 | https://muscat.rism.info/admin/sources/1001000085 | =001  318721<br/>=852  ##$aPL-Wnifc$bBiblioteka Narodowego Instytutu Fryderyka Chopina$c2009/n$eNarodowy Instytut Fryderyka Chopina$x51003139<br/> |
| 318722 | https://muscat.rism.info/admin/sources/1001000085 | =001  318722<br/>=852  ##$aCZ-Pu$c\[without shelfmark\]$eNárodní knihovna České republiky$x30000083<br/> |
| 319078 | https://muscat.rism.info/admin/sources/1001014524 | =001  319078<br/>=852  ##$aF-Pc$c\[no indication\]$eBibliothèque du Conservatoire$x30001480<br/> |
| 319589 | https://muscat.rism.info/admin/sources/1001031599 | =001  319589<br/>=852  ##$aRUS-SPk$cИнв. № 199$eSankt-Peterburgskaja gosudarstvennaja konservatorija imeni N. A. Rimskogo-Korsakova, Naučnaja muzykal'naja biblioteka $x30002520$zLabel: "Библиотека Императорcкаго Русскаго Музыкальнаго Общества. Ззапа ... Шкаф № 15. Полка № 2. № 12"  710Library of the russian music association$zStamp: "Русскоe Музыкальноe Обществo" 710Russian music association<br/> |
| 319590 | https://muscat.rism.info/admin/sources/1001031602 | =001  319590<br/>=852  ##$aRUS-SPk$cИнв. № 2 или 6055 \(OРК\)$eSankt-Peterburgskaja gosudarstvennaja konservatorija imeni N. A. Rimskogo-Korsakova, Naučnaja muzykal'naja biblioteka $x30002520$zNote of Provenance: "Darquistade de S. \[?\] futgent""$zLabel: "Библиотека Императорcкаго Русскаго Музыкальнаго Общества \[...\]"$zStamp: "Императорcкое Русское Музыкальное Общество. С. Петербургское Отделение" 710: Imperial Russian Music Society, division St. Petersburg<br/> |
| 320010 | https://muscat.rism.info/admin/sources/1001034797 | =001  320010<br/>=561  ##$atitle page, at foot right, handwritten: "for \| Vanda Ossolinska."<br/>=700  1#$aOssolińska, Wanda$jAscertained$041010856$4fmo<br/>=852  ##$aPL-KOZmzk$cmzk/m/71$eMuzeum Zamoyskich w Kozłówce$x51000446<br/> |
| 329052 | https://muscat.rism.info/admin/sources/1001045231 | =001  329052<br/>=300  ##$a17 printed parts<br/>=500  ##$aTop inscribed: 19 \[another hand:\] No 242. Bound in partbooks with other symphonies and overtures. The number 19 inscribed on the tp refers to the order of this edition in the partbooks.<br/>=506  ##$aUse restricted by the terms of the Moravian Music Foundation Research Policies.<br/>=561  ##$aFrom the Moravian Church, Northern Province, Eastern District. Lititz Congregation \(Lititz Collegium Musicum Collection LCM 242 Beth pr\).<br/>=563  ##$aBound in partbooks in Collection of symphonies and overtures in 17 partbooks by various composers<br/>=710  2#$aLititz Collegium Musicum \(Lititz, Pa.\)$gAscertained$051000608$4fmo<br/>=710  2#$aMoravian Music Foundation$gAscertained$030002214$4asn<br/>=852  ##$aUS-BETm$cLCM 242 Beth pr$eMoravian Music Foundation$qfl \(2\); ob \(2\); cl \(2\); fag 1; clno 1; cor \(2\); vln 1\(2\), 2\(2\); vla; vlc; b\(2\)$x30002214<br/>=856  ##$uhttps://moravianmusic.on.worldcat.org/oclc/946886842$xOther$zOriginal catalog entry<br/>=973  ##$u240433<br/> |
| 329475 | https://muscat.rism.info/admin/sources/1001048107 | =001  329475<br/>=506  ##$aUse restricted by the terms of the Moravian Music Foundation Research Policies.<br/>=561  ##$aFrom the Moravian Church, Northern Province, Eastern District. Lititz Congregation \(Lititz Collegium Musicum Collection LCM 242 Beth pr\).<br/>=563  ##$aBound in partbooks in Collection of symphonies and overtures in 17 partbooks by various composers<br/>=710  2#$aLititz Collegium Musicum \(Lititz, Pa.\)$gAscertained$051000608$4fmo<br/>=710  2#$aMoravian Music Foundation$gAscertained$030002214$4asn<br/>=852  ##$aUS-BETm$cLCM 242 Beth pr$eMoravian Music Foundation$x30002214<br/>=856  ##$uhttps://moravianmusic.on.worldcat.org/oclc/946886842$xOther$zOriginal catalogue entry<br/> |
| 330032 | https://muscat.rism.info/admin/sources/1001050541 | =001  330032<br/>=852  ##$aA-Wn$cM. S. 15513$eÖsterreichische Nationalbibliothek, Musiksammlung$x30000398<br/> |
| 330043 | https://muscat.rism.info/admin/sources/1001050587 | =001  330043<br/>=852  ##$aA-ISCHlv$c125$eLehár-Villa$x51000476$zNachlass Franz Lehár<br/> |
| 330100 | https://muscat.rism.info/admin/sources/1001051050 | =001  330100<br/>=852  ##$aA-ISCHlv$c148$eLehár-Villa$x51000476$zNachlass Franz Lehár<br/> |
| 330113 | https://muscat.rism.info/admin/sources/1001051151 | =001  330113<br/>=852  ##$aA-ISCHlv$c149$eLehár-Villa$x51000476$zNachlass Franz Lehár<br/> |
| 51002213 | https://muscat.rism.info/admin/sources/1001053729 | =001  51002213<br/>=300  ##$a10 printed parts<br/>=506  ##$aUse restricted by the terms of the Moravian Music Foundation Research Policies.<br/>=561  ##$aFrom the Moravian Church, Northern Province, Eastern District. Lititz Congregation \(Lititz Collegium Musicum Collection LCM 48 Beth pr\).<br/>=563  ##$aIncluded in op. 3 instrumental parts$u990060782<br/>=710  2#$aLititz Collegium Musicum \(Lititz, Pa.\)$gAscertained$051000608$4fmo<br/>=710  2#$aMoravian Music Foundation$gAscertained$030002214$4asn<br/>=852  ##$aUS-BETm$cLCM 48 Beth pr$eMoravian Music Foundation$qob \(2\), cor \(2\), vl princ, vl \(2\), vla, vlc obl, b.fig$x30002214<br/>=856  ##$uhttps://moravianmusic.on.worldcat.org/oclc/1061505774$xOther$zOriginal catalog entry<br/> |
| 51005835 | https://muscat.rism.info/admin/sources/1001078629 | =001  51005835<br/>=852  ##$aA-ISCHlv$c342$eLehár-Villa$x51000476$zNachlass Franz Lehár<br/> |
| 51005902 | https://muscat.rism.info/admin/sources/1001079431 | =001  51005902<br/>=710  2#$aZbierka hudobnín Evanjelického a. v. kostola v Bratislave$051002799$4fmo<br/>=852  ##$aSK-BRnm$cMUS XIX 905$eSlovenské národné múzeum - Hudobné múzeum$x30000017<br/> |
| 51007068 | https://muscat.rism.info/admin/sources/1001087252 | =001  51007068<br/>=500  ##$aOn the third side is the signature: ''Kopecsny''.<br/>=500  ##$aAuthorship of the piece identified by a record in Rism ID no: 201002814.<br/>=710  2#$aZbierka hudobnín Leopolda Dušinského z Nitry$051002800$4fmo<br/>=852  ##$aSK-BRnm$cMUS XIV 50$eSlovenské národné múzeum - Hudobné múzeum$x30000017<br/> |
| 51008626 | https://muscat.rism.info/admin/sources/1001095983 | =001  51008626<br/>=591  ##$a366<br/>=852  ##$aCZ-K$c321$eStátní oblastní archiv v Třeboni, pobočka Český Krumlov$x30000183<br/> |
| 51009537 | https://muscat.rism.info/admin/sources/403005228 | =001  51009537<br/>=300  ##$a1 score: 40p.$c21,5 x 14 cm<br/>=852  ##$aCH-E$c216,2b$eKloster Einsiedeln, Musikbibliothek$x30000006<br/> |
| 51010391 | https://muscat.rism.info/admin/sources/400102803 | =001  51010391<br/>=300  ##$a1 part$c35,5 x 28 cm<br/>=500  ##$aIncomplete material<br/>=500  ##$aVollständige Ausgabe dieses Sammeldruckes vergleiche CH E 671,4<br/>=500  ##$aother parts missing<br/>=691  #7$aRepertoriumSchweiz$02564$2CH-BeSRO<br/>=852  ##$aCH-E$c480,1$eKloster Einsiedeln, Musikbibliothek$qSolo: S and A$x30000006<br/> |
| 51013408 | https://muscat.rism.info/admin/sources/408000419 | =001  51013408<br/>=300  ##$a1 part$c23 x 34 cm<br/>=506  ##$aKonsultation nur vor Ort<br/>=506  ##$aReproduktion kostenpflichtig<br/>=852  ##$aCH-SAf$bMusikbibliothek$cMusSAf.Dr.264$eBenediktinerinnen-Abtei St. Andreas \[Sarnen\]$qpf$x30000011<br/> |
| 51016702 | https://muscat.rism.info/admin/sources/1001108967 | =001  51016702<br/>=500  ##$aOn the title page "Band II." is in a circle drawn with pencil.<br/>=500  ##$aOn the title page in the right upper corner there is a round grey stamp: "INSTYTUT FRYDERYKA CHOPINA \[in handwriting:\] 455."<br/>=500  ##$aOn the title page in the right bottom corner there is a purple stamp: "Julius Hainauer, Breslau I \| Musikalien-Versand \| Schweidnitzerstr. 52. \* Telefon 1914."<br/>=500  ##$aOn p. \[ii\], at the bottom, there is a round grey stamp: "BIBLIOTEKA NARODOWY INSTYTUT FRYDERYKA CHOPINA".<br/>=506  ##$aTreasury of the Library<br/>=852  ##$aPL-Wnifc$bBiblioteka Narodowego Instytutu Fryderyka Chopina$c455/n$eNarodowy Instytut Fryderyka Chopina$x51003139<br/> |
| 51016748 | https://muscat.rism.info/admin/sources/1001109084 | =001  51016748<br/>=506  ##$aUse restricted by the terms of the Moravian Music Foundation Research Policies.<br/>=561  ##$aFrom the Moravian Church, Northern Province, Eastern District. Bethlehem Congregation \(Philharmonic Society of Bethlehem Collection PSB 44, folder 4 Beth ms/pr\).<br/>=710  2#$aPhilharmonic Society of Bethlehem$gAscertained$051000616$4fmo<br/>=710  2#$aMoravian Music Foundation$gAscertained$030002214<br/>=852  ##$aUS-BETm$cPSB 44.2 Beth pr$eMoravian Music Foundation$x30002214<br/>=856  ##$uhttps://moravianmusic.on.worldcat.org/oclc/22865928$xOther$zOriginal catalogue entry<br/> |
| 51016823 | https://muscat.rism.info/admin/sources/1001096303 | =001  51016823<br/>=500  ##$aFirst four pages are missing in the part of timpani.<br/>=500  ##$aTitle page is very dirty and torn.<br/>=700  1#$aSchwarzenberg$041008092$4fmo<br/>=852  ##$aCZ-K$c69$eStátní oblastní archiv v Třeboni, pobočka Český Krumlov$x30000183<br/> |
| 51016824 | https://muscat.rism.info/admin/sources/1001096281 | =001  51016824<br/>=035  ##$a26b<br/>=035  ##$a26c<br/>=700  1#$aSchwarzenberg$041008092$4fmo<br/>=852  ##$aCZ-K$c335$eStátní oblastní archiv v Třeboni, pobočka Český Krumlov$x30000183<br/> |
| 51017075 | https://muscat.rism.info/admin/sources/1001111248 | =001  51017075<br/>=852  ##$aPL-KOZmzk$cmzk/m/28$eMuzeum Zamoyskich w Kozłówce$x51000446<br/>=973  ##$u1001083395<br/> |
| 51017084 | https://muscat.rism.info/admin/sources/1001096207 | =001  51017084<br/>=852  ##$aCZ-K$c344 $eStátní oblastní archiv v Třeboni, pobočka Český Krumlov$x30000183<br/> |
| 51017131 | https://muscat.rism.info/admin/sources/1001095878 | =001  51017131<br/>=852  ##$aCZ-K$c320 $eStátní oblastní archiv v Třeboni, pobočka Český Krumlov$x30000183<br/> |

**Comment by jenniferward** [comment]
I presume they were all merged with other records, but I can run the holdings numbers against earlier data dumps (provided the records were published in the OPAC) in order to find fuller bib information if @BaMikusi thinks that would be helpful.

**Comment by BaMikusi** [comment]
Many thanks to Andrew for the list, it was most useful to see which libraries were affected by the plague of deletions. We briefly discussed the issue with @jenniferward today, and the chances of having here any unduplicated holding records is so slight that it is not worth the hassle to run another round to check, so feel free to delete these orphans.

**Comment by xhero** [comment]
@jenniferward some of the source records from these holdings seem to have been deleted quite recently, how were deleted? Or they are deleted automatically when merged (in this case, Houston we have a problem...)?

**Comment by jenniferward** [comment]
"merging" is just our shorthand for "copying and pasting relevant fields, then deleting everything manually" so I don't think that was a problem.

We used to be able to delete bib record + holdings all at once with one click, but at some point (when?? I can't find it) it was (wisely) changed so you have to delete the holdings first, then the bib record. Holding 51017130 (one before 51017131, which is on the above list) is from November 2019 so I wonder if they all date from before this time. If you delete a record, any associated comments live on here https://muscat.rism.info/admin/comments/ so I wonder if this is a similar thing: if the bib record is deleted, the holdings actually weren't?

That's my impression--or @xhero do you have a closer definition of "quite recently"?

**Comment by xhero** [comment]
I made a google doc resurrecting the deleted sources:

https://docs.google.com/spreadsheets/d/1cRJt3qc5AGWbZHRoZbnCL_I-Rc0PLr17GEBA_FEWBoE/edit#gid=0

We had a bug a couple years ago that you could delete Sources that had Holdings attached, but it was fixed between 2016-2018. Some of the deletion dates are quite recent (2020!), @jenniferward maybe you remember how you deleted those? In theory if a source has a holding Muscat will complain, I tested it and it seems to complain, so maybe there is a loophole somehow?
There are also two records that have no info - those still exist! They are orphaned holdings that happened during CH migration (sorry!) I can ask @baccia to review them and then I can delete them.

**Comment by xhero** [comment]
Correction,  403005228 and 400102803 were deleted but there is not delete event.

**Comment by baccia** [comment]
Done (see Google sheet): the two orphaned CH holdings 51009537 and 51010391 may be destroyed, the items' call numbers were attached to other records for the same print.

**Comment by jenniferward** [comment]
No, I can't think of a loophole, unless I deleted things so quickly that actions in my browser tabs overlapped and confused things. @BaMikusi Let me know if I need to do anything with Rodolfo's table above.

**Comment by xhero** [comment]
I don't think it can be multiple tabs or a race condition, since the holding has to be deleted before the source.

**Comment by BaMikusi** [comment]
Thanks, @jenniferward, I think it was insightful to discuss all of this, but looking into the details of concrete deletions would be of little use, so we can move on.

**Comment by xhero** [comment]
What should we do here? Delete the holdings and hope it does not happen again?

**Comment by ahankinson** [comment]
If it does happen we can catch it and investigate again?

**Comment by xhero** [comment]
Yes I think, maybe we will find them sooner and we can trace it to the problem. Shall I remove them in production then?

**Comment by BaMikusi** [comment]
Yes, get rid of the present set of records and try to catch new ones, should the incomplete deletion occur again, that seems the most effective strategy.

**Comment by xhero** [comment]
Holdings were deleted.
