### ISSUE TITLE
Change translation of The Vatican

### ISSUE THREAD

**Issue by ahankinson** [rism-digital/muscat#1179]
Currently The Vatican (the country) is translated as "Holy See" in the [translation files](https://github.com/rism-digital/translations/blob/main/locales/en.yml#L170).

As far as I can tell, "Holy See" refers to (in essence) the Government of the Vatican, rather than the name of the state itself. (It might be similar to calling the United Kingdom "Westminster Parliament" or Germany "Bundestag"). 

This does not align well with the siglum ("V") nor with the [Place authority](https://muscat.rism.info/admin/places/3900386) in Muscat. 

I would suggest changing this country name to "Vatican" or "Vatican City". I would avoid "The Vatican" since it's harder to sort.

Tagging @docudoctor, @HirschSt, @BaMikusi 

If agreed, I will make the change in the translation files, so I'll assign myself.

**Comment by jenniferward** [comment]
If I may intrude, while I agree, I believe we use the ISO Country Code names, which is indeed Holy See:
https://www.iso.org/obp/ui/#search
p. 4
I seem to recall a discussion about Viet Nam, though I can't find any documentation of it: 2 words is the ISO version, but we have it as Vietnam (though maybe that was my doing).

**Comment by ahankinson** [comment]
Yes, but even ISO-3166-2 uses "VA" as the actual code. :-D

I believe that the actual data that is stored in the `043 $c` is the GND code `XA-VA` (https://github.com/rism-digital/muscat/blob/96f7afc11bd7ee39750758efdf8174bbf3c39436/config/editor_profiles/default/configurations/PersonLabels.yml#L222-L223) so this is the human-readable label, instead of the stored value.

**Comment by ahankinson** [comment]
It's also technically incorrect, I think, to use Holy See, since this includes everything under the jurisdiction of the Pope which includes all Catholic believers globally. To say an institution is "located" in the Holy See could include churches and other institutions anywhere in the world.

Whereas I believe our use of this term is limited to the geographic region of Vatican City.

**Comment by jenniferward** [comment]
If we are allowed to move away from the ISO terms, then I would like to reconsider "Taiwan (Province of China)," which is a term that our colleagues in Taiwan have emphatically objected to. As a result, we don't use it (including the sigla records).

**Comment by ahankinson** [comment]
Sure; can you file an issue for that as well? I would like to keep this one focused on the Vatican.

**Comment by jenniferward** [comment]
Sure.
Elsewhere (https://github.com/rism-international/tasks/issues/924) I have suggested "Vatican City" for the user-friendly form of the name. See there also for other translations.

**Comment by ahankinson** [comment]
Ah brilliant! Thanks for referencing that.

**Comment by BaMikusi** [comment]
As long as this doesn't hopelessly mess up some standards, am fully in support of abandoning "Holy Sea" for "Vatican City".

**Comment by ahankinson** [comment]
This has been done in https://github.com/rism-digital/translations
