### ISSUE TITLE
Change translation of "Taiwan (Province of China)"

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#1180]
(coming from #1179)

Muscat uses the [ISO name "Taiwan (Province of China)"](https://www.iso.org/obp/ui/#iso:code:3166:TW) but for complicated political reasons, this is extremely problematic. As a result, we avoid using it at all. I propose moving away from ISO in this case and simply using "Taiwan". 

Background: 
- Correspondence with affected contributors from 27.05.2016: Do not use "China" in name; Taiwan should not be findable when searching "China". From ZR: "Province of China" generated automatically from Kallisto when using country code.
- Correspondence with ISO from 20 May 2016: "Taiwan (Province of China)" is ISO standard and cannot be changed.

**Comment by BaMikusi** [comment]
Sorry, but this is a no go. I fully understand that our colleagues in Taiwan hate the "Province of China" clause, but no one knows better than they do that writing simply "Taiwan" would be an explicit political statement that RISM cannot make. Until about two months ago altogether 15 countries recognized Taiwan as a sovereign country, namely the following world powers: Guatemala, Honduras, Haiti, Paraguay, Nicaragua, Eswatini, Tuvalu, Nauru, Saint Vincent and the Grenadines, Saint Kitts and Nevis, Saint Lucia, Marshall Isalnds, Palau, and the Vatican City. Then, on 18 November 2021 Taiwan was allowed to open a representative office (a kind of embassy) in Vilnius, and the ensuing major fallout between China and Lithuania you might have read about in the news everywhere. So, I do not object to getting around the one-China clause informally, but the official name cannot simply be Taiwan as long as there is no political consensus whatsoever about this interpretation worldwide.

**Comment by xhero** [comment]
What should I do here?

**Comment by BaMikusi** [comment]
Sorry, but there is nothing we can do other than closing this ticket without changing anything (with the war in Ukraine this topic has become even more sensitive than before).
