### ISSUE TITLE
Works: add "Folder" actions

### ISSUE THREAD

**Issue by MFalletta** [rism-digital/muscat#1182]
I miss the function to create a folder for works or to add an item to an existing folder.

**Comment by ahankinson** [comment]
![Screenshot 2022-01-06 at 10 11 13](https://user-images.githubusercontent.com/163183/148358506-aa651aca-f2b9-4438-b3eb-e213a9556707.png)

Do you see this on the Works list?

**Comment by MFalletta** [comment]
Yes of course, I just remembered me  - sorry!
