### ISSUE TITLE
Actions and holdings overlapping

### ISSUE THREAD

**Issue by BaMikusi** [rism-digital/muscat#1190]
Die Seitenleiste in der Datensatzansicht überdeckt beim Scrollen die Holdings der Drucke (Musikdruck Haupteintrag).
Bei Drucken mit vielen Exemplaren sieht man nicht alle https://muscat.rism.info/admin/sources/990045865 (s. Abb.). Bei Drucken mit wenigen Exemplaren, sieht es so aus, als wenn gar keine vorhanden wären (vgl. https://muscat.rism.info/admin/sources/1001184812). Hier sieht man die Holdings erst, wenn man nach unten scrollt.

![image](https://user-images.githubusercontent.com/70342380/149921066-9ff1d303-9d11-4919-82d5-7bbe56e4b22c.png)

**Comment by lpugin** [comment]
> The sidebar in the record view covers the holdings of the prints (music print main entry) when scrolling.
Prints with many copies do not show all https://muscat.rism.info/admin/sources/990045865 (see figure). For prints with few copies, it looks as if there are none at all (see https://muscat.rism.info/admin/sources/1001184812). Here you can only see the holdings when you scroll down.

**Comment by xhero** [comment]
I think we need a milestone for 8.0.1

**Comment by xhero** [comment]
I can fix this by making the status bar static when there are holdings, it is not super pretty but the holding bar can be very long and overflow, so that would be difficult to have it floating.

**Comment by jenniferward** [comment]
Right, that was the problem: Some editions have so many holding libraries that you wouldn't be able to see the bottom of the list if it were floating. 

If the status bar is static, then we are back to where we were before, right? So no net loss?

**Comment by BaMikusi** [comment]
When we discussed this at the meeting yesterday, no one had a ready idea how to the remedy this without returning to the original format (i.e. static status bar). If nothing better occurred to you, either, there is probably no royal road here.

**Comment by xhero** [comment]
I think for 8.0.1 I will do as follows:

* Sources with holdings: sidebars are static on top
* Sources without holdings: the sidebar is fixed on the side

I have a couple ideas on how to solve this but we need to test them more.
