### ISSUE TITLE
Spaces in Plaine & Easie code

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#1191]
We often get incipits where people put spaces at the beginning of the Plaine & Easie Code or in other random places. We would like a validation that warns about extra spaces. Really spaces should be limited to only in cases of changing the time signature, key signature, or clef, so they should only be allowed if ``` @ ```   ``` $ ``` or ```% ```  is nearby.

**Comment by BaMikusi** [comment]
"Nearby" is likely not specific enough for a validation, but since Verovio now gives a warning if a space is missing after a change of clef or times/key signature, it can apparently identify all such legitimate uses and, by way of exclusion, could in principle easily send a notification for all other spaces occurring in a PAE string.

**Comment by ahankinson** [comment]
Leading and trailing spaces can also be trimmed quite easily when the record is saved. Spaces in the middle cannot be, though.

**Comment by jenniferward** [comment]
Just a thought: Would it be worth replacing the space with an actual character? (Maybe use the character at the beginning and end of the change, like %C-1%'2A ?) Lengths of clef changes will be fixed, but the others are variable.

I have beginners who add spaces in their incipits, and it is not noticeable because it doesn't affect the display. They might do 
'' 4 C D E F or who knows where else.

**Comment by BaMikusi** [comment]
It sounds tempting to get rid of spaces altogether, but for now we should of course simply collect such ideas, and take a look at the whole picture at the end. (Should the revisions merely amount to a polish of the original? Or rather imply a thorough rewriting of the whole system -- which might not necessarily be welcome in all corners.)

**Comment by xhero** [comment]
Related to #1210, whitespace now is stripped from all marc tags, leading and trailing.

**Comment by jenniferward** [comment]
Does this include spaces in the middle? `'' 4 C D E F`

**Comment by lpugin** [comment]
@jenniferward no, this is only for the leading and trailing spaces

**Comment by jenniferward** [comment]
Is it possible to have a validation for the spaces in the middle (assuming it's something we don't want)?

**Comment by xhero** [comment]
Should this be done in the Verovio parser?

**Comment by lpugin** [comment]
Yes https://github.com/rism-digital/verovio/issues/2854

**Comment by jenniferward** [comment]
Thanks for clarifying.
