### ISSUE TITLE
Muscat 8.0.1 superfix

### ISSUE THREAD

**Issue by xhero** [rism-digital/muscat#1192]
Catch-all ticket for stuff to have in 8.0.1

- [x] `self.resource.class` in folder controller
- [x] index key in sru (see pull #1188)
- [x] `load_source false` in works
- [x] Make sure `auth_user` in application controller calls saml_user_signed_in? only if defined
- [x] Fix "OK" in comments
- [x] Fix sidebar #1190 
- [x] Fix total in modification digest
- [x] Couple small enhancements to the indexer
- [x] fix work count broken by https://github.com/rism-digital/muscat/commit/30cb4d6eac4545cbdd6ec4e6287993db0a2146e4
- [x] Revert Guidelines to html...
- [x] Re-add ppm, oth, fmo and dpt to Source 700/710 (#1123)
- [x] Update translations
- [x] Add Belarus (#1187)

more just add here

**Comment by lpugin** [comment]
* [ ] fix work count broken by https://github.com/rism-digital/muscat/commit/30cb4d6eac4545cbdd6ec4e6287993db0a2146e4
