### ISSUE TITLE
031$p validation: initial characters

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#1195]
Could you add this to the Plaine & Easie validation? It shouldn't be possible to begin the music incipit with a $, %, @. These are signals to change the clef, key, or time so they should only appear mid-incipit. However, there are old versions of the RISM guidelines floating around where you are instructed to begin the incipit by stating these elements and then the notes. So someone used to this would input  something like this ``` @3/2 {8''GAE} ``` and not see any error - and it would be hard for us editors to catch because the music looks fine.

A small thing, but would be helpful.

**Comment by xhero** [comment]
@lpugin I think we have WIP with @carlolic with this issue no? I would move this issue to Verovio if we want this since it will be implemented there I think
