### ISSUE TITLE
Incipit validation with beamed ornaments

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#1199]
I just received this from a user:
Beamed ornaments that appear mid-group aren't beaming in the display:
{''6FnEFbE}/{D'B{3''qC'qBqA}8B}''gD{8C'6AF}/''gC{'8B6AB}
![image](https://user-images.githubusercontent.com/18663291/150970450-2f2da628-f87f-4333-8120-cfe28f71b51d.png)

It used to appear as expected (see muscat-training):

![image](https://user-images.githubusercontent.com/18663291/150970656-8427c3a8-056f-4d20-b874-21694e499125.png)

The preference is to keep the internal beams. Is this possible?

**Comment by lpugin** [comment]
I think it makes sense to support
```
 {''6FnEFbE}/{D'Bqq{3''C'BA}r8B}''gD{8C'6AF}/''gC{'8B6AB}
```
That means only if the nested beam in opened **within** `qq...r`

**Comment by jenniferward** [comment]
Is it ok to advise our contributor to start using `qq{3''C'BA}r` in such cases (in part, to further avoid more q q q q q q q)?
