### ISSUE TITLE
One more PAE validation message

### ISSUE THREAD

**Issue by BaMikusi** [rism-digital/muscat#1200]
Just received the following notification while editing an incipit in Muscat:
"Duration content cannot be parsed (Setting to quarter note if running in non-pedantic mode)"
I had no memory of working on this sentence, so I checked the doc we used for #901
https://docs.google.com/spreadsheets/d/1bbQ2CzuyrgDTM3YTpm3FG4d_orTN5dqgjKJCiBXfzX8/edit?usp=sharing
and this indeed appears as an empty line there, without an English equivalent for Muscat users and DE/ES/PL translations.
Has this been added later on or am I simply going senile?

**Comment by lpugin** [comment]
It is triggered for example if you enter a `.` https://www.verovio.org/pae-editor.html?pae=8C. or `.8` instead of `8.`

I agree it is a bit cryptic, but so is PAE parsing ;-)

**Comment by BaMikusi** [comment]
I realize on my screen the right edge of the spreadsheet was not visible, and right there was the comment that we didn't quite understand this. And there is indeed one more line with a similar comment, namely ERR_058:
"Fermata on measure rest with extraneous content '%{value}'"
So what does this mean?

**Comment by jenniferward** [comment]
And one more clarification please, in the Key signature validation:
"The input contains one or more characters:"

**Comment by BaMikusi** [comment]
For ERR_052 we could perhaps simply say in Muscat:
"Duration cannot be interpreted, please revise."

**Comment by ahankinson** [comment]
🤖 does not compute.

**Comment by lpugin** [comment]
> "Fermata on measure rest with extraneous content '%{value}'"
> So what does this mean?

The Excel list is not up-to-date. It now says (at least in Verovio natively) "A fermata on measure with extra '1' is invalid."
https://www.verovio.org/pae-editor.html?pae=/(=1)/

**Comment by lpugin** [comment]
> And one more clarification please, in the Key signature validation:
"The input contains one or more characters:"

Could you give the code that triggers the error? Thanks

**Comment by jenniferward** [comment]
It doesn't say:
![image](https://user-images.githubusercontent.com/18663291/151027365-847f0de0-ec0d-4eec-bdc8-6d6f86b80307.png)

**Comment by lpugin** [comment]
What about `Key signature: The input contains one or more invalid character(s) 'sheep'` ?

**Comment by xhero** [comment]
if there is whitespace the witespace is not shown:

"`xFC  `" triggers `Key signature: The input contains one or more invalid character(s) ' '`

**Comment by xhero** [comment]
<img width="550" alt="Schermata 2022-01-25 alle 19 00 43" src="https://user-images.githubusercontent.com/1691778/151033118-2cc15cc9-1d67-408a-89ec-df6eb38c7f53.png">

**Comment by lpugin** [comment]
That is a good way for cataloguers to learn coding... They need to be precise, and when there is a warning they need to find what they messed up ;-) 

I can see the whitespace in `' '`, so I am still not sure I understand what the problem is.

**Comment by BaMikusi** [comment]
OK, my suggestions:
ERR_052: "Duration cannot be interpreted, please revise."
ERR_058: "The parantheses of a fermata can contain a single character (note or rest)."
"Key signature: Delete the invalid characters (including any whitespaces):"

**Comment by jenniferward** [comment]
I'd say:
ERR_052: "Duration cannot be interpreted." [To make it like ERR_040]
ERR_058: "The parentheses of a fermata must only contain a single note or rest."
"Key signature: Delete the following invalid characters (including any spaces):"

**Comment by BaMikusi** [comment]
Thanks, all three are fine with me. Does anyone else have further suggestions? If not, we could start having these translated and make sure they go live with the next update.

**Comment by BaMikusi** [comment]
PS: As I have now been correcting some messy key signatures in Muscat, the standard notification I received for out-of-place characters has been this:
"The input contains one or more character(s)"
But this, as it stands, reads rather odd -- of course the field contains characters, unless its left empty.
Also, if we mean to list those invalid characters after this message, should we not have a : after "character(s)"?

Sorry, this appears to be an endless story...

**Comment by jenniferward** [comment]
That seems to be a new one? I don't see it on our initial chart.

**Comment by BaMikusi** [comment]
I came across one more Verovio notification that we had not seen earlier and, as it stands, is certainly not for human consumption:
![muscat rism info_admin_sources_1001073818_edit (1)](https://user-images.githubusercontent.com/70342380/165953475-82775545-4961-4ebc-998a-e237723cf61e.png)
Can we provide an English translation?

**Comment by xhero** [comment]
For some reason ERR_041_NESTING_INVALID is not included in the translations at all, maybe it was one of those values that we thought would never show up?

**Comment by lpugin** [comment]
Yes, I think this is the reason. 

There will be a few more in the next release. https://github.com/rism-digital/verovio/blob/02e7e4ceadb11953755de271004d1c83c9a4636d/src/iopae.cpp#L2272-L2336

You should add them already.

**Comment by xhero** [comment]
I made a separate ticket: #1244
