### ISSUE TITLE
Value-lengthening dots not shown in mensural notation

### ISSUE THREAD

**Issue by BaMikusi** [rism-digital/muscat#1201]
https://muscat.rism.info/admin/sources/1001143547
Both incipits feature a dot each, but neither is shown in the incipit rendering.
(I thought that they might remain invisible because of being on the line, but no: if I change the pitch accordingly, still no dot appears.)

**Comment by BaMikusi** [comment]
NB: I just realize that Andrea Hartmann (SLUB) also brought up this problem in an email yesterday (one which I came to read in full only now). Might the fact that all three of us (she, Alessandra Ignesti and me) apparently bumped into this on the same day imply that the error may not have come with 8.0 but creeped in afterwards, e.g. with a hotfix (if there were any in this field)?

**Comment by xhero** [comment]
Yes we updated to verovio 3.8.1: 36ed84011081bc24425cd08174e1bd31100f5ac1

**Comment by lpugin** [comment]
I added an issue [here](https://github.com/rism-digital/verovio/issues/2599) and will fix it asap. 

It makes me think that there is one clarification we need to make, which that double dots cannot be supported in mensural notation. I am sure we will find some for sources of the transition period that can still look like mensural notation. In such cases, the incipit should be entered as CWMN.

**Comment by lpugin** [comment]
One example of double dots here (1.61.1) https://muscat.rism.info/admin/sources/990038698
That is for me a typical case where it should not be coded as mensural notation. The intention is probably only to reflect the visual aspect of the source.

**Comment by xhero** [comment]
Was this solved? We are using Verovio 3.9, so I think the patch from February is there.

**Comment by lpugin** [comment]
Yes!
