### ISSUE TITLE
Institutions, MARC field authority reference (024), further linking

### ISSUE THREAD

**Issue by Docudoctor** [rism-digital/muscat#1204]
Dear colleagues,
for linking to further authority file references please adopt these four basic URLs to the
1. BNE:  https://datos.bne.es/entidad
2. BNF: https://catalogue.bnf.fr/
3. ISNI: https://isni.org/isni/
4. LC: https://lccn.loc.gov/

DNB, VIAF and WKP are just working. 
Many thanks.
Guido

**Comment by xhero** [comment]
This came free after implementing #1205!
