### ISSUE TITLE
Mensural dots (7.) with modern clefs

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#1207]
Probably related to #1201 and in a way to #809:
Previously (in muscat-training it is still like this) you could use 7. with a modern clef:
![image](https://user-images.githubusercontent.com/18663291/151765345-9d7a9df5-982c-4c4f-a4ec-9be35b275ec8.png)

But now they are showing up as dotted 64ths:
![image](https://user-images.githubusercontent.com/18663291/151765450-15c3c5b5-410d-4712-b70f-7115de2c3ba9.png)

I think the users would like it to look how it did before, or is there a larger change I need to communicate?

**Comment by ahankinson** [comment]
This is a known issue and tracked here. I'll close this issue. 

https://github.com/rism-digital/verovio/issues/2593

**Comment by lpugin** [comment]
The notes will be changed to stemless notes. Ties are another issue. We also have plenty of them in mensural notation to encode ligatures. We probably want to tackle this properly in the PAE spec. One option would be to use another character for this to be used only with mensural notation or with `7.` and to migrate the data.

**Comment by ahankinson** [comment]
Should I open a new issue in the PAE code repo for ligatures?

**Comment by lpugin** [comment]
See https://github.com/rism-digital/pae-code-spec/issues/28
