### ISSUE TITLE
Add items to 856

### ISSUE THREAD

**Issue by xhero** [rism-digital/muscat#1211]
`IIIF Manifest` should be removed, instead we should have:

- IIIF Manifest (digitized source)
- IIIF Manifest (other)

**Comment by xhero** [comment]
@jenniferward is it OK to batch-change `IIIF Manifest` to `IIIF Manifest (digitized source)` everywhere and changed to "other" by hand if needed?

**Comment by jenniferward** [comment]
Yes: We will change to `IIIF Manifest (other)` as needed (I think there will be very few instances of this).

**Comment by ahankinson** [comment]
I think this is done so I will close it.
