### ISSUE TITLE
563 for handwritten treatises and libretti

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#1212]
Follow-up of #962
The field Binding (563) is back for the templates handwritten treatises (collection and source) and handwrtten libretti (collection and source), but the records where it was previously filled out—then removed—have landed in a "ungrouped fields" area:

https://muscat.rism.info/admin/sources/1001007121/edit
![image](https://user-images.githubusercontent.com/18663291/153580993-cdb2eee7-9ee4-4f80-83d6-1bda1b110f62.png)

Is there a way to find out how often treatises or libretti have ungrouped fields? I suspect it's not very often, but they need to be moved back.

**Comment by xhero** [comment]
I can make a script, I imagine they should be in material groups right?

**Comment by jenniferward** [comment]
Thanks. Yes, the field is already present in "Material description." If there's only a handful of affected records I'm happy to move them by hand, if you tell me the IDs.

**Comment by xhero** [comment]
This is the complete list:
```
250013526
250013877
250013878
250013879
250013880
250015893
250015894
450058156
450063143
450118319
450118320
467061300
469169200
650014899
653005627
653006238
1001008735
1001009495
1001030159
1001036241
1001101430
1001116480
201010149
410004220
410004221
450063488
450116109
469000300
469001300
469001400
653005745
1001002977
1001005751
1001005752
1001007109
1001007121
1001187653
1001195770
1001209760```

**Comment by jenniferward** [comment]
Thank you! A script must have caught most of them. They are all good now.
