### ISSUE TITLE
Move data with {{brk}} in 563$a and 031$q

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#1217]
Coming from here: https://github.com/rism-digital/muscat/issues/985

In the fields 563$a and 031$q that contain {{brk}}:

- For 031$q, after each {{brk}} move to a new $q (new subfield only)
- For 563$a, after each {{brk}} move to a new 563$a (new field)

(031$q with brk: 451 records; 563$a with brk: 417 records)

**Comment by jenniferward** [comment]
Fixed in 11.2.1

**Comment by ahankinson** [comment]
Things get better, little by little…
