### ISSUE TITLE
Terms in "Category" (240$g) in the Secondary Literature 

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#1220]
In the Secondary Literature, field Category (240$g) uses the term `Catalog of works`. This replaces the pre-Muscat term `Work catalog`. However there are ca. 840 records that still have the old term. Please change all  240$g `Work catalog` to `Catalog of works`.

**Comment by xhero** [comment]
I fixed the data in -test, I also made the popup menu get the actual values from the data, which means there are many "alien" entries shown now...

**Comment by xhero** [comment]
The data is fixed, followup #1221 will be closed after muscat is updated.
