### ISSUE TITLE
Problems with filtering by "Category" (240$g) in Secondary Literature

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#1221]
On https://muscat.rism.info/admin/publications you can filter by Category, which is the 240$g in the records. 
![image](https://user-images.githubusercontent.com/18663291/155316917-e5dc3523-e991-42e1-afd1-effb2cf8f339.png)

I think there is an indexing problem.
1. If you select "Catalog" [link](https://muscat.rism.info/admin/publications?utf8=%E2%9C%93&q%5B240g_contains%5D=Catalog&commit=Filter&order=src_count_order_desc) you get 2,297 results. This is too many; there should only be ca. 940. I think it is additionally picking up records that _contain_ the word `catalog` in the 240$g, including items that are marked `Thematic catalog` such as the "RepertoriumSchweiz" https://muscat.rism.info/admin/publications/2564 . It should be limited to strictly the records that only contain `Catalog` and nothing else in the 240$g.

Further I think there are some inconsistencies between the data and the selection menu.
1.  Filtering by `Collective catalogue` finds nothing because the spelling is `Collective catalog`. Please change the name of the filter to `Collective catalog`.
2. `Catalog of works` is missing.
3.  `Work catalog` is also incorrect, but I think this can only be changed after https://github.com/rism-digital/muscat/issues/1220 is fixed. (`Work catalog` will need to be deleted.)

**Comment by xhero** [comment]
This should be fixed in ##1220, can you test on -test?

**Comment by xhero** [comment]
This will come in 8.1 (see -test to test it)
