### ISSUE TITLE
Adjust the list of values we support in 593 $a

### ISSUE THREAD

**Issue by lpugin** [rism-digital/muscat#1228]
### Sources

This depends on #1226 because we distinct 593 $a depending on the template.

collection, source, libretto_source, theoretica_source:
* Autograph manuscript
* Possible autograph manuscript
* Partial autograph
* Manuscript copy
* Manuscript copy with autograph annotations
* Additional printed material 

edition, edition_content, libretto_edition, libretto_edition_content, theoretica_edition,  theoretica_edition_content:
* Print

composite:
* Composite

### Holdings

Values also need to be adjusted for holdings

* Print
* Print with autograph annotations
* Print with non-autograph annotations
* Print proof
* Additional manuscript material

**Comment by BaMikusi** [comment]
Just a reminder also here that we should have a clear timeline when and in which steps this change can be undertaken so that the Munich colleagues could also prepare the OPAC for dealing with the revised data structure.

**Comment by jenniferward** [comment]
Small adjustment: Print proofs
