### ISSUE TITLE
Comment notification doesn't work with some unicode chars

### ISSUE THREAD

**Issue by HirschSt** [rism-digital/muscat#1233]
see https://github.com/rism-digital/muscat/blob/00b261d708f020b073a7aeaa49545dd36e8c5b13/app/mailers/comment_notifications.rb#L4

Balázs could not be found:

```ruby
ActiveAdmin::Comment.find(15938).body.scan(/@[A-Za-z0-9_-]*/)
 => ["@Barbara_Wiermann", "@Bal", "@Laurent_Pugin", "@Bernhard_Lutz"] 
```

Proposal for an improved version:

```ruby
ActiveAdmin::Comment.find(15938).body.scan(/@[^ ]*/)
 => ["@Barbara_Wiermann", "@Balázs Mikusi", "@Laurent_Pugin", "@Bernhard_Lutz"] 
```

**Comment by HirschSt** [comment]
Underscore seems to work:

```ruby
"@Andrej_Šuba @Annemarie_Bösch-Niederer check this".scan(/@[^ ]*/)
 => ["@Andrej_Šuba", "@Annemarie_Bösch-Niederer"] 
```

**Comment by xhero** [comment]
Yes I tried it too, I'm not sure why Balázs is with a space in the comment, maybe it was typed out?

**Comment by BaMikusi** [comment]
Can we perhaps take a quick look at all the user names whether there are any others without underscore? Perhaps there are a few special characters occurring in these names that are particularly likely to cause a less?

**Comment by HirschSt** [comment]
I think this is already done with these lines of code

```ruby
require 'json'
text = File.read("./users.json.txt")
data = JSON.parse(text)

data.each do |e|
  id = e["id"]
  r = "@#{id}".scan(/@[^ ]*/)[0].gsub("_", " ")
  if r[1..-1] != id.gsub("_", " ")
    puts id + " " + r
  end
end

```

with 
[users.json.txt](https://github.com/rism-digital/muscat/files/8480338/users.json.txt)

**Comment by xhero** [comment]
I have run my script and you seem to be the only one to have this privilege! (@HirschSt did you find more?)
The reason is not about the accented a in your name, but because the space is not really a space but an unicode space:

Balazs Mikusi
42 61 6c 61 7a 73 **c2 a0** 4d 69 6b 75 73 69 0a

cfr with:

Balazs Mikusi
42 61 6c 61 7a 73 **20** 4d 69 6b 75 73 69 0a

This also explains why it is possible to send the email without the underscore. I think when the name was changed the no-break space was changed to a space and now we see the underscore in the @ mention.

**Comment by HirschSt** [comment]
>  really a space but an unicode space

That was my thought too, but obviously it's difficult to find these chars; I think this exception is well explained now. Nevertheless it's strange...

**Comment by BaMikusi** [comment]
Thanks for looking into all of that. The problem with my name has been solved, I am assuming the rest should now also work fine -- and once we'll have a warning about potentially blocked email notifications, the issue should not cause any further mess of such dimensions.

@xhero: Thanks also for the chart with the 500 aborted email notifications. I shall go through it, take care of the stuff I am able and forward the rest appropriately (unsurprisingly, there are many Polish addresses affected, so Guido will have a good deal to check).
