### ISSUE TITLE
Add sidebars to explain folder functions

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#1240]
People are unsure what folders can and can't do, and I suspect that even the "delete" button makes people nervous. Can we add a sidebar (like what we have for the [template selection](https://muscat.rism.info/admin/sources/select_new_template)) to explain basic functions?

I propose two sidebars. Comments welcome: (edited based on discussion below)

(1) General folder page https://muscat.rism.info/admin/folders 
 - **View**: View the contents of any folder. Folder URLs can also be shared with other Muscat catalogers.
 -  **Edit**: Change the name of your folder.
 -  **Delete**: Delete the folder. (The records in the folder will not be deleted.)

(2) Specific folder page, such as https://muscat.rism.info/admin/folders/843
- **Delete**: Delete the folder. (The records in the folder will not be deleted.)
- **Publish**: Publish the contents of a folder.
-  **Export Folder as MARCXML**: The records in MARCXML format will be sent by email. The limit is XX,XXX records. 
- **Export Folder as CSV**: A CSV file containing basic fields from each record will be sent by email. The limit is XX,XXX records. 
- **Validate items**: The records will undergo Muscat's record validation and a report will be sent by email.

**Comment by BaMikusi** [comment]
A tiny remark: when explaining **Delete** it would seem to me somewhat clearer to put the second sentence in brackets:
"Delete the folder. (The records in the folder are not deleted.)"
Or perhaps even use the future tense? (The records in the folder will not be deleted.)

**Comment by jenniferward** [comment]
Thank you, I have adjusted the explanation above.

I'd be reluctant to make it easy for users to unpublish records because it might have unintended consequences for other catalogers who need the records (prints with other holdings, citing published records in other records) and external users who have already seen the records.
