### ISSUE TITLE
Show comments on Dashboard

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#1254]
I think it would be helpful to show a view of a user's comments on the Muscat Dashboard page. That would encourage people to take care of the comments and keep new ones in view. 

I think the table here https://muscat.rism.info/admin/comments?as=table would be a sufficient view (but you can probably omit the column "Author type" unless it has a function?). 

It should show any of the comments that a user would receive an email for: comments on their records, and comments where they are tagged.

It might also be useful to offer a few sentences about comments: that people can feel free to delete comments that are no longer relevant, and that when appropriate comments can be included as notes (either public in 500 or internal 599 notes), especially in cases that involve extra research, to save the time of future catalogers/readers. Currently there are over 8,000 comments, probably very few of which have lasting value.

**Comment by xhero** [comment]
We did implement this! I think we can close.
