### ISSUE TITLE
MARCXML export crashes in folders

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#1258]
https://muscat.rism.info/admin/folders/860

![image](https://user-images.githubusercontent.com/18663291/170214264-1d560ca7-54a1-4bf7-b5af-78c10d4e3353.png)

But this small folder worked: https://muscat.rism.info/admin/folders/843

**Comment by xhero** [comment]
Fixed with #1256 (was the same error), will be in 8.1.3
