### ISSUE TITLE
"Compare versions" error if no notifications are set up

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#1278]
If a user doesn't have any notifications set up in their user profile, then the link https://muscat.rism.info/admin/compare_versions leads to a "We're sorry..." message (see recent error emails, [ERROR] compare_versions index (ActionView::Template::Error) "undefined method `each_line' for nil:NilClass").

For this case, I think it would be more useful to have a message that explains the situation. The usual "Compare versions" screen should be shown but there should be a message that says something like "There are currently no notifications set up. Edit your user profile to add notifications."

**Comment by xhero** [comment]
Well that it is what it should _already_ say... I will have a look
