### ISSUE TITLE
VIAF-Import (Personal names)

### ISSUE THREAD

**Issue by alexandermarxen** [rism-digital/muscat#1304]
With the update to version 9.0, the import of VIAF data into the Personal names database no longer works as expected.
If there are several fields in the VIAF, only the content of the last field is taken over. In addition, data already existing in Muscat is overwritten.

**Comment by xhero** [comment]
@alexandermarxen I pushed a fix on muscat-test, can you try it and tell me if it works as expected? thanks

**Comment by xhero** [comment]
Fixed in 9.0.1
