### ISSUE TITLE
As of Muscat 9.0, catalogues table still exists

### ISSUE THREAD

**Issue by fjorba** [rism-digital/muscat#1309]
There was an agreement in #975 to rename `catalogues` to `publications`, and it was implemented mostly in 1fb8c04275c304a6a1243fa2347d58951dcfee3c. However, as of 9.0, the old `catalogues` table still exists.

https://github.com/rism-digital/muscat/blob/3228b662392e700848042a3b6fb40291a93e8515/db/schema.rb#L40

I don't know if there are records in the RISM database or it is already empty, but I think that this table, and its related indices, should be removed, because there are old field names (like `description`, that was renamed `title` in `publications`) that appear in the code.

I'm trying to update #1104, but now it has became quite difficult to now what is valid and what belongs to this obsolete table, and so I cannot easily work on it until this issue is resolved.

Thanks.

**Comment by xhero** [comment]
You can safely drop those tables, I will make a patch to fix this (there is no data in there)

**Comment by fjorba** [comment]
Great. I've resolved the conflict in #1104, but it would be great if this and related PR are merged, so I can be sure that I work on an up-to-date codebase.
