### ISSUE TITLE
Add chr to 700$4

### ISSUE THREAD

**Issue by BaMikusi** [rism-digital/muscat#1313]
Please add choreographer (chr) to the list of functions in 700$4.

Note that this function may have existed in Muscat earlier on, and so it could be worthwhile restoring it in the older (Swiss) source records (if it was not merely a theoretical option, but actually in use).

**Comment by xhero** [comment]
@baccia Do you know where we used this?

**Comment by xhero** [comment]
It actwually does not seem to be in CH data al all. These are the records I found in the old versions that had `chr`:

```
400008468
400110528
402002485
402003163
402003173
402004074
402004095
402004096
409000541
409000542
410005195
840010115
840011060
840011085
840011096
840011097
840011100
840011101
840011103
840013358
840014457
840014468
840014539
840014540
840014541
840015423
840015425
840015429
840015432
840015436
840015437
840015440
840015448
840015449
840015451
840015454
840015458
840015460
840015461
840015462
840015463
840015464
840015467
840015468
840015469
840015474
840015478
840015479
840015483
840015486
840015497
840015499
840015500
840015501
840015602
840016115
840016547
840016559
840016576
840016603
840016655
840016658
840016837
840017220
840027154
850602657
850602660
850604834
850605921
850605992
850607425
850615224
850616257
850616462
850616463
850616464
850616465
850616613
850616614
850616615
850616616
850616617
850616618
850616619
850616636
850616637
850616648
850616795
850616796
850616797
850616798
850616799
850616800
850616801
850616802
850616806
850616807
850616808
850616809
850616810
850616811
850616812
850616813
850616814
850616818
850616819
850616820
850616821
850616822
850616823
850616827
850616828
850616829
850616830
850616831
850616843
850616844
850616845
850616990
850616991
850616992
850616993
850617415
850617416
850617417
850617418
850617568
850617569
850617580
850617581
850617582
850617583
850621159
850621160
850621161
850621321
850621322
850621323
850621484
850621485
850621486
850621487
850621488
850622950
850622951
850623102
850623106
850623107
850623264
850623265
850623266
850623267
850623268
850623269
850623270
850623271
850623272
850623273
850623274
850623275
850631576
850650839
850651804
850652895
850655145
850670575
850696066
850698664
850728907
850733757
850733758
850734157
850734207
850734652
850736117
850744043
850744174
850744176
850744280
850744320
850744321
850744322
850744323
850744581
850744582
850745408
850746153
850748071
850748076
850748202
850748426
850748563
850748995
850749906
850750574
850750575
850750576
850750578
850750579
850752305
850752468
850752790
850752993
850752994
850752996
850753585
850754733
850754973
850760113
850760821
850760975
850760976
850760977
850762649
850762657
850767257
850767258
850767544
850767545
850767546
850767547
850767548
850767549
850767550
850767705
850767706
850768684
850769852
850773635
850774502
850774509
850776861
850777617
850778757
850779669
850779756
850780073
850781138
850791344
850792167
850792663
850793445
850794553
850801277
850802936
850803577
850815612
1001112326```

It seems it was changed to `oth` on 2020-08-23 with a script. I can try to figure out a way to restore it...

**Comment by BaMikusi** [comment]
The items at the very beginning of the above list (those with an ID starting with 4) are actually Swiss records, but indeed form a minority. The rest is from the French import (starting with 84) and -- overwhelmingly -- the Italian union catalog (85...), and all of these together would in my opinion form a big enough chunk to make it worthwhile to restore the earlier "chr" indications, if that's possible (sorry about extra hassle). Just to be sure, I picked a few ID's randomly from all three groups, took a closer look at these, and it is clear that in all cases indeed the choreographer was indicated, so going back to those original 700$4 values would certainly be an improvement, now that we officially have the 'chr' option.

**Comment by cgueggi** [comment]
I would support Balázs proposal to restore the "chr" indications. I remember the discussions at the beginning of the Muscat development process and always was always of the opinion to keep as many indicators as possible. If it is too complicated to make the changes by machine, perhaps it can be done manually. After all, there are only about 250 entries.

**Comment by xhero** [comment]
ok I will see how I can restore that from the old versions

**Comment by BaMikusi** [comment]
Thanks. But -- as Cédric hinted -- ca. 250 records is not a vast amount, so if the script is not strightforward, just let me know, and we can do it by hand (once the option will be available in the dropdown, of course).

**Comment by xhero** [comment]
Unfortunately you cannot easily access the data since it is available only on the DB. I extracted a list of all the people in that list of sources that at some point were "chr", I can restore it back. Please just double check the list before!

[oth to chr.xlsx](https://github.com/rism-digital/muscat/files/10446823/oth.to.chr.xlsx)

**Comment by MFalletta** [comment]
I checked some of the french and italian records, for me it's okay.

But please notice, that in 
82: 850616463 "Le Comte, Claude" (40212201) is now "Lecomte, Claude" (40212212) 
185: 850734157 "Benserade, Isaac : de" (41017487) is now "Benserade, Isaac de" (30026052)
187: same as 185

**Comment by BaMikusi** [comment]
Seems fine also to me. In addition to the cases pointed out by @MFalletta, a few more names that have changed in the meantime:

Aumer = Aumer, Jean-Louis
Aumer, Jean Pierre = Aumer, Jean-Louis

Clerico = Clerico, Franceso

Duport, Louis = Duport, Louis-Antoine

Gardel, Maximilien = Gardel, Maximilien-Léopold-Philippe-Joseph

Vestris, Gaetano = Vestris, Gaetano Appolino Balthasar

Note that there might be even more, for I was only checking those cases where this spreadsheet itself had incomplete names or internal conflicts (i.e. two different name variants for the same person).

**Comment by xhero** [comment]
This is the complete list of deleted people, I would need the matching new IDs so I can fix them:

```csv
Duport, Jean Louis          40201094
Fusco, Federico	            40203339
Aumer, Jean Pierre	        40206438
Benserade, Isacco : de	    40209898
Le Comte, Claude	        40212201
Manzotti, Luigi	            41015072
Gioia, Gaetano	            41015178
Bruni,	                    41015220
Dauberval, Jean	            41015382
Angiolini, Gasparo	        41015432
Salomoni, Giuseppe	        41015451
Romanov, Boris Georgević	41017452
Benserade, Isaac : de	    41017487
Fuchs, Aloys	            41017795
Henry, Louis	            41017867
Duport, Louis-Antoine	    41018139
Guerra, Antonio	            41018179
Picque,	                    41019834
Franchi, Paolino	        50033473
Achard	                    50033816
Horschelt, Friedrich	    50036961
Vestris, Gaetano Appolino Balthasar	50038970
Duport, Louis	            50039294
Gardel, Maximilien	        50039389
Noverre, Jean Georges	    50039668
Gallet, Sébastien	         50039671
Aumer	                    50039672
```

**Comment by BaMikusi** [comment]
I guess we should leave this to @alexandermarxen

**Comment by alexandermarxen** [comment]
Voilà:

Duport, Jean Louis          40201094 - 30005109
Fusco, Federico	            40203339 - 40220521
Aumer, Jean Pierre	        40206438 - 30031925
Benserade, Isacco : de	    40209898 - 30026052
Le Comte, Claude	        40212201 - 40212212
Manzotti, Luigi	            41015072 - 30032590
Gioia, Gaetano	            41015178 - 30019303
Bruni,	                    41015220 - 40203220
Dauberval, Jean	            41015382 - 30031926
Angiolini, Gasparo	        41015432 - 30000111
Salomoni, Giuseppe	        41015451 - 30101802
Romanov, Boris Georgević	41017452 - 40217024
Benserade, Isaac : de	    41017487 - 30026052
Fuchs, Aloys	            41017795 - 85015
Henry, Louis	            41017867 - 40201944
Duport, Louis-Antoine	    41018139 - 30098750
Guerra, Antonio	            41018179 - 30106720
Picque,	                    41019834 - 40214311
Franchi, Paolino	        50033473 - 30042139
Achard	                    50033816 - 30043919
Horschelt, Friedrich	    50036961 - 41008842
Vestris, Gaetano Appolino Balthasar	50038970 - 41015397
Duport, Louis	            50039294 - 30098750
Gardel, Maximilien	        50039389 - 30013374
Noverre, Jean Georges	    50039668 - 30047704
Gallet, Sébastien	         50039671 - 30084543
Aumer	                    50039672 - 30031925

**Comment by xhero** [comment]
More madness:

`Salomoni, Giuseppe : 1710-1777 - [30101802]` in the data is this other `Salomoni, Giuseppe : 1730c-1805c - [30101410]`
see
OPS 41015451 should be 30101802 different in source 850623102
OPS 41015451 should be 30101802 different in source 850623264
OPS 41015451 should be 30101802 different in source 850623265
OPS 41015451 should be 30101802 different in source 850623266
OPS 41015451 should be 30101802 different in source 850623267

`Pace, Vincenzo : 17.sc - [30014586]` in the data is this other one `Pace, Vincenzo : 19.sc - [40217440]`
OPS 30014586 3should be 0014586 different in source 850748995

Three sources have no more 700s: 840016547, 850769852 and 850774502. Should I add them back?

**Comment by xhero** [comment]
@alexandermarxen @MFalletta in the meantime I ran the script on -test, can you tell me if it is ok? Once we sort out the stuff in the previous comment I can run it on production.

**Comment by xhero** [comment]
ok, but with my script I'm not changing the ID in the current record, so for example in 850623102 I will make chr 30101410 Salomoni (which is the one in the record). Or I can leave these alone and you guys can fix them.

**Comment by alexandermarxen** [comment]
From my side, it looks very good that way on -test. We will have to fix some things ourselves, since only "oth" was used for old titles anyway.

**Comment by xhero** [comment]
ok, will run it on production as soon as we have 9.1, and leave the Salomonis to you :)
