### ISSUE TITLE
Internationalisation for 593 $a and $b

### ISSUE THREAD

**Issue by xhero** [rism-digital/muscat#1317]
The values in 593 are hardcoded, in fact all the values for subfield_select are hardcoded in the editor configuration and cannot be translated. We should rework this so that the menu can show the i18n version.

**Comment by xhero** [comment]
@MFalletta Could somebody please have a look at the German translation for these terms?

Autograph manuscript
Possible autograph manuscript
Partial autograph
Manuscript copy
Manuscript copy with autograph annotations
Additional printed material
Notated music
Libretto
Treatise
Mixed

**Comment by MFalletta** [comment]
Autograph
Fragliches Autograph
Teilautograph
Abschrift
Abschrift mit autographen Eintragungen
Zusätzliches gedrucktes Material
Notenmaterial
Libretto
Traktat
Gemischte Materialien
