### ISSUE TITLE
When importing printed music sources, all of them goes to edition_content

### ISSUE THREAD

**Issue by fjorba** [rism-digital/muscat#1318]
No matter if the bibliographic level in the music leader is d (Subunit) or m (Monograph/Item), Muscat puts all them as subunit (edition_content).

https://www.loc.gov/marc/bibliographic/bdleader.html

**Comment by xhero** [comment]
It seems we merge them on purpose:

```ruby
    elsif leader.match(/......c[dm].............../)
      rt = RECORD_TYPES[:edition_content]
```

@HirshSt, do you remember why we did it this way? Do we ever import prints? It is OK for me to change the behaivour here.
