### ISSUE TITLE
Secondary literature: unpubl. records can be deleted

### ISSUE THREAD

**Issue by MFalletta** [rism-digital/muscat#1351]
All these records 
https://muscat.rism.info/admin/publications?utf8=%E2%9C%93&q%5Bname_equals%5D=xxxx&commit=Filter&order=src_count_order_asc 
can be deleted. They came from PIKaDo. 
They are included (https://opac.rism.info/search?id=lit30022266&View=rism) and also part of the Open Data offering, but are completely useless.

**Comment by HirschSt** [comment]
done with https://github.com/rism-international/muscat-maintenance/commit/1c4856a9289327219b5995e82defc76ae47902b6
