### ISSUE TITLE
Adjust CSV export

### ISSUE THREAD

**Issue by HirschSt** [rism-digital/muscat#1354]
- [x] 240$m
- [x] 245$a 
- [x] 593$a 
- [x] 593$b

 https://github.com/rism-digital/muscat/blob/2b6804e3858ac93d17f0350a5d6d9e44c97411f4/app/jobs/export_records_job.rb#L235

**Comment by lpugin** [comment]
Would you be able to elaborate? This is not very clear. Thanks

**Comment by MFalletta** [comment]
We need 240$m, 245, 593$a and $b. Thanks

**Comment by HirschSt** [comment]
pr https://github.com/rism-digital/muscat/pull/1358
