### ISSUE TITLE
Creating a new 710 in Source should also update the "place" field in the instiution

### ISSUE THREAD

**Issue by xhero** [rism-digital/muscat#1369]
This is relevant only when creating a new institution from the Source editor. A new field linked to institution.place should be added which works as autocomplete_extra (i.e. life_dates for 100). The difference is that when a new institution is added (clicking the relevant checkbox), the user can insert a value there (pulled from Places), and the new institution will be filled with both name and place. Initial implementation in 1c760e15807f440eff38d545709b78086ca238f9

**Comment by Docudoctor** [comment]
It works in Muscat test.

**Comment by Docudoctor** [comment]
Install the same requirement for 710 in secondary literature.
