### ISSUE TITLE
690-n: required_if-6900: 26 items

### ISSUE THREAD

**Issue by HirschSt** [rism-digital/muscat#1370]
first 10: [[303005016](https://muscat.rism.info/admin/sources/303005016), 303005043, 303005046, 303005132, 303005289, 303005605, 600054845, 659100292, 840016274, [840016710](https://muscat.rism.info/admin/sources/840016710)]

Problem: This is when a catalog of works is cited, but no concrete number is given.
Proposed solution: Fix by hand by the ZR.
Action: I gave the list to editors; status unknown.
April 25 2023: 
- Known issue. 
- This error is not possible with new records but could happen with imported records.
- BM will ask what the status is. Perhaps records can be handed over to national groups to deal with.

**Comment by MFalletta** [comment]
I have worked through the list. Please check again if there are any other cases.

**Comment by jenniferward** [comment]
This error check will stay in the validations. I don't see any development issue here so I will close the ticket.
