### ISSUE TITLE
Links in 856 lack $z

### ISSUE THREAD

**Issue by HirschSt** [rism-digital/muscat#1371]
Ca. 7,600 records with links in 856$u lack a note in $z. The number might be higher because the validation is not running in holdings.

- [x] @HirschSt will implement https://github.com/rism-international/tasks/issues/745  
- [x] @xhero will add this validation to holdings

This is from the [Health Report](https://docs.google.com/document/d/1lKOruB8mBN2_LY07AfqmO2_PqgbfxKecv8zER69F9sg/edit#heading=h.7k0o12g1p5ag) error "856-z: required_if-856u."

**Comment by HirschSt** [comment]
Probably also http://nbn-resolving.org or http://mdz-nbn-resolving.org should be checked

**Comment by HirschSt** [comment]
done with https://github.com/rism-international/muscat-maintenance/commit/fc920ded3ca04a88e4e94e989f5e3704b1c53842

**Comment by jenniferward** [comment]
Validation is running on holdings.
