### ISSUE TITLE
Links in 856$u without $x

### ISSUE THREAD

**Issue by HirschSt** [rism-digital/muscat#1372]
Ca. 460 records have a link in 856 but no link type. The number might be higher because the validation is not running in holdings. 

- [x] @Docudoctor will supply the correct link type because they are all from the same library and all have the same data in $z. [See table here](https://docs.google.com/spreadsheets/d/1f3rOFsj61zOA8cR1zwbcPBfslO8PyaoTUV2hWm4EnHE/edit#gid=0).
- [x] @HirschSt will add the link type to those records. (done with https://github.com/rism-international/muscat-maintenance/commit/bfe806ce99678105bddc073c571643cb038f58aa)
- [x] @xhero will add validation to holdings.

This is from the [Health Report](https://docs.google.com/document/d/1lKOruB8mBN2_LY07AfqmO2_PqgbfxKecv8zER69F9sg/edit#heading=h.gbeqefz47uto) error "856-x: required_if-856u."

**Comment by Docudoctor** [comment]
The correct link type is "Other" I have added to the table provided by Jennifer. 
Best, Guido

**Comment by jenniferward** [comment]
No instances of the error in Sources. Validation is now in holdings, and the remaining errors are being dealt with by the holding library.
