### ISSUE TITLE
700$a missing $4

### ISSUE THREAD

**Issue by HirschSt** [rism-digital/muscat#1374]
Ca. 125 records have a 700$a but no $4. The number may be higher because the validation is not running on holdings.
The ZR is correcting the records.

@xhero will add holdings to validation.

This is from the [Health Report](https://docs.google.com/document/d/1lKOruB8mBN2_LY07AfqmO2_PqgbfxKecv8zER69F9sg/edit#heading=h.lfcy3ml7zxk) error "700-4: required_if-7000."

**Comment by xhero** [comment]
Validation on holdings added, coming the next release!
