### ISSUE TITLE
Fix corrupted 240 $k and 240 $o

### ISSUE THREAD

**Issue by lpugin** [rism-digital/muscat#1376]
It looks that some records ended up with corrupted values when exported from Kallisto:
https://gist.github.com/lpugin/2df32cb36a900c2736ad9a0358e588e1

In some cases, it seems that the title was split based on a `.` and the content after the `.` was moved to $k and $o
Some pattern are:
* Content in $k needs to be move back to $a (https://muscat.rism.info/admin/sources/989002148)
* Content in $k needs to be split between $k and $o (https://muscat.rism.info/admin/sources/107108) (`Excerpts. Arr`)
* Content in $k needs to be moved to $o (https://muscat.rism.info/admin/sources/104442 (`Arr`)
* Content in $o needs to be moved to $k (https://muscat.rism.info/admin/sources/408004951) (`Excerpt`)
* Content in $o needs to be normalized (https://muscat.rism.info/admin/sources/410004505) (`Arr` and not `arr` or `Arrangement`)

**Comment by HirschSt** [comment]
Sorry for asking again: can I use the tables in the gist to filter all the related records?

**Comment by lpugin** [comment]
Yes. These are all the corrupted values

**Comment by HirschSt** [comment]
Done with https://github.com/rism-international/muscat-maintenance/commit/02b81f3005d6953bbaa1564ae0e01923668f1b44

Result can be checked at https://github.com/rism-international/muscat-maintenance/blob/master/log/20230426-fix-arr.log and https://github.com/rism-international/muscat-maintenance/blob/master/20230428-fix-sub_rest.csv

**Comment by HirschSt** [comment]
done by maintenance
