### ISSUE TITLE
Remove 041$e in Sources

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#1387]
041$e in Source is called "Language of libretto," but this often leads to inconsistency, confusion, and errors. Instead, 041$a should be used for the language of the source, regardless of the type of source.

The data in 041$e should deleted if $e is identical to $a. Example: https://muscat.rism.info/admin/sources/1001091316 

If they are different, $e should be moved to $a. Example: https://muscat.rism.info/admin/sources/1001042745

**Comment by HirschSt** [comment]
Yes, of course, I can prepare a script

**Comment by HirschSt** [comment]
@jenniferward please check with https://github.com/rism-international/muscat-maintenance/blob/master/log/20230824_drop_041e.log

**Comment by xhero** [comment]
@jenniferward At the end $e will be removed right?

**Comment by jenniferward** [comment]
@HirschSt If $a and $e are different, $e needs to move to $a to be an additional $a. As far as I can tell, $e was deleted.
In https://beta.rism.info/admin/sources/1001035799/edit, `lat` was completely deleted. It needs to join $a to be `$apor$alat`
https://beta.rism.info/admin/sources/1001165578/edit should be `$apol$ager`

Duplicated $a and $e were correctly deleted, as in: https://beta.rism.info/admin/sources/1001242002/edit

@xhero Yes sorry, please remove $e at the end!

@Docudoctor Please check next round with table at https://docs.google.com/spreadsheets/d/1fwg1Cs0u0plUaatGzr4qi4D5NhaLmkFP5mrPRpndS2w/edit#gid=0

**Comment by HirschSt** [comment]
> @HirschSt If $a and $e are different, $e needs to move to $a to be an additional $a. As far as I can tell, $e was deleted.
> In https://beta.rism.info/admin/sources/1001035799/edit, lat was completely deleted. It needs to join $a to be $apor$alat
> https://beta.rism.info/admin/sources/1001165578/edit should be $apol$ager

Yes, sorry. Corrected with the new version

**Comment by jenniferward** [comment]
$e should now be gone from the sources, so please remove $e from the interface.
