### ISSUE TITLE
There are too few filters to select from the list of folders

### ISSUE THREAD

**Issue by fjorba** [rism-digital/muscat#1389]
Currently there is a single folder filter to select from the folders list, by name. Moreover, the title ("Any name contains") does not correspond to the real behavior, that is, the full name.

When there are many folders, this selection is too limiting. The current "contains" should really do a substring select, not a full name, and other filters, like by owner and folder type, would be very welcome.

**Comment by xhero** [comment]
@jenniferward I think there is a wish list here too right?

**Comment by jenniferward** [comment]
We have a Folders label (which I just added here) which is essentially the wish list. I agree this would be useful!
