### ISSUE TITLE
Does it make sense creating folders of users?

### ISSUE THREAD

**Issue by fjorba** [rism-digital/muscat#1391]
Currently it is possible to create a folder for Muscat users, selecting a few from the list and creating a folder, like any other element.

Beware, though, because after creating one, the folder list crashes with this error (**Don't do it in production!**):

<pre>
Mysql2::Error: Unknown column 'users.wf_stage' in 'where clause': SELECT COUNT(*) FROM `folder_items` INNER JOIN users ON folder_items.item_id = users.id WHERE `folder_items`.`folder_id` = 16 AND (users.wf_stage = 0)

Extracted source (around line #31): 

       relation = folder_type.pluralize.underscore.downcase
     #if folder_type == "Source"     return false if folder_items.joins("INNER JOIN #{relation} ON folder_items.item_id = #{relation}.id").where("#{relation}.wf_stage = 0").count > 0
     #else
     #  content.pluck(:wf_stage).each do \|e\|
     #    return false if e == "inprogress"
--
relation = folder_type.pluralize.underscore.downcase
    #if folder_type == "Source"
    return false if folder_items.joins("INNER JOIN #{relation} ON folder_items.item_id = #{relation}.id").where("#{relation}.wf_stage = 0").count > 0
    #else
    #  content.pluck(:wf_stage).each do |e| 
    #    return false if e == "inprogress"
</pre>

Rails.root: /home/ifmuc_muscat/muscat/muscat-9.2
app/models/folder.rb:31:in `is_published?'

The quick fix would be:

<pre>
$ bin/rails c
Loading development environment (Rails 5.2.8.1)
irb(main):001:0> Folder.last.destroy
</pre>

With a list of users there are a couple of actions can be done:

* Removing them
* Creating a folder (or adding them to an existing folder)

If creating folders does not make sense, I volunteer to provide a patch. However, I'd like to know if you really remove list of users this way. If not, I also volunteer to fix it (I have a draft).

**Comment by xhero** [comment]
I think we never used this and we can remove it. @lpugin @jenniferward what to you think>

**Comment by xhero** [comment]
I think it was there, never really worked, we never really noticed because only a handful of people can admin users. But in extreme theory, yes you can make a folder with users 😆
