### ISSUE TITLE
Should the number of occurrences in Secondary Literature appear in authority record list?

### ISSUE THREAD

**Issue by fjorba** [rism-digital/muscat#1392]
Currently, in the list view for People, Institution, or any other authority records, there is a column with the number of sources where this entry occurs. However, it says nothing about how often it occurs in secondary literature records.

I suspect that this information would be as useful for the main Muscat instance for RISM as it is for us at UAB.  However, before providing a patch, I'd like to know if you are interested in it.

A different issue is that there is not much space left with the current design of those authorities list as created with the ActiveAdmin gem.  I think that it can optimized, but that will be another issue that I'll open soon.

So, to make it clear: I can provide a patch for creating those counters (it is basically a copy&paste of the sources one, so no black magic here), and it requires a Solr reindex. The fact that those counters appear now or later on the list would be a different patch, maybe related with the optimization of the current list.

**Comment by xhero** [comment]
Yes! This is a long standing wish and I never came around to fixing it. One problem is indeed that we don't have much column space left, we could think of a way to condense the counters? @jenniferward ?

**Comment by fjorba** [comment]
> One problem is indeed that we don't have much column space left, we could think of a way to condense the counters? @jenniferward ?

Please see  #1405 with some ideas about optimizing column space.

**Comment by xhero** [comment]
@jenniferward When you have a moment can you look at this? Showing the count for all the linked items is something I would like to have since it is quite confusing if an auth file links to things other than a source.

**Comment by xhero** [comment]
Yes I think I added some of those in some auth files, but we could expand it to all for consistency
