### ISSUE TITLE
Records missing 260$c

### ISSUE THREAD

**Issue by HirschSt** [rism-digital/muscat#1401]
260$c is required if anything in the 260 block is filled out (like a city name). Of the ca. 12,000 errors, ca. 10,000 are from the ICCU import.

@xhero will exclude the ICCU records from this validation (see [spreadsheet](https://docs.google.com/spreadsheets/d/1kB5w5rhpqRxirTeKwPMpB0lDXcE_zhRd1XkipGlF1gI/edit#gid=1332990952) tab "260 c required"), records that start with 850

This is from the [Health Report](https://docs.google.com/document/d/1lKOruB8mBN2_LY07AfqmO2_PqgbfxKecv8zER69F9sg/edit) error "260-c: required."

**Comment by xhero** [comment]
Added exclusions https://github.com/rism-digital/validation-exclusions/commit/bfcbb002a9033220e7ab1da7cb2c10a72afb06fe

**Comment by jenniferward** [comment]
Exclusions added. The remaining 26 will be done by hand.
