### ISSUE TITLE
300$a missing in imported records

### ISSUE THREAD

**Issue by HirschSt** [rism-digital/muscat#1402]
There are ca. 39,000 records that lack 300$a. Most are from data imports, where the records were created following different guidelines, and this information is not available. Such imported records should be excluded from the validations.

The biggest chunk is from the ICCU import (IDs start with 850, 30,000 records) and the ÖNB import (8,900 records, IDs start with 600)

@xhero will make the exclusion for the records that start with 850 and 600.

This is from the [Health Report](https://docs.google.com/document/d/1lKOruB8mBN2_LY07AfqmO2_PqgbfxKecv8zER69F9sg/edit#heading=h.71jw8h5dbedt) error "300-a: required."

**Comment by xhero** [comment]
Added in https://github.com/rism-digital/validation-exclusions/commit/1e5242a402db5ee9a5c0f29c4ac099d83df3d283
