### ISSUE TITLE
031$a but no $b or $c

### ISSUE THREAD

**Issue by HirschSt** [rism-digital/muscat#1404]
An 031 $b and/or $c is missing from some imported ICCU records. The number is less than 100 and will be edited by hand.

This is part of the [Health Report](https://docs.google.com/document/d/1lKOruB8mBN2_LY07AfqmO2_PqgbfxKecv8zER69F9sg/edit) error "031-b: required_if-031a" and "031-c: required_if-031a."

**Comment by xhero** [comment]
I think for this kind of work we are doing for validation it is more useful to make tickets with only the bullet points of what we have to do (ex. change configuration or make a script) more than mirroring here what we have in our internal notes document.

**Comment by lpugin** [comment]
I agree with @xhero : duplicating the content from the GoogleDoc is confusing

**Comment by HirschSt** [comment]
Ok with me, can you edit it accordingly?
