### ISSUE TITLE
Muscat Ruby 3.x and Rails upgrade path?

### ISSUE THREAD

**Issue by fjorba** [rism-digital/muscat#1407]
I was trying to install Muscat 9.3 in our shiny new servers, with Debian 12 (Bookworm), that is in late beta.  I have been beaten by the fact that it is not possible to build Ruby 2.7.x in a newer Linux server, that ships with openssl 3.0.  I'm using ruby-install (https://github.com/postmodern/ruby-install) myself, but I have seen similar reports reports with rvm and other installers (ex: https://github.com/rbenv/ruby-build/discussions/1940).  Upstream Ruby developers have decided not to support this combination (https://bugs.ruby-lang.org/issues/18658#note-18).

Myself, I have the workaround to install Debian 11 (Bullseye) meanwhile, that ships with openssl 1.1, and I will be able to build ruby 2.7, needed for Muscat.  Moreover, Ruby developers urge to migrate to 3.x, as 2.7.8 will be the last 2.7 Ruby release, with no upgrades even for security fixes (https://www.ruby-lang.org/en/news/2023/03/30/ruby-2-7-8-released/).

Anyway, I decided to try to install Muscat 9.3 with Ruby 3.2.2, to see what happens, and it fails very early:

~/muscat/muscat-9.3$ bundle install
Bundler 2.4.10 is running, but your lockfile was generated with 2.2.29. Installing Bundler 2.2.29 and restarting using that version.
Fetching gem metadata from https://rubygems.org/.
Fetching bundler 2.2.29
Installing bundler 2.2.29
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
Fetching gem metadata from https://rubygems.org/........
Fetching https://github.com/rism-ch/sunspot
Fetching https://github.com/rism-ch/progress_bar
Fetching https://github.com/rism-ch/rails3-jquery-autocomplete
Fetching https://github.com/rism-ch/blacklight
Fetching https://github.com/rism-ch/blacklight_range_limit
Fetching https://github.com/rism-ch/delayed_job
Fetching https://github.com/rism-ch/progress_job
Fetching https://github.com/jrochkind/cql-ruby
deprecation-1.0.0 requires ruby version ~> 2.1, which is incompatible with the current version, ruby 3.2.2p53
~/muscat/muscat-9.3$ 

So, may I kindly ask which are your plans to upgrade Ruby and Rails to newer versions?  I'm willing to help if I can.  Thanks.

**Comment by xhero** [comment]
Muscat currently will not work with rails 3, you can checkout the rails 6 branch and that should work, but it is still quite WIP. I hope to finally completely migrate muscat to rails 7 by this fall, the main blocker is Blacklight 5 which does not run with rails 6. Our plan is to split away the bl stuff, since we don't use it anymore and it prevents upgrading Muscat.

**Comment by xhero** [comment]
The branch is actually called develop-no-blacklight ;)

**Comment by fjorba** [comment]
Yes, I have seen this one, but I wasn't aware that was based on Rails 6.

**Comment by xhero** [comment]
Yes maybe we can rename it to something more meaningful. I brought it up to date with develop

**Comment by fjorba** [comment]
That's a big step! Congratulations!!
