### ISSUE TITLE
Allow editors to export Muscat records in Muscat MARC format

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#1408]
It would be convenient if Editors had access to MARC records in the real Muscat MARC format, unedited from any export manipulation Muscat does, including the 599$a internal notes. This could be added to the Export functions in Folders.

**Comment by jenniferward** [comment]
Oh I forgot about that! Yes, I think they are sort of related. In the Folders view (like https://muscat.rism.info/admin/folders/1001) we have the options "Export Folder as MARCXML" and "Export Folder as CSV." I would like "Export Folder as internal MARCXML." This would need to preserve the 599$a internal notes, which -- as I notice just now -- even the .xml view (https://muscat.rism.info/admin/sources/600100001.xml) of full records does not include (with good reason). Only editors would need this, not the general Muscat user.

**Comment by xhero** [comment]
> 

This is a bit different, it is for exporting the raw format we save in the database, sometimes it is useful when we have to do clean ups of data.
