### ISSUE TITLE
Table indexes are not compatible between institutions, holdings, and sources

### ISSUE THREAD

**Issue by ahankinson** [rism-digital/muscat#1410]
The `siglum` column on institutions was recently changed to a different collation. However, the `lib_siglum` column on the `sources` and `holdings` tables do not share the same definition. This means that the index on the siglum columns cannot be used when joining since the index values are no longer compatible. The following error is shown when trying to do this sort of lookup:

```
Cannot use ref access on index 'index_holdings_on_lib_siglum' due to type or collation conversion on field 'lib_siglum'
```

To fix this the `lib_siglum` columns on `holdings` and `sources` should be altered to use the same collation as the `institutions` table.

At the same time it's probably also good to change the `VARCHAR` length to match, since the holdings and sources tables have `VARCHAR(255)` but the Institutions table has `VARCHAR(32)`. 

The following SQL statements will fix this:

```
alter table sources modify lib_siglum VARCHAR(32) collate utf8mb4_0900_as_cs null;
alter table holdings modify lib_siglum VARCHAR(32) collate utf8mb4_0900_as_cs null;
```

I'm marking this as fairly urgent, since the lack of usable indexes on the siglum columns slows the RISM Online indexing down to a crawl.

**Comment by xhero** [comment]
I think we can have a look at this today, we can make a micro-release of Muscat to fix it asap.

**Comment by fjorba** [comment]
I'm aware that it may not be your priority, but `utf8mb4_0900_as_cs` does not exist in MariaDB. I have been comenting this migration since appeared:

https://mariadb.com/kb/en/incompatibilities-and-feature-differences-between-mariadb-10-4-and-mysql-8-/

You may be interested in looking for an alternative if you'd like Muscat be a little more compatible with other databases.

**Comment by ahankinson** [comment]
What would you suggest for both accent and case sensitivity?
