### ISSUE TITLE
Change font in Muscat 

### ISSUE THREAD

**Issue by BaMikusi** [rism-digital/muscat#1416]
In order to please our larger circle of users, we spent much time to select a font for our website that allows for the display and easy differentiation of every possible character. But now thinking of it again, the same Noto Sans would actually be quite nice to have also in Muscat, to make the life of catalogers and editors easier as well.

**Comment by xhero** [comment]
<img width="1246" alt="Schermata 2023-08-22 alle 11 23 14" src="https://github.com/rism-digital/muscat/assets/1691778/1cc23297-1c4d-4999-8e87-ec89260e0a7c">

@baccia @cgueggi @ahankinson @lpugin 

This is how Muscat looks in Noto Sans, I actually like it! I will push it on -test and we can decide it to keep it or fine tune it.

**Comment by cgueggi** [comment]
Looks nice to me, too! I think people will quickly get used to it.

**Comment by ahankinson** [comment]
Does it look OK with the ambiguous sigla? Particularly "l" (lower L) and "I" (upper i) ?

**Comment by xhero** [comment]
Which one is it?

**Comment by ahankinson** [comment]
Pick any Italian one and you should see very quickly. :)

**Comment by xhero** [comment]
<img width="1246" alt="Schermata 2023-08-22 alle 13 58 46" src="https://github.com/rism-digital/muscat/assets/1691778/4ea96fc7-55c4-47e6-b5ba-48937a221b0c">

ok here is how it looks when I _actually_ change the font in the inputs!

**Comment by BaMikusi** [comment]
Looks good to me too. And since this change is not fixing a problem that catalogers would intensely have been complaining about for ages, from my side it can wait until the next major release -- even though I don't actually think such postponement is necessary, if we explain to the users that this is not simply an aesthetic change but a quite substantial practical improvement for all.

**Comment by Docudoctor** [comment]
Yes!
Please try a nice siglum from Linz: A-LIabil
