### ISSUE TITLE
Comment notification doesn't work if case isn't exact 

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#1425]
We had an instance (now deleted, but reproduced here: https://muscat-test.rism.info/admin/sources/1001250544 ) where a user @'ed someone but the notification did not get sent. The mention looked like this:
`@martina_falletta` 
The notification only gets sent if the case matches: 
`@Martina_Falletta` 

I suspect the mention was typed in by hand. The reason for that _might_ be because of the bug in #939 and perhaps the list of names was not readily visible so they resorted to typing it out.

See also #1233 for an earlier issue with notifications.

**Comment by xhero** [comment]
The match is case sensistive, we can make it case insensitive I think

To do with: #1432
