### ISSUE TITLE
Help box for Digital objects

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#1430]
Can we add a help box to the right-hand column for Digital objects, like we have for Folders? I think just a couple sentences are needed (feedback welcome):

*****
Help
The **Digital objects** database collects all of the images (typically watermarks, handwriting samples, or bindings) and MEI incipits that are attached to records in Muscat. Digital objects can be attached to sources, people, and institutions. A digital object can be attached to multiple records. 

New digital objects can only be added from the editing mode of a source, person, or institution. From the record, click on on **Attach a new image** and follow the upload instructions.

You can edit or delete digital objects that you have uploaded. 

From any digital object, you will find links to attach it to a source, person, or institution. 

*****

I noticed that the "Create" button does not do anything: "Images or Incipits can only by attached from objects". Should it be removed from both the main https://muscat.rism.info/admin/digital_objects page as well as each object page?

**Comment by xhero** [comment]
I'm going to add this to Muscat, I need a volunteer for the translations ;)

**Comment by xhero** [comment]
Danke!
