### ISSUE TITLE
Leaders missing for TED, TEC and LEC

### ISSUE THREAD

**Issue by xhero** [rism-digital/muscat#1436]
These three templates are just ignored in the code, a proposition for a proper leader should be made

**Comment by xhero** [comment]
A proposed list (from me):

```collection: dc
edition: cc
composite: pc
source: dm or dd if child
edition_content: cd (cm will never happen!)
libretto_source: tm
libretto_edition:ac
theoretica_source: pm

we miss

libretto_edition_content: ad
theoretica_edition_content: pd

and we need to fix:

libretto_edition: ac if collection, am if single
theoretica_edition: pc if collection, pm if single```

Note that Muscat has a bug for edition and libretto edition: instead of properly setting those as collection/single item it counts 773 (!) in the childs (!!) for the _child_ leader. This has to be moved to to the toplevel editions, see if 774s exists, and adapt the leader of those as per table.

**Comment by jenniferward** [comment]
I agree with the above regarding what is missing and what needs to be fixed (highlighted in yellow in the document). I would add that EDT should also differentiate between collection and single.

I went a bit further in the document, after having looked at the [MARC description](https://www.loc.gov/marc/bibliographic/bdleader.html) in more detail and comparing that with our templates. In case we want to look at it further.

**Comment by lpugin** [comment]
Looks good to me
