### ISSUE TITLE
Display of free-text fields in Edit mode

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#1437]
Could you make the following fields in Muscat into growtext so that all the text in them is displayed on the screen in Edit mode? Many of our longer fields are this way (245, 500) but there are a few textareas that get cut off in the display while in edit mode.
 
Sources:
- 541$a
- 300 $b
- 592 $a
- 518 $a (I don't understand what the key is doing in this field)
- 597 $a

Holdings:
- 852 $q 
- 541$a
- 300 $b
- 592 $a
- 518 $a (Same question regarding the key)

Institutions:
- 680 $a

People:
- 678 $a
- 680 $a

**Comment by xhero** [comment]
I implemented all of these with the exception of 518 in Sources and Holdings, which uses an autocomplete and cannot grow. Do we need the autocomplete here?

**Comment by jenniferward** [comment]
Thanks, looks good! 

Please get rid of autocomplete in 518 and add the growfields.
