### ISSUE TITLE
Add "Patron" [pat] to 700 $4 and 710 $4

### ISSUE THREAD

**Issue by BaMikusi** [rism-digital/muscat#1444]
(The German equivalent is "Auftraggeber".)

**Comment by xhero** [comment]
We already have a translation in DE:
```yml
patron: Mäzen/Auftraggeber```

is it ok or should I just have Auftraggeber?

**Comment by BaMikusi** [comment]
For the content, both German equivalents are of course fine, but would that mean that in the dropdown list catalogers would come to see this double version with the slash in the middle? (For I see no similar case in the rest of the list, and would therefore tend to avoid creating an outlayer example if possible.)

**Comment by xhero** [comment]
Fixed name

**Comment by jenniferward** [comment]
Just a side note: At the time of the ÖNB import we didn't have `pat` so I changed it the `oth` in 2 cases. Now I changed those to `pat`. (It was not in F-Pn or ICCU as far as I can tell.) Maybe someone can check the Swiss data import.
