### ISSUE TITLE
Change editorial info in GND editor

### ISSUE THREAD

**Issue by afaschon** [rism-digital/muscat#1453]
In field 040 of the GND editor the default editorial ISIL under $9r: should be DE-633 (for RISM Germany). @xhero

**Comment by BaMikusi** [comment]
Thanks for reporting that; indeed, DE-633 should be the correct identifier.

(That a wrong number had been in circulation in several places -- among others at VIAF -- was discovered about two years ago, and I ran a 'campaign' last year to have this corrected everywhere, but the implementation has taken quite a bit of time.)
