### ISSUE TITLE
Track duplication IDs

### ISSUE THREAD

**Issue by ahankinson** [rism-digital/muscat#1462]
An idea, from a conversation on Slack with @jenniferward: 

Since record duplication is pretty common among our users, it would be handy, even from the developer side, to know both a) whether a record originated from a duplication action and b) what record it was duplicated from. 

Since we don't necessarily need this in the MARC data, I wonder if adding a NULLable `origin_id` (or some other name) to the database would work? Then when the record is saved, the value from the `existing_title` query parameter could be stored there. 

I had a quick look and I couldn't see anywhere obvious that this was already being stored. 

This would apply to all types where the user can create a new record by duplicating an existing one. I think this is sources, works, publications?

**Comment by lpugin** [comment]
It makes sense to track it. I am not fully convince we need this in the database, though. I would suggest storing this in a local read-only marc field.

**Comment by xhero** [comment]
I was going to say the same, why not a read-only marc field? From the Muscat side it is a bit cleaner

**Comment by ahankinson** [comment]
Well, I thought about that. It's not really part of the "record" though... Two books that originate from duplicate IDs can be completely different in content, so storing the ID in the MARC record for an otherwise unrelated source seems to be an internal Muscat thing, rather than intrinsic to the bibliographic record.

I see it more like one of the `wf_` fields (published, unpublished, etc.), which we don't store in the MARC record.

**Comment by lpugin** [comment]
It is essentially a data creation process. They do not really have a relation any more once the record has been created and modified. I agree this is not directly part of the record, but I see it more like an internal notes. So something like the `599` but we probably need another one to make it read-only so cataloguers will not remove it.

**Comment by lpugin** [comment]
I think we can make it visible in the record preview. Wouldn't that be even simpler?

**Comment by xhero** [comment]
I'm not sure you can take an initial snapshot, duplication is done in the fronted and not in the backed, and the version will not be saved until you save from the editor. The duplicate record acts as a new record without an ID.

**Comment by xhero** [comment]
<img width="1187" alt="Screenshot 2023-12-19 alle 15 31 52" src="https://github.com/rism-digital/muscat/assets/1691778/4185cfa3-1dba-449d-a505-66a2c8e95472">

Something like this? We propose a new dedicated field 981, with the origin ID and the date. Any preference on how to format the date?

**Comment by ahankinson** [comment]
Maybe "Original" instead of "Origin"?

**Comment by xhero** [comment]
Yes yes give me time to make the labels :)

**Comment by HirschSt** [comment]
>  Any preference on how to format the date?

Probably only date without time

**Comment by ahankinson** [comment]
Time would be a good thing to include since duplication events may happen multiple times in one day.

**Comment by jenniferward** [comment]
Catalogers shouldn't be allowed to delete this field because it would defeat the purpose:
![image](https://github.com/rism-digital/muscat/assets/18663291/f2552f0b-056d-4039-bec3-84af2be12b13)

**Comment by jenniferward** [comment]
Upon saving, the Date appears above Original record:
![image](https://github.com/rism-digital/muscat/assets/18663291/58a9a843-44bb-4bc7-a68b-9a8efeda20e0)

Can it be preserved in the same order the the Edit mode has? ID first, then date

**Comment by xhero** [comment]
Oops I forgot to make it non deletable. I will see for the show page, it is one of those easy things that are not super easy...

**Comment by xhero** [comment]
<img width="396" alt="Screenshot 2023-12-20 alle 14 20 09" src="https://github.com/rism-digital/muscat/assets/1691778/a126b76e-7dde-4513-b1ea-79418da47668">

What about this?

**Comment by jenniferward** [comment]
That's great, and gives context to the date as well.
Did we say unlinked though for the ID?

**Comment by xhero** [comment]
yeah but since I was making a partial anyways...

**Comment by ahankinson** [comment]
Work records can also be duplicated. It would probably make sense to do the same thing for those too?

**Comment by jenniferward** [comment]
So can Secondary Literature, while we're at it.

**Comment by xhero** [comment]
981 everywhere?

**Comment by jenniferward** [comment]
We can't duplicate the other authorities (not sure if we need to).

**Comment by xhero** [comment]
No I mean, should we use the same tag 918 in Works and Institutions ;)

**Comment by ahankinson** [comment]
Yes. (`s/Institutions/Secondary Literature/g`?)

**Comment by xhero** [comment]
oops yes :)
