### ISSUE TITLE
Headings for new Muscat data views

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#1476]
I am testing out https://github.com/rism-digital/muscat/pull/1469 on muscat-test and I am wondering if adding a heading to the MARC view page would be helpful and/or possible. A cataloger might accidently click on one of the MARC views and be confronted with an unfamiliar format and wonder what happened and how to get back: 
https://muscat-test.rism.info/admin/sources/1001274019?view=MARC21
![image](https://github.com/rism-digital/muscat/assets/18663291/f576bda1-456d-4ea4-bfd5-02280107e1d6)

Maybe something like `MARC21 view` would be enough to clue them in? Or highlight it on the sidebar? I note that the XML view opens in a different page, but there I think a cataloger's instinct would be to click "back" on the browser to return to normal. 

Big thanks to @fjorba for adding the MARC views!

**Comment by fjorba** [comment]
Thanks, @jenniferward. Do I understand well that you are proposing several solutions, not necessarily incompatible: 

* First, add "view" in each of the three views (Default view, MARC21 view and MARCXML view)
* Second, add a header, at least for the MARC21 view at top of the MARC21 record.
* Hightlight the "active" view in the sidebar.

Is that right?

Personally, I don't know how to highlight the active view in sidebar. Maybe @xhero would, but this is beyond my Rails abilities. So, for the time being, I have to discard this solution.

Regarding adding "view" for each of them, that would mean to make this message "translatable" (sp?), create the standard string and update each language file.  I'll try to do it in the next few days.

Regarding MARCXML, it is considered a "raw", exchange, format (to be saved and imported as such in another system), and thus it is not "decorated" within a normal html page like the others, that are for human consumption.  Our current Invenio system behavies similarly:

* https://ddd.uab.cat/record/188089
* https://ddd.uab.cat/record/188089/export/hm
* https://ddd.uab.cat/record/188089/export/xm

**Comment by jenniferward** [comment]
Thanks for your thoughts! I was thinking a header like this:
![image](https://github.com/rism-digital/muscat/assets/18663291/6a866fc2-6a9c-4d1e-a291-6c74ad4c784b)

but you're right, that's not standard.

Maybe just changing the phrases in the side bar would be the simplest and enough to rescue people if they get lost?
![image](https://github.com/rism-digital/muscat/assets/18663291/b0925809-5d39-4bef-ae04-555188993522)

**Comment by xhero** [comment]
Done with bb598259affb9883c4b3765a7226edf7e9146ed1

**Comment by fjorba** [comment]
Thanks, @xhero, I was going to do it today, but I arrived late...
