### ISSUE TITLE
Holdings missing from MARC view

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#1477]
Re https://github.com/rism-digital/muscat/pull/1469: The MARC21 view when looking at printed items does not display the holdings information:

1 library: https://muscat-test.rism.info/admin/sources/990071549?view=MARC21 
![image](https://github.com/rism-digital/muscat/assets/18663291/77f8a111-2cf0-435d-9a57-e3744377d2c1)

Many libraries: https://muscat-test.rism.info/admin/sources/990046739

The MARCXML view includes the holdings: https://muscat-test.rism.info/admin/sources/990046739.xml

In a way, I see an advantage to excluding holdings: the core bibliographic information can be swiftly copied over elsewhere. But there also might be situations where showing all the fields would be expected.

**Comment by xhero** [comment]
The problem here is that Marc and MarcXML show two different marcs from muscat: text marc is the "internal" muscat marc, while marcxml is the "external" one we use to export data.

**Comment by xhero** [comment]
The MARC21 should be the same as marcxml, so we will export to_external
