### ISSUE TITLE
Wrong message when removing records from folder 

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#1478]
I created this folder https://muscat-test.rism.info/admin/folders/1172 as a cataloger, where I have editing rights for Germany. I am looking at this record, which is in that folder: https://muscat-test.rism.info/admin/sources/1001274025 
I tried to add it to someone else's folder, The Cazzati Folder 

![image](https://github.com/rism-digital/muscat/assets/18663291/7701c2df-91db-44d6-9576-e4ebd9f1e5f1)

but I got this message: You are not authorized to remove items from The Cazzati Folder 1103
![image](https://github.com/rism-digital/muscat/assets/18663291/d8490f49-fcaf-4cdb-8a75-0a2535679a5b)

So it recognizes that I did not create that folder, but I think it is showing me the wrong message? 
When I go to an Austrian source like https://muscat-test.rism.info/admin/sources/1001121681 and try to delete it from its folder, I get this message as expected: "You are not authorized to remove items from A-Sm_Hof 443."

(Again, huge thanks to @fjorba for adding the add/remove functionality!)

**Comment by xhero** [comment]
Done f5a63079

**Comment by fjorba** [comment]
Thanks again.
