### ISSUE TITLE
"View" in Secondary literature

### ISSUE THREAD

**Issue by MFalletta** [rism-digital/muscat#1482]
The option "View" in Secondary literature doesn't work (today). 

Starting for example from https://muscat.rism.info/admin/publications/30026872 I want to switch to another referring literature but I get an error: 
Dashboard: The resource you are trying to access does not exist or has been deleted. (Work 30025271) 

But the record exists: https://muscat.rism.info/admin/publications/30025271

**Comment by HirschSt** [comment]
the controller directs to works instead of publications (copy&paste)

https://github.com/rism-digital/muscat/blob/49ef204ac6f637d3b6b983d24cd3896429b0f91c/app/admin/publication.rb#L261

**Comment by xhero** [comment]
oups!
