### ISSUE TITLE
Visibility of duplicated/copied ID's in Muscat

### ISSUE THREAD

**Issue by LynnMegan** [rism-digital/muscat#1495]
I don’t think it is very practical how the copied items are included when searching for an ID that was duplicated from another one. 
E.g. lets say I want to change 1001283964 and search for it; the “duplicates” also show..  its okey when its only 3 results but what if  I have a collection with 50 entries where I just copied every single one of the subs (e.g. when its just 50 songs or so).. I think it will get a bit messy when I want to search for just one of the single ID's.
![Bildschirmfoto 2024-02-15 um 11 02 01](https://github.com/rism-digital/rism-online-issues/assets/89964087/c2ccf48b-cd5a-4f41-89b6-905b6de1222f)

**Comment by ahankinson** [comment]
Not that it directly fixes this issue, but if you know the source ID you want, you can just edit the URL and go straight to the record: https://muscat.rism.info/admin/sources/1001283964

**Comment by xhero** [comment]
I think we can add a filter specific for IDs, I know some users want also to see the collections or the child records. Would this make sense?

**Comment by jenniferward** [comment]
I agree with Lynn. The 981 is just an admin field that is part of the record origin and shouldn't have anything to do with searching. Can 981 be excluded from the search?

**Comment by jenniferward** [comment]
@LynnMegan There's a new field for RISM ID now. Can you try it, keeping your above comments in mind?

**Comment by jenniferward** [comment]
Seems to be ok!
