### ISSUE TITLE
Bundler error with Gemfile

### ISSUE THREAD

**Issue by HirschSt** [rism-digital/muscat#1496]
Installing a fresh Muscat 10 it seems that references like https://github.com/rism-digital/muscat/blob/c9b70d9d9a48f05c2f5f3b6d5ca0844458ab16a7/Gemfile#L58 probably are out of order (going to nowhere). 

Also the rather obvious switch to rism-digital changes nothing. 

Are all the git-links in Gemfile up-to-date?

**Comment by ahankinson** [comment]
This package is still available on the RISM CH GitHub page. We kept both accounts open. 

https://github.com/rism-ch/progress_bar

Are you experiencing any problems with installation?

**Comment by HirschSt** [comment]
... BTW I'm using ruby 3.3.0

**Comment by ahankinson** [comment]
If you're using ruby 3.3.0 then this:

`... /home/dev/.rvm/gems/ruby-2.7.6/cache/bundler ... `

would seem to indicate that there's a problem with your RVM environment, and maybe you're not using the correct version with bundler? I'm not a ruby expert, though.

**Comment by HirschSt** [comment]
Yes, probably there are some old environment variables...

**Comment by HirschSt** [comment]
Solved by a complete reinstall of rvm
