### ISSUE TITLE
People: Names of owners

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#1497]
The names of the record owners in Personal Names here https://muscat.rism.info/admin/people starts alphabetical, then seems to be chronological (when user added). Can the names be arranged alphabetically by last name, as in Sources? https://muscat.rism.info/admin/sources

**Comment by BaMikusi** [comment]
On that note: in Sources the names are indeed ordered by last name, but it often takes a lot of scrolling to get to the one I need. In similar dropdowns one can as a rule find things faster by hitting the first letter of the term searched -- but here this trick is unfortunately not getting me to the *last* names starting with that letter, only to the next *first* name. Not a big deal, of course, but perhaps there is a simple way to improve this?

**Comment by jenniferward** [comment]
Fixed thanks to the type-in popup menu!
