### ISSUE TITLE
People: English terms for 042

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#1499]
In the Personal Names, 042, the two choices, `individualized` and `not individualized` are not idiomatic for this context in English. They should be `differentiated` and `undifferentiated`. 
We should change the drop-down menu, but I think these terms are in the data as well, for example: https://muscat.rism.info/admin/people/30004985?view=MARC21
`=042 ##$anot individualized`
So the data should be changed as well.

**Comment by ahankinson** [comment]
Can we also delete the Anonymous person while we're at it? :-D
