### ISSUE TITLE
Control fields in Muscat

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#1505]
The control fields 000, 001, 003, 005, and 008 behave differently across Muscat in Editing mode:

  | Sources | Literature | People | Institutions | Works
-- | -- | -- | -- | -- | -- 
000 | – | freetext | freetext | freetext | freetext 
001 | grayed out | grayed out | grayed out | grayed out | grayed out 
003 | -- | grayed out | grayed out | grayed out | – 
005  | – | grayed out | grayed out | grayed out | – 
008 | – | – | – | grayed out | – 

In addition, some can be deleted (even by catalogers) and some cannot.

Can these fields be consistent, either present everywhere, or hidden everywhere, or present but gray everywhere? For editors and catalogers, I don't think they need to be visible at all, but maybe there are program reasons to have them. 

Most don't even display the actual data:
https://muscat.rism.info/admin/institutions/51004835/edit
![image](https://github.com/rism-digital/muscat/assets/18663291/1e8a9fc7-12d2-4e2b-9237-5381b4cf3f1c)
`=001 51004835
=003 DE-633
=005 20240209185700.0`

**Comment by xhero** [comment]
Implement as in sources
