### ISSUE TITLE
Secondary literature: Error when linking in 780/785

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#1510]
In Secondary literature, 780 and 785 are used to link journals that have undergone name changes. 780 is for the earlier title, 785 is for the later title.
Journals don't typically have short titles (210$a), though there are some old records with 210.
We have discovered that there are some duplicate short titles and are correcting them. There is a validation in place for 210$a so it is no longer possible to have duplicate 210$a.

But when I click on https://muscat-test.rism.info/admin/publications/30026129 I get an error message when trying to view it (We're sorry, but something went wrong.). Editing is fine.  In 30026129, the 780 is supposed to link to  https://muscat.rism.info/admin/publications/30026121. 30026121 has the short title `Proceedingsofthe` which is one of our duplicates. If you select it and save it, you get an error (We're sorry, but something went wrong.)

I'm getting the same error when trying to link to anything in 780/785 and save, with or without 210$a.

When I view a record like https://muscat-test.rism.info/admin/publications/30023482 with 780 and 785, the URL mouseover preview doesn't look like it is catching the ID:
`https://muscat-test.rism.info/admin/publications/Denkm%C3%A4ler%20der%20Tonkunst%20in%20Bayern%20(=DTB,%20Alte%20Folge)`
![image](https://github.com/rism-digital/muscat/assets/18663291/bba5eb21-dbe0-43e1-ac2d-7b810aab5eb8)

**Comment by HirschSt** [comment]
Maybe: https://github.com/rism-digital/muscat/blob/ade290fdd0aa2e72224312b6141119749691c8b0/app/views/marc_show/_show_related_publication.html.erb#L4 (not checking for existing t_tag), see also https://muscat.rism.info/admin/publications/30026977.xml
