### ISSUE TITLE
Works: Migrate 7XX block to 5XX

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#1522]
The Works template has 3 7XX fields:
- 700 Additional personal name
- 710 Additional institution
- 747 Liturgical festival

In MARC the 7XX fields are meant to point to authorized forms in external authority files, which is not relevant for RISM. To show how a person or institution is related to our work, 5xx fields should be used instead.

The 7XX fields should be migrated as follows:
700-->500
710-->510
747-->547

These 3 fields, plus 530 (Related work), should all be together in the Relations block. 

See, for example, the Brandenburg Concerto in VIAF (DNB) which has the dedicatee in 500, which would correspond to our current 700. 
http://viaf.org/viaf/186724054 
Or a librettist for an opera:  http://viaf.org/viaf/181031673

**Comment by jenniferward** [comment]
Would it make sense to move 530 to the "Relations" section? A "Related work" is not strictly one of the main entry fields.

**Comment by xhero** [comment]
Yes for me! Moving is easy ;)
