### ISSUE TITLE
Works: Add new names directly from Works interface

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#1523]
In the Works interface, it is not possible to add new names from field 700 (aka 500; https://github.com/rism-digital/muscat/issues/1522). We get the warning "Item cannot create a new element, please select one from the list." 
We need the checkbox "Confirm the insertion of a new value" to add new names.

**Comment by xhero** [comment]
This was actually fixed when I did a review of all linked fields for another ticket
