### ISSUE TITLE
Works: Add new functions in 700 and 710

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#1524]
The list of functions in 700$4 and 710$4 (aka 500 and 510; see https://github.com/rism-digital/muscat/issues/1522) is short. We don't need to use the entire list of functions as in Sources, but a few more would be useful.

For 700$4, please add:
- arr
- trl
- aut
- ctb
- ccp
- pat

For 710$4, please add:
- asn
- pat

**Comment by jenniferward** [comment]
`arr` should verbalize as `Arranger` in 500$a instead of `Arrangement`
![image](https://github.com/rism-digital/muscat/assets/18663291/6ab2b351-91fe-4e28-97c6-5521aa91fab6)

**Comment by xhero** [comment]
oops will fix!
