### ISSUE TITLE
Page navigation across tabs

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#1527]
When you have multiple Muscat tabs open, the page navigation 

![auswahl_055](https://user-images.githubusercontent.com/18663291/36024985-c2b3628a-0d91-11e8-8a64-3d309ea93c54.png) 
might disappear after clicking forward/backward or editing.

Generally, if I am navigating through results and editing along the way, I would like to be able to move forward or backward. But the navigation disappears and I loose my place.

See https://github.com/rism-digital/muscat/issues/597

**Comment by xhero** [comment]
Multi tab muscat is now on -develop!
