### ISSUE TITLE
Marc Import collates accented chars

### ISSUE THREAD

**Issue by xhero** [rism-digital/muscat#153]
For example: adding a 240 $a "Légende" the import find_by will match "Legende" so the auth file is not created. Collations should be disabled?

**Comment by lpugin** [comment]
Yes, I should be disabled

**Comment by xhero** [comment]
We can disable totally collations setting it to uft8_bin, so only binary matching will be made. But this means we completely loose any special character matching. Alternatively (maybe?) we can set the COLLATE option only when we do import of marc records to force binary matching in that case and leave uft8_general_ci for the rest.

**Comment by lpugin** [comment]
I would change it only for import, if this is possible.

**Comment by xhero** [comment]
Moving to 3.6, this will include a bigger fix for autocompletes

**Comment by lpugin** [comment]
@xhero what is the status of this? Didn't we give up?

**Comment by xhero** [comment]
We did give up, but I would like to have the ticket to track the problem
