### ISSUE TITLE
Additional tag for indicating atypical (obsolete, dubious) works

### ISSUE THREAD

**Issue by lpugin** [rism-digital/muscat#1532]
We need a dedicated tag for marking some specific works that are listed in some work catalogues but where we should give an indication they should not be used as reference. Example:
* Graupner 1118/12 which is now 1118/12a and 1118/12b, where we need 1118/12 to be marked as "obsolete"
* Purcell "dubious" D* works
* Others?

Some ideas:
* 130 $g (Miscellaneous information), but not prominent enough IMO
* 075 (Entity type), but not really correct ($2 would be missing?)

Others?

**Comment by ahankinson** [comment]
`024 $z` with a set of fixed options for `$q` (e.g., `obsolete`, `dubious`)

**Comment by lpugin** [comment]
For me that would be saying the the identifier is obsolete, not the resource itself.

**Comment by lpugin** [comment]
Or are you saying that both `1118/12a` and `1118/12b` would have a `024` with `1118/20` ? That would work, but only for obsolete resources that have been replace by another one (or more)

**Comment by ahankinson** [comment]
Would you do that on the work itself, or on the catalogue entry? If it's on the work, then wouldn't you add it to the 690, since (I think?) that's where the number/page and catalogue reference are. 

So add a second 690 and mark one as "obsolete" or "dubious"?

**Comment by lpugin** [comment]
Yes, I think I would keep a work record with a 690 for 1118/12 and mark it as obsolete. Then, in that record, pointing to 1118/12a and to 1118/12b with the link explaining that it has been replace by them.

**Comment by lpugin** [comment]
(We cannot assume that an obsolete work has been replaced by something else)

**Comment by xhero** [comment]
Did we decide a tag for this? I can leave it out for now

**Comment by lpugin** [comment]
Another possibility would be to have a database field and export it to 05 in the leader https://www.loc.gov/marc/authority/adleader.html. For Muscat and RISM Online, that would work well. Maybe less if we export the data, but we could event skip these or add a note field if that is eventually the case.

**Comment by xhero** [comment]
I need a couple things to complete this:

* How should it be called?
* The two values will be obsolete and dubious right?
* I also need a value for when it's neither, (except for "none" which cannot be used for weird rails reasons)

**Comment by lpugin** [comment]
> * How should it be called?

Label? Category?

> * The two values will be obsolete and dubious right?

Yes, for now.

> * I also need a value for when it's neither, (except for "none" which cannot be used for weird rails reasons)

standard? blank? void? (I assume we are not going to see it. We can show the label only when it is given

**Comment by xhero** [comment]
I did an initial implementation which you can find on -test. I went with "label" and the select has an empty value for "normal" records

**Comment by lpugin** [comment]
Looks good. You also need to add it to the show partial

**Comment by ahankinson** [comment]
Something more descriptive might be helpful. Authenticity? Attribution Certainty?

**Comment by xhero** [comment]
Form me both are good, @jenniferward do you have a preference?

**Comment by xhero** [comment]
![Screenshot 2024-03-20 alle 11 52 10](https://github.com/rism-digital/muscat/assets/1691778/76e94b89-dd1d-47a0-8c3d-d9576d875294)

NRM, OBS and DUB?

**Comment by lpugin** [comment]
Looks good. I would actually show nothing for normal records. I think this should work.

**Comment by BaMikusi** [comment]
Is "dubious" the right word in this context? Why it's essentially (and even etymologically) the same as "doubtful," I have the impression that it is the latter word that is more in use in work lists.

And would "spurious" not be a third category to consider here?

**Comment by lpugin** [comment]
I am equally fine with `doubtful`

Regarding `spurious`, no decision has been made. However, having thought about it more since we talked about it, it seems to be that these would be a perfect use-case for work nodes.

**Comment by xhero** [comment]
Should I change it to doubtful?

**Comment by lpugin** [comment]
Thanks, it is much better to use the common terminology.

**Comment by BaMikusi** [comment]
As to the *spurious* stuff, I am not against any meaningful options (whereby I won't be at our meeting tomorrow and next week to discuss how a work node variant would exactly look like).

**Comment by jenniferward** [comment]
The field Application History Note, 688, might be useful as a user-friendly way to call attention to the status of the record, to complement the code in 008. 
https://www.loc.gov/marc/authority/ad688.html
For example: Graupner 1118/12 was split into 1118/12a and 1118/12b.

**Comment by lpugin** [comment]
I would suggest `Validity`
