### ISSUE TITLE
Personal names - Field 856$y

### ISSUE THREAD

**Issue by alexandermarxen** [rism-digital/muscat#1548]
The data from field 856$z has not yet been migrated to 856$y. As field 856$z no longer exists, it disappears when records are edited and saved.
Example:
https://muscat.rism.info/admin/people/11035

**Comment by alexandermarxen** [comment]
856$y is not yet displayed in the view.
https://muscat.rism.info/admin/people/69314

**Comment by xhero** [comment]
oops, that should still be 'y'

**Comment by xhero** [comment]
Fixed, the view unfortunately can only be fixed when we solve the issue with 856.

**Comment by alexandermarxen** [comment]
What I have only just realised is that the validation for the field refers to 856$z instead of 856$y. Could this be adjusted?

**Comment by alexandermarxen** [comment]
After the update to Muscat 11, the contents in field 856$z are missing.

**Comment by alexandermarxen** [comment]
Example: https://muscat.rism.info/admin/people/20001075

**Comment by xhero** [comment]
Fixed!

**Comment by alexandermarxen** [comment]
Oh, that was quick! Thank you very much!
Was 856$u also copied in 680$a? I have seen this in some records and am actually sure that I have not entered this twice?

**Comment by xhero** [comment]
AFAIK I didn't touch 680, maybe it was done in another script?

**Comment by ahankinson** [comment]
@alexandermarxen you can check the modification history to see when the value was copied.

**Comment by alexandermarxen** [comment]
Oh yes, I really must have forgotten to remove the double entry. Sorry and thanks again for the quick hotfix!
