### ISSUE TITLE
740$a should not consider capitalization at the beginning

### ISSUE THREAD

**Issue by cgueggi** [rism-digital/muscat#156]
f.e.: "miserere" brings no hit. Only "Miserere" opens the drop down list with all the texts beginning with "Miserere".

**Comment by xhero** [comment]
We are using the terms.prefix component, which is handy but is case sensitive. We could move to the suggerster: https://cwiki.apache.org/confluence/display/solr/Suggester
http://stackoverflow.com/questions/32324735/how-to-implement-auto-suggest-in-solr

Which is made for ACs

**Comment by xhero** [comment]
The Suggester is available only in solr 4.10, we use 4.2. Solr will be updated after the release

**Comment by xhero** [comment]
We have solr 5 now! Finally we can fix this

**Comment by ahankinson** [comment]
@xhero I think 740 has been removed, so this probably can be closed?
