### ISSUE TITLE
Reindexing issue when works are duplicated

### ISSUE THREAD

**Issue by lpugin** [rism-digital/muscat#1570]
When a work is duplicated and the catalogue (690) field is only changed in `$n`, searching the work is not finding it if the search is limited to that catalogue.

**Comment by lpugin** [comment]
This is actually not only when duplicating but also when creating a new work. So the real issue is in work creation. Saving a second time fixes it (I think)

**Comment by xhero** [comment]
@lpugin Can you test this in -test? Hopefully it is fixed

**Comment by lpugin** [comment]
Looks good! Thanks
