### ISSUE TITLE
Show place as well as name for related institutions

### ISSUE THREAD

**Issue by ahankinson** [rism-digital/muscat#1577]
Many institutions have generic names, like "Cathedral" or "Duomo" that are only differentiated by the place. However, in the "Related institution" display on Muscat, the place name is not included, meaning you only get a generic name. Even for those that do not have a generic name, like "Yale University", including the place name is still helpful.

Can the place (110 $c) be included in the display along with the name to help differentiate them? 

Here are some examples:

https://muscat.rism.info/admin/publications/30028993  -- Would be "Universität, Innsbruck" in "Additional Institution"

https://muscat.rism.info/admin/sources/467411500 -- Would  be "Hofoper, Berlin" in "Additional Institution"

https://muscat.rism.info/admin/sources/990010871 -- Would be "Duomo, Archivio Capitolare, Udine" under the holding record for I-UD. Also, "Yale University, Music Library, New Haven, CT" under the holding for US-NH.

**Comment by xhero** [comment]
@jenniferward in [publications/30028993](https://muscat.rism.info/admin/publications/30028993) what is "U" as function? Also "pbl" does not look right...

**Comment by xhero** [comment]
<img width="497" alt="Screenshot 2024-05-16 alle 12 21 24" src="https://github.com/rism-digital/muscat/assets/1691778/fc7057ef-d024-494f-950c-08040fc0287f">
@ahankinson Something like this? I just added $c

**Comment by jenniferward** [comment]
Those are old values from Kallisto or earlier. They might be typos or they might have had a meaning. I don't think the drop-down menus in Publications have ever been cleaned up.

**Comment by ahankinson** [comment]
That's perfect, thanks!
