### ISSUE TITLE
Muscat MARC format when exporting

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#1587]
The file of the Muscat MARC format when exporting a folder (example: https://muscat.rism.info/admin/folders/1267) turns up as one giant record for me. When I use MarcEdit then I need an empty line before each `=001` so not

![image](https://github.com/rism-digital/muscat/assets/18663291/f7a93639-2fa9-4638-a05d-11d25740865c)

but
![image](https://github.com/rism-digital/muscat/assets/18663291/79a5e63b-ec1d-4113-a156-3368e00121e7)

I can add the empty lines, but I am pretty sure they were present in the last release (see also https://github.com/rism-digital/muscat/issues/1509 where the export files changed) and if this is an easy fix then I would appreciate saving the step.

In 2023 I downloaded a folder as Muscat MARC and it starts in MARCXML format, which I then can process without a problem.
![image](https://github.com/rism-digital/muscat/assets/18663291/62e3c699-be8f-4db6-8b1b-b9a1ba964261)

There's no XML any more in the Muscat MARC format.
![image](https://github.com/rism-digital/muscat/assets/18663291/ce7a862c-11e6-4267-b33a-9728d4e23dd1)

**Comment by xhero** [comment]
I think I can add the empty lines, but I'm confused on the XML part: you selected a _marc_ export and you got xml?
