### ISSUE TITLE
Search filter for owners leads to 502 Bad Gateway-Error

### ISSUE THREAD

**Issue by alexandermarxen** [rism-digital/muscat#1604]
Currently, the search for owners results in an error message:
https://muscat.rism.info/admin/people?utf8=%E2%9C%93&q%5Bwf_owner_with_integer%5D=wf_owner%3A1&flexdatalist-q%5Bwf_owner_with_integer%5D=Admin&commit=Filtern&order=id_desc

**Comment by alexandermarxen** [comment]
It obviously affects all search queries:
https://muscat.rism.info/admin/people?utf8=%E2%9C%93&q%5Bfull_name_or_400a_contains%5D=Bhartini&commit=Filtern&order=id_desc
https://muscat.rism.info/admin/people?utf8=%E2%9C%93&q%5B550a_with_integer%5D=550a%3AAbbot&commit=Filtern&order=id_desc

**Comment by xhero** [comment]
Do you have more details or a screenshot? All those queries work when I open them

**Comment by alexandermarxen** [comment]
![502-Bad-Gateway](https://github.com/rism-digital/muscat/assets/42838336/98611dd5-4a90-4e4a-a258-41459d81282e)
Maybe I should clear my cache?

**Comment by xhero** [comment]
Yes please could you try? From here I can access it without problems

**Comment by alexandermarxen** [comment]
Logging out, clearing the cache and logging in again worked. Thank you!

**Comment by ahankinson** [comment]
I wonder if something from the new authentication fixes now triggers a 502 in certain circumstances...

**Comment by xhero** [comment]
But we did not change anything in the authentication process, just a warning when you log out

**Comment by HirschSt** [comment]
Probably something remaining from the DNS change?

**Comment by ahankinson** [comment]
This seems to be fixed now? Re-open if I'm wrong...
