### ISSUE TITLE
Add Bolivia to Nationality (043) in People

### ISSUE THREAD

**Issue by alexandermarxen** [rism-digital/muscat#1611]
Please add Bolivia (XD-BO) to Nationality (043) in People.
see: https://muscat.rism.info/admin/people/51019690

Thanks

**Comment by alexandermarxen** [comment]
PS: Is there an easier and/or better solution for adding codes? Or could all codes be added to the lists?

**Comment by xhero** [comment]
Unfortunately at the moment no... you can do a PR if you want to add them yourself :)
