### ISSUE TITLE
"Select" disappears when searching for people through Sources or Secondary Lit

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#1613]
If I am in Sources or Secondary Lit and search for a name (100 or 700) using the magnifying glass, navigation disappears and/or I can no longer click "Select".

From Sources:
![image](https://github.com/user-attachments/assets/9c18a16c-420b-40ba-874d-a919dcdc21fe)

![image](https://github.com/user-attachments/assets/cacfed3a-0279-4883-881f-8792bac18112)
Navigation is fine, but the `Libraries` counter disappears in some records:
![image](https://github.com/user-attachments/assets/78e574a8-453c-4808-a068-b23a143f9264)

If I click to get back to the list, I no longer have `Select`.
![image](https://github.com/user-attachments/assets/2100383c-b757-4d14-9f2c-d297b7eee923)

From Secondary Lit:
![image](https://github.com/user-attachments/assets/4f3ce0a2-2200-4bfc-a9d1-1eef69ad513c)
 
Clicking on the 1st name:
![image](https://github.com/user-attachments/assets/525034d7-5485-4c24-9be2-d9294068111c)

Navigation is gone: can't page forwards or backwards.
![image](https://github.com/user-attachments/assets/d4311ed6-cadc-4de5-a143-2a15f2bb21ac)

**Comment by fjorba** [comment]
Yes, we also have this behavior, but I thought that it was caused by some of my local patches.  Now I see that it isn't.

**Comment by xhero** [comment]
Yup, it's a bug unfortunately :( I will try to fix it asap
