### ISSUE TITLE
Sigla in holdings should include name of city

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#1615]
Can the city of the holding library be included in the Exemplar display? It it hard to tell at a glance what cities are meant.
Example:
https://muscat.rism.info/admin/sources/990066380
with I-PCd and  I-PS
Especially since both have `Archivio capitolare` in their institution name.
I think this would be a convenience similar to https://github.com/rism-digital/muscat/issues/1577.

**Comment by xhero** [comment]
I refactored the holding title to be more legible
