### ISSUE TITLE
593: preventing "Additional printed material" alone or in Group 1

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#1622]
Currently it is possible to create a Collection or Manuscript record where the only 593$a is `Additional printed material`.
Similarly, it is possible to create a Collection or Manuscript record where 593$a `Additional printed material` is the first group.
Neither one of these practices reflects the logic behind this option in 593$a, so it should be prevented.

**Comment by xhero** [comment]
How often does this happen? Maybe I can trap this with validation, but since groups can be moved I'm not sure I can actually remove the values from the menu.

**Comment by xhero** [comment]
![Screenshot 2024-09-24 alle 11 43 08](https://github.com/user-attachments/assets/3d30b0db-8e18-4cfb-955e-df4c4972f038)
Something like this?

**Comment by xhero** [comment]
I'm closing this, since with the validation users will not be able to save "wrong" records anymore in the next release, and this problem happens in around 31 records which will be logged in the weekly report.
