### ISSUE TITLE
[GND editor] 548 and subfields, order and names

### ISSUE THREAD

**Issue by afaschon** [rism-digital/muscat#1641]
**Order and names of 548 and subfields; default values**
- 548 – "Zeitbeziehung"
- $a – "Zeit"
- $4 – "Beziehungscode"
- $i – "Verweisungsphrase"
- $w – "Kontrollunterfeld"
- $9 – "Bemerkungen"

**In addition**
- 548 is facultative
- in case it is used, $a and $4 are obligatory
- $w has default value "r"

**Comment by afaschon** [comment]
Addition: $9 should be named "$9 v"

**Comment by xhero** [comment]
The value of $9 should be "v"? or the label?

**Comment by afaschon** [comment]
The label!

**Comment by xhero** [comment]
![Screenshot 2024-10-14 alle 15 35 36](https://github.com/user-attachments/assets/58ac68df-38a2-4a8a-9c7b-1ef959eff264)
Like this?

**Comment by afaschon** [comment]
As far as I understand, it should look like this:
Bemerkungen ($9 v)
