### ISSUE TITLE
Solr ThemaxQuery-1.0-SNAPSHOT.jar no longer part of Muscat?

### ISSUE THREAD

**Issue by fjorba** [rism-digital/muscat#1648]
As I was setting up our first Muscat for production in a new server, Solr complained about a missing plugin:

```
$ curl "http://localhost:8983/solr/admin/cores?action=STATUS&core=traces-muscat"
{
  "responseHeader":{
    "status":0,
    "QTime":0},
  "initFailures":{"traces-muscat":"org.apache.solr.common.SolrException:org.apache.solr.common.SolrException: Could not load conf for core traces-muscat: Can't load schema /var/solr/data/traces-mus
cat/conf/schema.xml: Plugin init failure for [schema.xml] fieldType \"text_pae\": Plugin init failure for [schema.xml] analyzer/filter: Error loading class 'org.rismch.PAEFilterFactory'"},
  "status":{
    "traces-muscat":{}}}
```
It turns out that this plugin is found in ThemaxQuery-1.0-SNAPSHOT.jar, that used to be part of Muscat distribution until 10.0, and duplicated in several places.  The last release where it was found was 9.4.2:

```
$ ls -l $(find muscat-9.4.2 -name ThemaxQuery-1.0-SNAPSHOT.jar) 
-rw-r--r-- 1 ddd users 1644139 Oct 31  2023 muscat-9.4.2/solr-configuration/jar-8.8-linux/ThemaxQuery-1.0-SNAPSHOT.jar
-rw-r--r-- 1 ddd users  442465 Oct 31  2023 muscat-9.4.2/solr-configuration/jar-8.8-mac/ThemaxQuery-1.0-SNAPSHOT.jar
-rw-r--r-- 1 ddd users  433214 Oct 31  2023 muscat-9.4.2/solr/jar-mac/ThemaxQuery-1.0-SNAPSHOT.jar
-rw-r--r-- 1 ddd users 1644139 Oct 31  2023 muscat-9.4.2/solr/jar-solr8-linux/ThemaxQuery-1.0-SNAPSHOT.jar
-rw-r--r-- 1 ddd users  433214 Oct 31  2023 muscat-9.4.2/solr/jar/ThemaxQuery-1.0-SNAPSHOT.jar
```

Fortunately, this file still works, and when copied in /opt/solr/contrib/themax/ Solr starts without errors.  I copied the version with filesize of 1644139 bytes, because that's what the `2- INSTALL.rdoc` still recomends.

So, my question is double: is any reason why this jar is no longer part of Muscat? And, is the `2- INSTALL.rdoc` documentation is still valid about the Solr version and jar file?  (I remember to test a solr-9.2.1 but I cannot recall which problems did I have). Thanks.

**Comment by xhero** [comment]
Ouch weird, I thought I removed all references to the PAE plugin as it is obsoleted, I will have a look

**Comment by fjorba** [comment]
Sorry, false alarm, my fault. I copied an old version of schema.xml to the new server.  There is no reference to text_pae in the current version of Muscat, and so ThemaxQuery-1.0-SNAPSHOT.jar is no longer needed
