### ISSUE TITLE
Add 744$a to Composite volumes too

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#1650]
Collections have a 774$a which consists of normalized data from the child's 100$a and 240$a:
https://muscat.rism.info/admin/sources/1001313794?view=MARC21
`=774 18$aSchlabitz, A. - Ottilien-Polka - pf$w1001313795`
`=774 18$aSchlabitz, A. - Elsbeth-Tyrolienne - pf$w1001313797`

Can Composite volumes include an $a with similar data as well? Currently only the $w is included. 
https://muscat.rism.info/admin/sources/1001301112?view=MARC21
`=774 18$w242975$4holding`
`=774 18$w550281787`
`=774 18$w51071932$4holding`

**Comment by xhero** [comment]
Something like this?

```=774  18$a990062099: Sterkel, Johann Franz Xaver - 6 Lieder - V, pf; StWV 51$w242975$4holding
=774  18$aMozart, Wolfgang Amadeus - Nozze di Figaro - Excerpts; V (2), orch; KV 492/16$w550281787
=774  18$a1001301281: Dalayrac, Nicolas-Marie - Nina - Excerpts; S, pf$w51071932$4holding
=774  18$aDalayrac, Nicolas-Marie - Raoul sire de Créqui - Excerpts; Arr; V, pf$w550281788
=774  18$aRighini, Vincenzo - Se cerca se dice - S, orch$w550281790
=774  18$aSalieri, Antonio - Deh si piacevoli - S, pf$w550281791
=774  18$a990062167: Sterkel, Johann Franz Xaver - Juliens Feyer - S, Coro, pf; op. 14; StWV```

**Comment by jenniferward** [comment]
This is helpful! Then we get the IDs of all the records, too.

**Comment by lpugin** [comment]
I think the title should go in `$t`

**Comment by xhero** [comment]
Should we also change 773? We add $a with the title there too, see #1161

**Comment by jenniferward** [comment]
I suggested $a to align with current practice, but instead of a normalized form it could be:
`=774 18$aSchlabitz, A.$tOttilien-Polka - pf$w1001313795`
so $a and $t
but that leaves the scoring floating out there. $m?
Looking at: https://www.loc.gov/marc/bibliographic/bd760787.html

**Comment by xhero** [comment]
What should I do here? We can discuss this Wed, but then the change will go in 11.3...

**Comment by lpugin** [comment]
I think just just `$t` (and no $m`) would be fine. I think that would mean you can get it from `std_title`?

**Comment by xhero** [comment]
Right now what is in $a in 773/774 come from this:

```ruby
  def name
    "#{composer} - #{std_title}"
  end
```

I can split it and put int in $a and $t or just $t

**Comment by lpugin** [comment]
`composer` in `$a` and `std_title` in `$t`

**Comment by BaMikusi** [comment]
PS: As implemented in the end, this should have received the `MARC config change` tag (and accordingly it unfortunately breaks the display in the RISM Catalog).

**Comment by lpugin** [comment]
Yes, you are right. Sorry for overlooking it.
