### ISSUE TITLE
[GND editor] Field 930 not displaying actual work title

### ISSUE THREAD

**Issue by afaschon** [rism-digital/muscat#1662]
When a source record is part of a collection, field 930, "Werktitel", shows the _collection’s_ title instead of the _actual work’s_ title:
![werktitel_1](https://github.com/user-attachments/assets/af28b6c3-960b-47ac-866f-83bdd4d399f2)

Instead, field 930 should be displaying the _work’s title_ as in 100 $p.
![werktitel_2](https://github.com/user-attachments/assets/19a3e71e-b97a-4eec-b6c7-7bfd9a05c4cd)

In this example case, "Werktitel" should show "Pater noster qui es in coelis", not "Cantiones sacrae de festis praecipuis totius anni".

**Comment by afaschon** [comment]
From a technical point of view, it is correct, yes. From a user’s point of view it is misleading because the work node is not about a collection any work may or may not be part of but about the individual work (there are also many works that are not part of any collection—their title is displayed correctly).

One problem is that in the GND’s standards, the collection title is a mandatory part of the work title. But we don’t want the collection title to be displayed before the individual work’s title because that is counter-intuitive from most researching points of view.

Is there, in your eyes, any solution to this?

**Comment by afaschon** [comment]
Thank you! Desiree and I are discussing the problem and we’ll get back to you asap.

**Comment by xhero** [comment]
Would merging the two fields, when importing the WorkNode, into $t work? In this case you would get: `$tCantionae sacrae: Pater noster` or formatted in a similar way, and you would see this in the Source when the WN is linked.

**Comment by lpugin** [comment]
@afaschon please add links to the Muscat and GND records you are referring to in your next comments. Thanks!
