### ISSUE TITLE
Inventory Item tune-up

### ISSUE THREAD

**Issue by xhero** [rism-digital/muscat#1671]
* "Inventareintrag" is better than "Inventarartikel."
* The German labels for shades are missing in 240$r.
* 594$c translation is "Anzahl," not "Nummer."
* 598 is not necessary.
* [852 has no label configuration]

**Comment by xhero** [comment]
@MFalletta @baccia  Number has always been Nummer since the last set of translations in Sources, I'm not sure it was done on purpose. Either is ok for me.

**Comment by MFalletta** [comment]
It's ok for me, thanks!
