### ISSUE TITLE
Add district and country to names in Place authority dropdowns

### ISSUE THREAD

**Issue by ahankinson** [rism-digital/muscat#1675]
The Place authority has fields for Country and District, to help differentiate between different places with the same name. 

However, when choosing a place in any of the source, holding, people, institutions, etc. these values are not displayed. 

This leads to entering duplicate places, and entering district and country to the name itself. (See related #1663 )

It would be helpful to see this information in the authority dropdown chooser. 

In addition, I don't think the country and district values are searchable in the Place authority, and the District value is not shown in the table. Both of these things would be useful to see.

**Comment by xhero** [comment]
![Screenshot 2024-11-25 alle 13 49 38](https://github.com/user-attachments/assets/2f6f92cc-cd42-4774-ab61-c9a624e7782b)
Something like this?

**Comment by xhero** [comment]
Any preference on the order of district and country?

**Comment by ahankinson** [comment]
Probably district first, then country? 

Bologna, Emilia-Romagna, Italia?

**Comment by ahankinson** [comment]
And either of those *could* be null...

**Comment by xhero** [comment]
If it is null it is filtered out

**Comment by ahankinson** [comment]
Filtered out? the place won't appear?

**Comment by xhero** [comment]
Obviously not, it will not appear like this `Bologna, , ` but just `Bologna`

**Comment by BaMikusi** [comment]
I have no objections to the above but my understanding is that a project initiated by the SLUB and targeting specifically our 'Geografika' is in the pipeline, so the optimal workflow should be to address all related issues at one go once that indeed gets started.

**Comment by ahankinson** [comment]
Sure, but I've noticed that people are entering duplicate places into the place authority because they can't see which "London" is meant, so they'll add "London (England)" as a name, when "London" in the "United Kingdom" already exists. They are not actually adding it through the Place authority form, but in sources, people, institution entries. 

So this change makes it so there is less to clean up for the SLUB project. 😁
