### ISSUE TITLE
SRU response does not reference MODS namespace correctly

### ISSUE THREAD

**Issue by oliver-stoehr** [rism-digital/muscat#1690]
When retrieving a record via SRU interface the namespace for MODS is not correctly referenced in the resulting XML.
E.g. [this SRU request](https://muscat.rism.info/sru?recordSchema=mods&operation=searchRetrieve&query=dc.id%3D600113626) returns an XML body with the following MODS structure:
```
...
<mods xmlns:mods="http://www.loc.gov/mods/v3" version="3.6">
    <titleInfo>
        <title>Violin-Konzert / Heinrich Gattermeyer</title>
    </titleInfo>
    ...
```
The `mods` namespace should be either defined as default namespace:
```
...
<mods xmlns="http://www.loc.gov/mods/v3" version="3.6">
    <titleInfo>
        <title>Violin-Konzert / Heinrich Gattermeyer</title>
    </titleInfo>
    ...
```
or the `mods` node and all of its children should explicitly use the namespace:
```
...
<mods:mods xmlns:mods="http://www.loc.gov/mods/v3" version="3.6">
    <mods:titleInfo>
        <mods:title>Violin-Konzert / Heinrich Gattermeyer</mods:title>
    </mods:titleInfo>
    ...
```
With the current XML structure none of the elements are part of the `mods` namespace.

**Comment by HirschSt** [comment]
Probably this is somwhere around https://github.com/rism-digital/muscat/blob/4a2a317db9f248063b35c7f4c82e2ebd0880e250/app/views/sru/_result.xml.erb#L17, I will check this...
