### ISSUE TITLE
Ignore diacritics in filter search (JW)

### ISSUE THREAD

**Issue by HirschSt** [rism-digital/muscat#306]

**Comment by lpugin** [comment]
When sorting the columns "Composer", diacritics should be ignored. 
Example: 
"Štěpán" appears at the end of the list. 

In the filter "Composer contains", diacritics should be ignored. 
Example: "Stepan" does not find "Štěpán"

**Comment by lpugin** [comment]
@xhero can you look at this?

**Comment by lpugin** [comment]
I think this will be difficult to solve. However, if we have both in variant names it will be OK. See
http://muscat-dev.rism.info/admin/people/30003048
That is found with both spellings.

**Comment by jenniferward** [comment]
Just wondering if there is an update for this? Or should our office starting entering diacritic-free name variants?

**Comment by HirschSt** [comment]
**Filter** @xhero Probably indexing composer as special field with something like
`<filter class="solr.ASCIIFoldingFilterFactory" preserveOriginal="true"/>`
could solve the issue.
**Column** Ignoring diacritics when sorting the column should be easier.
Inserting strings only to match sorting/searching criteria is a no go IMO

**Comment by lpugin** [comment]
I agree that we should by any mean avoid to have to input diacritic-free names.

**Comment by xhero** [comment]
This is applied to all text fields in 8.0.
