### ISSUE TITLE
Escape double quotes " in PAE for MarcShow

### ISSUE THREAD

**Issue by xhero** [rism-digital/muscat#544]
`'4-G8{G''D}/2.D"/4D-'B+/2B4E/2E4-/`

The double quote crashes all the javascript in the page/

**Comment by xhero** [comment]
I would like to do it in both places, so we validate the data but we avoid problems in the show page

**Comment by HirschSt** [comment]
Yes thats the best.

**Comment by xhero** [comment]
This is en route to be fixed with the PAE correction project.
