### ISSUE TITLE
Add warning with IE

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#575]
Is there any way to have Muscat include a pop-up warning when users log on using Internet Explorer? Despite us saying "Do not use IE" over and over again, it still happens about once a month (that I know of), and users are confused when they can't save, etc. 
Such as...
This browser is not supported. Recommended browsers are Chrome and Firefox.

**Comment by xhero** [comment]
Do you think we still need this?

**Comment by jenniferward** [comment]
No!
