### ISSUE TITLE
Add button to remove a whole (material) group

### ISSUE THREAD

**Issue by cgueggi** [rism-digital/muscat#589]
Groups (which are used only for material) cannot be deleted unless the user removes all the tags by had, a delete button should be added. This is related too to the "-" for subfields #516

**Comment by xhero** [comment]
This should not be too complex, maybe we can do it for 4.1?

**Comment by MFalletta** [comment]
Das Löschen von Materialgruppen ist momentan nicht möglich, z.B. https://muscat.rism.info/admin/sources/1001172539
Es gibt eine Fehlermeldung, dass 593 ausgefüllt sein muss! (Diese Fehlermeldung kann nur von den Editoren übergangen werden.) 
Wenn alle Felder einer Materialgruppe leer sind, sollte der Block automatisch gelöscht werden.

**Comment by jenniferward** [comment]
We're getting the same error now again as reported by Martina above (maybe that's why we hesitated making both subfields required).

**Comment by xhero** [comment]
But if you delete the whole 593 shouldn't validation pass? I tried this on -test and it seems to work

**Comment by xhero** [comment]
see: https://muscat-test.rism.info/admin/sources/1001172539/edit I clicked the trash can on the 593, left only 1, and saved. Isn't this what is expected?

**Comment by jenniferward** [comment]
I can't replicate this again! I'll wait to see if anyone else reports problems.

**Comment by cgueggi** [comment]
I see now, that the original wish came from me ;-) I never had any problems to delete 593 since there is another 593 in another material group.
But now I remember what my original wish was...: For the cataloguers it would be a great advantage if there was a button to delete a whole block of material, including 593, 260, 300, 590 etc. as a whole, with just one click. This is handy in cases where you need to copy an entry (which happens quite often) and then change and save it as a new entry. If the copied entry has several material layers, one must first laboriously delete each individual used field (593, 260, 300 etc.) separately. But I fear that this is not technically feasible at all.

**Comment by HirschSt** [comment]
> I'll wait to see if anyone else reports problems.

Same problem reported by Staatsbibliothek Berlin: "Wenn man alle Felder der überzähligen Materialgruppe gelöscht hat, kommt beim Speichern eine Fehlermeldung, dass man mindestens MARC 593 ausfüllen möge – aber wenn man das tut, bleibt die Gruppe natürlich „leer“ stehen (Bsp: 1001252490, 1001252508, 1001252549)."

**Comment by jenniferward** [comment]
Thanks, I found the error on different records as well (840014460, 840014467, imported F records). I don't get the error on muscat-test though.

Apart from that, I agree with @cgueggi - deleting an entire group in one go would be convenient.

**Comment by xhero** [comment]
Feature: implemented!
