### ISSUE TITLE
Proposal for full record view

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#595]
The current record full view / preview options do not display all of the fields. A full display is needed in order for contributors to check their work. Please see the attached document for the arrangement and order of the fields. ZR and CH collaborated on this.

[Proposal preview Muscat CH_ZR an die Entwickler.docx](https://github.com/rism-ch/muscat/files/1695745/Proposal.preview.Muscat.CH_ZR.an.die.Entwickler.docx)

**Comment by cgueggi** [comment]
Thanks Jennifer! Let's try it this way (as proposed). Small changes can be done later if necessary. OK?

**Comment by jenniferward** [comment]
Yes!

**Comment by jenniferward** [comment]
Do you mean whether we still want the full view/preview option as described above? Yes, very much so!

**Comment by xhero** [comment]
I'm a bit confused here 😄 Are these fields that are in edit and not in view/preview, but should be there?

**Comment by jenniferward** [comment]
Yes. In short, there are fields in edit that are not shown in view/preview, so contributors are not able to check their work or see the full information about a source.

**Comment by cgueggi** [comment]
@jenniferward Ist the list still ok for you. Do we/you need to check it again?

**Comment by jenniferward** [comment]
I am assuming the list is still valid. I have no reason to believe anything has changed since February. (I'm afraid I personally don't have time to check it again.)

**Comment by xhero** [comment]
Ok I will try to push it to 5.1

**Comment by cgueggi** [comment]
OK, I'll take a look. But I also think there were no changes since february.

Thanks Rodolfo, that would be perfect!

**Comment by cgueggi** [comment]
I've checked the list and made some additions. New fields and open questions (i. e. unknown $-fields) are marked in blue.
@jenniferward Could you please double check and confirm (or propose changes, additions etc.)? If we're fast, the changes could already be included in Muscat 5.1...!
@xhero Unfortunately the comments are in german, sorry! We can have a look together.

[Proposal preview Muscat.2018-12-04.docx](https://github.com/rism-ch/muscat/files/2642462/Proposal.preview.Muscat.2018-12-04.docx)

**Comment by cgueggi** [comment]
How is the state on this issue? It would be nice to have this in the next release.

**Comment by jenniferward** [comment]
Sorry for not being fast! Thanks for including the new fields.

Two additions/clarifications:
041 Language code is displayed as a code. It should be the full word, i.e. not "lat" but "Latin"
594: $c should always be displayed, even when the number is 1. (Currently no number is displayed when $c=1.)

**Comment by jenniferward** [comment]
Throughout, the following fields are not in the full record view:
852$b, 852$z
710$b

Those fields should just display next to their institutions.

For some of the templates, 383 (opus number) is displaying twice: at least for theoretica_edition and libretto_edition_content, but I think in other ones as well.

**Comment by jenniferward** [comment]
One more change: In the full record view, the incipit number is displaying as "Work number". German has "Incipitnummer" and I think that is more logical. Can it be changed to "Incipit number" here (and in the other languages)? People are looking for their incipit number, not the "work" number.

**Comment by xhero** [comment]
I want to resurrect this and have it done for 7.2.
The problem here is that the 'show" functionality can have custom views for some tags. For example:

```yml
      "100": marc_show/show_person
      "246": marc_show/show_title_variant  
      "930": marc_show/show_work
      "001": marc_show/show_rism_id
```

For example, the first rule `"100": marc_show/show_person` is used to show the tag 100 using one line, like this: `Rubinštejn, Nikolaj Grigor'evič (1835-1881)`

This comes from the times when Muscat was used also to show the records to the public, hence the display was "enhanced" in many places, in a way that it could be quite different from the edit view.
If the requirement now is that Show and Edit display exactly the same data it is possible to switch to that and remove the customisations, in this case the two views will display the same data in the same order, but missing some of the "magic" features of the Show view, like automatic field concatenation (i.e. 510, the repeated fields are shown in one like separated by semicolons). Obviously then custom partials can be left here and there, but my understanding of the issue is to make the two views identical.

**Comment by jenniferward** [comment]
Can you suppress the "Set" field, since it is added by Muscat and has no meaning to catalogers?

**Comment by fjorba** [comment]
As a complement (or alternative?) to this request, a raw Marc view would be also necessary, specially if Blacklight is being removed from Muscat.

**Comment by jenniferward** [comment]
@fjorba That's an interesting thought, and indeed many OPACs provide a "librarian's view" to the records. You can add .xml to any URL to see the MARCXML view - does that help? Ex. https://muscat.rism.info/admin/sources/1001031654.xml

**Comment by fjorba** [comment]
Thanks for the hint, @jenniferward, but xml (marcxml in that case) is not specially user friendly to read.  With current Blackight (/catalog) interface, a .txt is already available (ex: /catalog/249906.txt), but not under /admin.

As Blacklight is going to be removed, this .txt view under /admin/sources (but also /admin/people et al), with a proper icon and link in the right panel would be great.  I'll try to work on a patch, if you also think that it would be useful.

**Comment by xhero** [comment]
Ok one moment please before adding random stuff to the system. Firstly Blacklight is not yet deprecated, and when that time will come, the idea is to move the Muscat compatibility interface outside of Muscat proper so the two systems can be maintained separately. Secondly if we want to download MARC records in text format this is doable but we need to what this format is, and also what record we are going to export (internal or external). BTW this is something different than having a "MARC View" box as we had in Muscat 2.0 integral to the view page.

**Comment by fjorba** [comment]
I see, thanks for the comments, but I was indeed talking about viewing the record in Marc (that is, a Marc view), independently of an export format.
