### ISSUE TITLE
Page navigation sometimes missing

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#597]
Sometimes when I'm paging through sources, the Previous/Back to the list/Next buttons are missing at the top. I don't have a good idea of when this happens; sometimes it's there, and when I leave the screen and return to it again, it's gone. My coworkers have noticed the same thing, but we can't pinpoint the cause.

Currently, the page navigation is missing from the records contained in these folders:
http://muscat.rism.info/admin/folders/157
http://muscat.rism.info/admin/folders/159
I created the folders using the "Add all to a new folder" link at the bottom right of the Sources page.

However, the page navigation is present in these folders:
http://muscat.rism.info/admin/folders/158
http://muscat.rism.info/admin/folders/160
I created these folders using the individual selection and "Batch actions/Create folder with items" link at the top left of the Sources page.

I don't use folders very often, so I don't know if that is the cause.

**Comment by xhero** [comment]
Could you provide more context? Do you mean the navigation buttons on top of the page when you view a source? They should not be displayed at all when you select a source from the Folder listing.
Regarding the disappearing ones it depends what you do when you leave the page: do you normally just go back to the Source list and then in a source page?

**Comment by jenniferward** [comment]
I'm talking about the navigation buttons "Previous/Back to the list/Next" when I view a source, see screenshot. 
![auswahl_055](https://user-images.githubusercontent.com/18663291/36024985-c2b3628a-0d91-11e8-8a64-3d309ea93c54.png)

It's hard to describe the context because it seems like the buttons vanish without reason. Strangely, today, there is no navigation available in folders 158 and 160, even though they were present when I reported the issue above.

Why should there be no navigation buttons when you select a source from the folder listing? It seems to me that it would make sense to be able to navigate within a folder.

The buttons disappear sporadically, so next time it happens again, I'll try to describe it here.

**Comment by lpugin** [comment]
The navigation is shown only if 1) there was a search, and 2) if you are looking at a manuscript that is part of the result set. For example, if a collection is part of the results, and then you go to a child manuscript that is not part of the results, then the navigation there will not be shown. (It will when you go back to the collection.) Could this be the issue?

**Comment by jenniferward** [comment]
Can we re-examine this ticket? (I see it is closed now.) This has been an ongoing, rather annoying issue but I think I have found a (the?) situation in which in crops up. This actually doesn't specifically have to do with folders. It has to do with having multiple sessions (multiple tabs) open in Muscat at the same time on the same browser. 

You are probably already aware that this happens (and maybe Muscat was programmed this way on purpose): When Muscat is open in multiple tabs on the same browser, the search in Sources (for example) migrates across sessions. For example:
1. First tab: search for Bach, click View for any source. You see the page navigation as usual.
2. Second tab: search for GB-Lbl
3. Return to the Bach tab and click on "Back to the list". The search is now populated not with Bach records but with GB-Lbl records.

I've noticed this before, and normally this doesn't bother me, but today it dawned on me that this is why the navigation disappears:
1. First tab: search for Bach, click View for any source. You see the page navigation as usual.
2. Second tab: search for GB-Lbl
3. Return to the Bach tab and click "Next" to go to the next record. My next record is a Bach record, but the page navigation is gone. If I click on "Sources" now, I get the GB-Lbl results. 

Losing the page navigation impedes work and disrupts my workflow, particularly when I am working on multiple, interrelated issues at once that require me to be working within separate groups of records. 

I'm not sure if this is something the developers want to change, but at least I have found the cause for my "disappearing" page navigation.

**Comment by xhero** [comment]
Ok now I get the exact problem (I could not reproduce it with folders). We will probably need a redesign of the search storing mechanism, as it is designed to work as in your first example right now.

**Comment by xhero** [comment]
(since I'm already working with stored params[]...)
The issue here is that search params are globally stored, and overwritten every search. So when to tabs are open at the beginning both have the same search params, but if in the second tab a new search is made, the params are overwritten. When in turn the first page is reloaded (i.e. "next" on the navigation), the params get overwritten with the ones of the second tab.
This needs to be rediscussed, as Muscat is not designed to work with multiple searches on the same browser (but will work with two different browsers!)
