### ISSUE TITLE
Secondary literature: ignore punctutaion in search?

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#622]
http://muscat.rism.info/admin/catalogues
A search for "Annotated Catalogue of Chopin’s First Editions" (without quotation marks; text copied from a website) in the field "ANY FIELD CONTAINS" or "DESCRIPTION" does not find
http://muscat.rism.info/admin/catalogues/30025545 . However, if you change the apostrophe to ' then it is found:
Annotated Catalogue of Chopin's First Editions 

Can the search please ignore punctuation, or at least re-format text so it is in a form it understands?

**Comment by jenniferward** [comment]
This came up today in the Institutions:
Search for: La Seu d’Urgell
finds only 1 hit

Search for: Urgell 
finds 3 hits because the apostrophe in La Seu d'Urgell is different!

**Comment by jenniferward** [comment]
This applies to Personal Names as well.

I'm afraid this affects many users. When I was in Argentina, with the participants typing on many different Argentinian computers, we were not able to find names like Vásquez when the á was typed with the keyboard. As a result, information was not found and duplicates were created. I was surprised that typing a Spanish character on a Spanish keyboard did not work.

We had this problem when searching the Secondary Literature database but also when using autocomplete in Sources (thus connecting to Personal Names).

**Comment by jenniferward** [comment]
All of my examples work on muscat-test, thanks to @fjorba's patch in #690.

You do need the exact diacritics in the autocomplete in the 100/700 fields, but the correct name can always be retrieved using the search function.

**Comment by xhero** [comment]
The new patch in #690 fixes this and all the examples work, so I'm closing this.
