### ISSUE TITLE
Secondary literature: Automatic insertion of new values needed

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#631]
While inputting a new record in Secondary literature, automatic new entries need to be possible in the following fields:
100, 700, 710, 760$t, 650, 651

Currently users need to input new names, subject headings, institutions, etc. separately before entering them in the literature record. This interrupts and slows down the workflow. Automatic entries should be allowed as they are in Sources.

**Comment by jenniferward** [comment]
This was echoed in Kraków by our contributors: It slows down work when we have to stop and create new names, subject headings, etc. Muscat would be easier to work with (and more attractive for new contributors) if this was enabled.

**Comment by xhero** [comment]
What to do you mean with automatic new entries? the "confirm a new value" checkbox as in sources?

**Comment by jenniferward** [comment]
Yes!

**Comment by jenniferward** [comment]
Reopening this - I think institutions were overlooked here? We don't have the "confirm a new value" for institutions (field 710) in Secondary Literature.

**Comment by jenniferward** [comment]
We have this now, thanks!
