### ISSUE TITLE
Sticky sidebar in Source#show (was: Freeze menu bar on Muscat?)

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#732]
A suggestion: Is it possible to freeze the menu bar at the top of Muscat so it is always visible no matter where you are on the page? When I am scrolling through a very long record, or when I am on a long page such as the MARC configuration or the guidelines, it would be nice to find the links to Faceted search /Sources /Authorities  /Guidelines and the rest quickly, without having to scroll all the way back up again. A minor annoyance, to be sure, but this improvement would be a great convenience.

**Comment by xhero** [comment]
This would be nice but I'm not actually sure it is doable unfortunately @lpugin what do you think?

**Comment by HirschSt** [comment]
But we can fix the position of #muscat_admin_header by css, can't we?

**Comment by xhero** [comment]
we can try and see if it works!

**Comment by jenniferward** [comment]
In a way, clicking on one of the sections also takes you to the top. So maybe I just need to get used to that.

**Comment by jenniferward** [comment]
I take that back: In the Full Record View, the section navigation stays at the top. Here is a long record with lots of scrolling where navigation would be nice:
https://muscat.rism.info/admin/sources/1001045405

**Comment by xhero** [comment]
I think that once upon a time the sidebar was sticky, did we remove it in muscat 3?

**Comment by lpugin** [comment]
As far as I remember it was removed because with more and more options added to the sidebar (save, save and quit, etc.) then it would not be shown completely on small screens. We need to keep this in mind for new changes.

**Comment by xhero** [comment]
Wait - the sidebar *is* sticky in edit, would it suffice to make it like this in show?

**Comment by jenniferward** [comment]
I don't mean the side bar, I mean the menu at the top: 
![image](https://user-images.githubusercontent.com/18663291/55722530-da488480-5a06-11e9-8861-9b3d42c8b4cd.png)


I need a quick way of getting to the top of the page and this navigation.

**Comment by cgueggi** [comment]
@jenniferward If you're using a Microsoft keyboard press "ctrl+home"

**Comment by jenniferward** [comment]
Strg + Pos 1 on my keyboard. I didn't know that. Thanks!

**Comment by MFalletta** [comment]
Solche Tipps sind Gold wert! Danke!!!

**Comment by jenniferward** [comment]
Cédric's Hot Tip solves this for me, so this can be closed as far as I'm concerned - will let the developers decide if they want to pursue this with a different technical solution.

**Comment by lpugin** [comment]
OK, thanks. Closing the issue for now

**Comment by jenniferward** [comment]
Commenting on a closed issue, just for the record: A user requested the ability to quickly get back to the top of the page. I will tell him the "ctrl+home" trick, but it just shows that it is not intuitive to all.

**Comment by xhero** [comment]
I'm resurrecting this since it seems quite easy to set the sidebar to sticky in Show and add the button. I will add it to 8.0 and see how it works, then we can see if to expand it to other auth files

![Schermata 2021-11-30 alle 10 44 29](https://user-images.githubusercontent.com/1691778/144023876-a3f74a04-6033-48c8-a0bf-3cc8b75b4729.png)
