### ISSUE TITLE
Add item count for collections and composite volumes

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#749]
In parent records (collections and soon composite volumes) you have "Items in this source" and then sometimes a very long list of items connected to the record (774). Since the number of items plays a part in determining the standardized title, it would be nice if Muscat counted the items for us. Sometimes it is hard to count, especially if there are a lot or if you have to scroll. Most convenient would be a placement in the Editing mode, but having it in the Full record view would work too.

Ideas

![image](https://user-images.githubusercontent.com/18663291/53883961-cb8f3c00-401a-11e9-9616-60fcbeb2a27e.png)

or
![image](https://user-images.githubusercontent.com/18663291/53884046-ee215500-401a-11e9-903a-5aeaa055a254.png)

**Comment by xhero** [comment]
I think we can do this with a bit of javascript magic
