### ISSUE TITLE
Clickable URLs in Full Record View (Secondary Lit, Comments)

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#750]
In the Secondary Literature:
Currently in the Full Record View in Muscat the URLs that go to external websites aren't active (text only). Field 856.
Example: 
https://muscat.rism.info/admin/catalogues/41001680

Could they be made live links, as in Sources? (Example: https://muscat.rism.info/admin/sources/900024163)

Can links be made active in Comments too? Example: https://opac.rism.info/search?id=lit2425

**Comment by xhero** [comment]
We should be able to apply the same magic we have for 856 in Sources (it still works there no?)
For the comments, do you mean to have http:// links be clickable? That should be (relatively) easy.

**Comment by jenniferward** [comment]
Yes, it still works in Sources! Work your magic.
Yes to comments: the http:// links should be clickable - that would be so much easier for us. Thanks!

**Comment by jenniferward** [comment]
This seems to have been taken care of for Secondary Lit (thanks!) but not Comments yet. I have no idea why I linked to the OPAC above. This is what I meant for a link in the Comments:

https://muscat.rism.info/admin/sources/1001112755
