### ISSUE TITLE
Rename liturgical feasts to events

### ISSUE THREAD

**Issue by HirschSt** [rism-digital/muscat#756]
- [x] add function ("task") column to distinct between secular/sacred
- [x] attribute all existend feasts as "sacred" (sql)

it's agreed that the current liturgical feast authority should also contain some secular events (eg Coronations); the authority should be renamed as "**Events**". 
In a first step this only touches the UI (labels etc). We can leave all db dependencies as they are (since one aim is to create a term based "Thesaurus" as Marc-Class with all relevant terms, differentated by indicator sometimes later.

**Comment by jenniferward** [comment]
"Event", please, because the field names are in the singular.

**Comment by cgueggi** [comment]
I'd clearly prefer not to mix these two areas, since a liturgical feast (imo) is not an "event" in the classical sense. I'm also thinking of the research possibility in this specific field. Especially for musicians it is nowadays more likely to look for a liturgical fest than, f. e. for a coronation. Suggestion: Would it be possible to create a second subfield under 657 for secular events?

By the way: There is a big mess in the authority data set of 657, where terms like "per 2 voci" appear. It seems to be a problem of migrated data from Italy...?!

**Comment by HirschSt** [comment]
@jenniferward ok plural in the menu, not the field label
@cgueggi thanks, the issue concerning ICCU data import is known, we are working on this. 
The request for adding further terms in liturgical feasts is coming from other projects. Marc itself describe 657 most generic as "Index term that describes the activity...". Your suggestion - indicating the character of the event by a subfield - seems quite good for me. Our idea is to add this indicator directly in the authority record, so it's clear that the term is secular or sacred (or whatsoever). In both cases the character of the event is preserved.

**Comment by cgueggi** [comment]
@HirschSt Thanks! This seems to be the perfect way to go!

**Comment by lpugin** [comment]
I am not against renaming it to "Event". However, we need to make sure there is a distinction between actual events (e.g. one specific date in history), which differs from abstract events as we have now in the data (e.g., Pentecostes). Could you elaborate on the data that will be added from other projects?

**Comment by HirschSt** [comment]
This is a request by the early motet project in Mainz, which is in preparation - so unfortunatley at the moment I have no example at hand; but we can distinct between periodical and singular events by adding another attribute to the schema.

**Comment by HirschSt** [comment]
follow up in #761

**Comment by jenniferward** [comment]
It was my understanding that this field was to name events in a general way, such as Pentecostes (even if the source was written for one specific Pentecost) or Coronations (even if the source is for one specific coronation). MARC21 has 647 for a specific "Named event", so I presume that a named (specific) event would be better placed there.  

We still need to discuss internally (and the discussion is planned) how to use this field: For example, we already have subject headings (650) for some events such as Wedding music and Funeral music; does a cataloger need to add "Wedding music" in 650, "Weddings" in 657, and "Wedding of X to Y on 30 September 1718" in a potential 647?

**Comment by xhero** [comment]
I'm closing this for the moment, I think it will be solved when we have the new auth layout?
