### ISSUE TITLE
dub in relator codes (700 $4)

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#773]
I'd like to revisit "dub" in the relator codes for people (700 $4). I found some emails from 2016 about this but it might be good to take a fresh look.

"dub" in Muscat is called "Uncertain." "Uncertain" makes sense as a relator code, but since we are linking it to dub, we should keep the MARC definition in mind. According to the MARC standard, dub is for "a person or organization to which authorship has been dubiously or incorrectly ascribed". But this is completely covered by some of the Attribution designations in RISM: 
-alleged: if the name is on the source, but doubtful
-misattributed: if the name is on the source, but wrong
-doubtful: authorship is in question [for other reasons]

Therefore it doesn't make sense for us to have dub as a function as well. @cgueggi wrote once that dub in a relator code should "bezieht sich jedoch auf eine nicht gesicherte Funktion der betreffenden Person." I think it makes sense to be able to express this function, but to me, this is better covered by relator code asn, Associated name: "A person or organization associated with or found in an item or collection, which cannot be determined to be that of a Former owner [fmo] or other designated relationship indicative of provenance." So asn/Uncertain would cover other names where a relationship to the source is present but the exact function is uncertain (and oth/other means the function is known but it's not on our list of functions).

I propose keeping "Uncertain" as a label but changing dub to asn. (Or, "Associated name" isn't bad, either, or incorrect, and we have that in Secondary Literature.) Thoughts?

**Comment by cgueggi** [comment]
@jenniferward convinces me (the longer the more ;-)
I'm d'accord, since the dub/asn-case does not occur very often.

**Comment by xhero** [comment]
So if I understand correctly:

1) rename `dub` in 700 $4 list to `asn`
2) Fix the 505 records that currently use `dub` to `asn`.

is this correct? It would be a simple task to perform.

**Comment by cgueggi** [comment]
Let's do it!

**Comment by jenniferward** [comment]
I think that sounds fine!

**Comment by xhero** [comment]
It was not done, right?

**Comment by jenniferward** [comment]
For the Muscat editor, Uncertain should be removed
asn should be added as a function = Associated name.

**Comment by xhero** [comment]
-> Uncertain and 'dub' both removed from editor, data fixed dub -> asn, add 'asn' and Associated name to editor.

**Comment by jenniferward** [comment]
Re-opening this to ask if the records were corrected that contain `dub`? It is still in at least 414 records, for example:
https://muscat.rism.info/admin/sources/400003635 
https://muscat.rism.info/admin/sources/403012674
https://muscat.rism.info/admin/sources/990044132 

I'm not sure if it is also in 710, or in holdings.

**Comment by xhero** [comment]
What should I do here? @HirschSt or me can make a script to remove the dubs, what should they become?

**Comment by jenniferward** [comment]
`dub` should be changed to `asn` in both Sources and Holdings. 

@cgueggi Could you please confirm that this is still a good idea? I think it is mostly form the CH import.

**Comment by cgueggi** [comment]
Thanks for the reminder!
I'm still fine with that! Let's change it!

**Comment by xhero** [comment]
Fixed all the Swiss data!
