### ISSUE TITLE
031 $n/p: display sharps/flats in [ ]

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#808]
In the RISM guidelines for the field Key signature (031 $n), it says "Add missing sharps or flats in brackets." You use this if, for example, the piece is clearly in A major but the source only has xFC. You enter xFC[G]. This is a very old RISM rule that we've had since CD-ROM days.  In the CD-ROM the sharp/flat in the key signature would display in brackets. In Muscat, the [G] can be entered but it does not display in brackets. Can you change it so that the sharps/flats are in brackets?

Unfortunately I don't have an example on hand.

**Comment by xhero** [comment]
@lpugin do you think it could be implemented in Verovio? Maybe we can move it to the wishlist

**Comment by jenniferward** [comment]
Here are some examples  - we have  [ in 031$n 3,400 times:

https://muscat.rism.info/admin/sources/000108924
https://muscat.rism.info/admin/sources/000109594
https://muscat.rism.info/admin/sources/854000005

**Comment by xhero** [comment]
I think this is more related to the PAE corrections + verovio
