### ISSUE TITLE
Some time signatures in 031 $o do not display in 031 $p

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#809]
Some of the time signatures in Plaine & Easie only display if a certain clef (common or mensural) is selected. Is that on purpose? I wonder if it would be better to have them display in both kinds of clefs. We have some sources from GB-Ob where the clefs and notation were "common" but the time signature is mensural. 
Example: https://muscat.rism.info/admin/sources/800273244/

Does not display with common clef:
3/4 4/4
c3
c3/2
c. 
o
o/ 
o.

Does not display with mensural clef:
3/4 4/4
single numbers like 1, 2, 3

**Comment by xhero** [comment]
The problem appears when mixing "old" time signatures with "new" style of notation, and vice-versa. It appears in quite some ms entries entered from cards, probably we could tweak verovio to show "old" time signatures in "modern" notation, it happens quite a lot in Mss from the 17th century.

**Comment by xhero** [comment]
The PAE guidelines are not super clear, but other signatures like 3/4 + 4/4 should be displayed, probably we should implement this in verovio (and ope a ticket there?)

[](https://www.iaml.info/plaine-easie-code#toc-3)

**Comment by jenniferward** [comment]
Adding to this:  We would also like combinations with common clef such as o.3 and c3/2.
