### ISSUE TITLE
Links to composite volume 973

### ISSUE THREAD

**Issue by MFalletta** [rism-digital/muscat#812]
Verknüpfungen zum Konvoluteintrag sollen möglich sein von den 

Holdings  -- links to ---> composite volume

Single handwritten items  -- links to  ---> composite volume
music manuscripts
libretti
treatises

Manuscript collections -- links to ---> composite volume
music manuscripts
libretti
treatises

**Comment by HirschSt** [comment]
This is not clear. Can you please list exactly all the templates from https://muscat.rism.info/admin/sources/select_new_template?locale=en which should have a linkage to composite?

**Comment by MFalletta** [comment]
Holdings dürfte klar sein,
dann in der Abfolge von https://muscat.rism.info/admin/sources/select_new_template?locale=en:

Handschrift
https://muscat.rism.info/admin/sources/new?new_record_type=collection
https://muscat.rism.info/admin/sources/new?new_record_type=source

Libretti
https://muscat.rism.info/admin/sources/new?new_record_type=collection
https://muscat.rism.info/admin/sources/new?new_record_type=libretto_source

Theoretica
https://muscat.rism.info/admin/sources/new?new_record_type=collection
https://muscat.rism.info/admin/sources/new?new_record_type=theoretica_source

**Comment by HirschSt** [comment]
Danke!

**Comment by xhero** [comment]
Wait, so there is more than one item that should connect to more than another item?
We have a fix for this in a branch, for the moment it enables single items and collections to link both to collections and composite items.
BTW to "link" is already possible, what is not possible right now is to select the elements from the interface. The branch fixes this.

**Comment by HirschSt** [comment]
Because the template system tends to be somehow obscure (just my impression), how about defining something like an "allowed_relations" method in the template.rb module to prevent at least recursion? From there we can define also the filter for the magnifying glass...

**Comment by HirschSt** [comment]
> I think that once we know exactly what are the linking requirements we can remodel the backend and the frontend.

That's exactly what I think :+1:  : we need a clear relationship model on sources templates and holdings.

**Comment by HirschSt** [comment]
I think the current requirements are something like this:

![image](https://user-images.githubusercontent.com/6461776/61109132-6d6cdc80-a484-11e9-9c2a-d8ed04cce0c7.png)

Can we agree on this?

Maybe some confusion occurs with single item, which refers to a composite with 773 exactly like part-of-collection item to collection relationship.

There should be no "collection in collection" - IMO this was one idea behind introducing composite.

**Comment by lpugin** [comment]
Yes, this looks good to me. Very useful. If there are some collection in collection, they we should probably be able to migrate them, shouldn't we?

**Comment by HirschSt** [comment]
> shouldn't we?

Yes, I hope so... we can use the template change method via maintenance. 

For now we have about 400 collections in collections

```ruby
2.4.1> Source.where(record_type: 1).where.not(source_id: nil).size ⏎
2.4.1> 393
```

and in some rare cases "collections in collections in collections" (see https://muscat.rism.info/admin/sources/1001072189) which could be difficult

**Comment by xhero** [comment]
Didn't we modify Muscat to allow this? I think we can close this ticket.

**Comment by HirschSt** [comment]
No, as seen in the requirements: it should not be possible to link a collection to another collection.

**Comment by MFalletta** [comment]
Bitte dt. Bezeichnung "Eingesprungen" ändern in "Zusammengebunden mit"
