### ISSUE TITLE
Avoiding Norman Doors in Muscat

### ISSUE THREAD

**Issue by xhero** [rism-digital/muscat#815]
There are some features in Muscat that are either slow to respond, or not easy to see if applied, or both, and can be quite confusing to users (and developers too...)
These are some areas that can use improvement:

* Filters in source/authorities: It is not really clear when a page is filtered or not. We should have a way to make this clear
* Filters from the secondary selection page (magnifying glass) are carried over to the main source page! This is above confusing
* Sorting remains sorted even after the filters are cleared or re-applied
* It is not clear when the user is in the "sections" in the edit page, and it is not at all clear how to get out of single-section visualization. This is quite frustrating for users.

Other issues are due to some lags in the software:
* Backend validation is slow and the edit page freezes until it has completed. If internet foes down it basically freezes there
* Autocomplete can lag when getting the data from the backend, this means the user can type things in the autocomplete before the menu appears, but will not be validated, since it is not selected from the menu
* Going to preview triggers backend validation and everything freeses, going back to the edit freezes again

These issues cold be alleviated by having some "loading" messages or animations

We can have individual tickets for this, it would be nice to at least home some in 5.3

**Comment by jenniferward** [comment]
For the first point,  It is not really clear when a page is filtered or not: It would be nice to have a message at the **top** of the filters, like an orange message "Filters activated" that appears at the top of the "Filters" column.

**Comment by jenniferward** [comment]
Actually, this Search Status box appears below the filters after you do a search. Maybe that can just be moved to appear at the top? 
![image](https://user-images.githubusercontent.com/18663291/94665502-845b5100-030c-11eb-8bfc-6a275c3b510b.png)
