### ISSUE TITLE
Navigation and right menu bars

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#828]
I know that the right-hand navigation menu is designed to stay "fixed" in place but when there are too many menus open then you can't get to the bottom of the menu, for example on Guideilnes:
![image](https://user-images.githubusercontent.com/18663291/63750812-77209700-c8ae-11e9-934e-4486643a87df.png)

I was wondering if that design strategy still make sense? I've run into similar problems when doing demonstrations/workshops and I need to enlarge the screen: When looking at a musical source in the editing mode, I can't save the source or basically do anything beyond "show preview" without zooming out, saving, then zooming in again. (And people who need to always have the screen enlarged can't see the "save" at all.)

**Comment by xhero** [comment]
The guidelines are getting a new site dedicated to them!

**Comment by xhero** [comment]
Oh no! Should we have a tracker specific for the guidelines? @lpugin

**Comment by jenniferward** [comment]
The fun is happening over here --> https://github.com/rism-digital/muscat-guidelines/issues/49
