### ISSUE TITLE
Works: add "Language" to template

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#848]
It would be good in work records for vocal pieces to name the language. MARC 377 seems to allow this:
https://www.loc.gov/marc/authority/ad377.html
and it is repeatable.

It should be a drop-down menu and include all the values as in the 041 in Sources.

**Comment by jenniferward** [comment]
On second thought, this might be better in the 100:
100 $l - Language of a work
but it is not repeatable.

**Comment by fjorba** [comment]
Sorry, but aren't you confusing language note in the bibliographic record (https://www.loc.gov/marc/bibliographic/bd546.html) with the language ($l) of a work ($t) in the authority one?

In the bibliographic record, effectively 546 matches, in natural language, the code in 041.

**Comment by jenniferward** [comment]
We need a way to indicate the language for work authorities.

**Comment by fjorba** [comment]
You are right, certainly.

**Comment by xhero** [comment]
Related to #849, would be nice for 6.4
