### ISSUE TITLE
Solr crash with division by zero in 031$o

### ISSUE THREAD

**Issue by HirschSt** [rism-digital/muscat#860]
eg "2/0" seems to be too hard for sunspot solr, so its getting crashed completly with my installation of 5.3. 
Can you test this on other environments?

**Comment by xhero** [comment]
I pushed a fix in muscat, in 6.2 I want to add more controls directly in Solr

**Comment by HirschSt** [comment]
Yes, a bit ugly, but most important that this fixed the issue

**Comment by xhero** [comment]
nono don't close it! :D I want to fix it in solr too in 6.2

**Comment by HirschSt** [comment]
ok, sorry

**Comment by lpugin** [comment]
Out of curiosity, where is the fix?

**Comment by xhero** [comment]
It is in the solr jar repo, it was a division by zero in humdrum
