### ISSUE TITLE
Search for old and new identical subject headings with diacritics: doublets not found

### ISSUE THREAD

**Issue by Docudoctor** [rism-digital/muscat#881]
The search for old and new identical subject headings with diacritics (ex. Mélodies) in "Any field contains" is only leading to the old RISM record with the ID 3000206. The French doublets (from BNF) recently loaded in Muscat are not found. There are seven more. Vice versa the same: I copied a recently loaded French doublet (just the keyword Mélodies) into "Any field contains" and received only the new seven doublets, but not the old RISM one (ID 3000206). 

Maybe this refers to the tickets #306, #622, #690

**Comment by jenniferward** [comment]
This works on muscat-test, thanks to patch.

**Comment by jenniferward** [comment]
This is fixed!
