### ISSUE TITLE
French records from BNF, wrong characters used in incipit codes very often

### ISSUE THREAD

**Issue by Docudoctor** [rism-digital/muscat#885]
Wrong characters: 
1) quotation mark " used for the two-line octave should be two apostrophes.
2) underscore _ used for a tie should be +

Can you change this auotmatically?

**Comment by Docudoctor** [comment]
3. wrong character is the capital N in function of a natural, should be a small n.

Can you also change this?

**Comment by Docudoctor** [comment]
4. wrong character is the capital X in function of a sharp, should be a small x.

Can you also change this?

**Comment by xhero** [comment]
I'm closing this, as we have a dedicated project + tracker to fix incipits.
