### ISSUE TITLE
French records from BNF, key "Mi majeur" mistransferred to "E minor"

### ISSUE THREAD

**Issue by Docudoctor** [rism-digital/muscat#890]
Ex.: RISM ID 840022159. Please review the link to the original catalogue entry and see the modification history of the RISM ID. 
I found some more ex. 
Guido

**Comment by Docudoctor** [comment]
A 2nd ex.:
See also incipit (031) of RISM ID 840010288. Check the modification history.
Best,
Guido

**Comment by jenniferward** [comment]
For the record: Not relevant to Muscat development, but the problem is still in the data (to be taken care of elsewhere).
