### ISSUE TITLE
852 Fehlermeldung bei Validierung 

### ISSUE THREAD

**Issue by Docudoctor** [rism-digital/muscat#894]
![852 Fehlermeldung](https://user-images.githubusercontent.com/26874482/75326504-0701c680-587b-11ea-9cb5-385d4058539b.PNG)

Musste gestern abbrechen. Danach konnte ich das Sigel erneut überarbeiten und auch abspeichern.

**Comment by Docudoctor** [comment]
Es handelte sich aber nicht um F-Pn.

**Comment by xhero** [comment]
What happened here? Because I can save the record. DId you select the new sigla from the list or typed in one without selecting?

**Comment by Docudoctor** [comment]
The siglum F-Pn is all right. Nothing is lost. I also made a little correction a minute ago.

**Comment by Docudoctor** [comment]
I think, I received this mistake while I was saving another siglum record. I cancelled the correction and started again with several corrections step by step and did not receive the mistake again, but here when I opened F-Pn and saved it. I was also checking all other French sigla I was correcting yesterday. They are okay.

**Comment by Docudoctor** [comment]
I will make a screen shot, when this mistake occurs again.

**Comment by Docudoctor** [comment]
Sorry. It was a source (RISM ID 840014314) not a siglum. Replace siglum by source in my description. I remember it now. The source is all right. 
I had too many unanswered questions in my head, as well as Ch. Ives. ;)

Thank you.
Guido

**Comment by jenniferward** [comment]
Seems to be ok now!
