### ISSUE TITLE
Triolen mit Pausen am Anfang

### ISSUE THREAD

**Issue by MFalletta** [rism-digital/muscat#913]
Steht am Anfang der Triole eine Pause, stimmt der Wert der ersten Note in der Grafik nicht.
Beispiel Incipit 1.1.2  
https://muscat.rism.info/admin/sources/1001107892
![Incipit Triolen](https://user-images.githubusercontent.com/18736235/77314618-4bf80c00-6d06-11ea-94b7-97864dd980f7.JPG)

**Comment by rettinghaus** [comment]
see https://github.com/rism-ch/verovio/issues/1231

**Comment by lpugin** [comment]
Solved
