### ISSUE TITLE
Visualise 856 in holding records

### ISSUE THREAD

**Issue by baccia** [rism-digital/muscat#930]
A linked source digitisation should be visible also from the 856 in the holding record, e.g.
https://muscat.rism.info/catalog/992004547

**Comment by jenniferward** [comment]
Agree - though I usually approach from the edit mode, so https://muscat.rism.info/admin/sources/992004547

**Comment by xhero** [comment]
this would be useful mostly for our data on rism-ch

**Comment by jenniferward** [comment]
Oh ok; though more than once I've wished there was a quick way to see which prints had links to digital surrogates (to save the step of going to the OPAC).

**Comment by xhero** [comment]
Do you think it would be useful to see the images in the "show" page of Muscat? I think it is not too complex to add, I just though nobody needed it!

**Comment by jenniferward** [comment]
Maybe, but I was thinking simpler, like just a link symbol next to the siglum on the right under "Exemplar information".

**Comment by xhero** [comment]
this is more a BL issue and since we are moving away, I would wait until the new search interface is ready to implement this.
