### ISSUE TITLE
Add items to folders from full record view

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#931]
I would like the ability to add items to folders from the full record view.

**Comment by jenniferward** [comment]
And remove: so if you are going through a folder and you no longer need the item, you can remove it and work until the folder is down to 0.

**Comment by fjorba** [comment]
We are also very interested in this issue, and I'm willing to work on it, but I have some doubts/questions.

First, about the user interface:

- I imagine that adding from the full record view could be done with an icon/link in the side bar, right?
- And removing the item from the folder? Should it be done both from the full record view, right? But also from the list of items in the folder view (that is, /admin/folders/1234)?

The second question is about permissions: who could add and remove them?  I think that the owner of the folder is clear, but any other user with greater permission could?

**Comment by fjorba** [comment]
> From the Sources view https://muscat.rism.info/admin/sources?clear_filters=true if you tick the box next to a source then you get batch actions to add/remove. I wonder if that can be replicated on the full-record view?

Yes, I understand that, but I'm trying to confirm that the place to have the button or pulldown menu would be in the sidebar (at the right of the screen), not at the bottom of the record (at the left side).

> Sure, it might be useful to remove items from the folder view (like /admin/folders/1234). I haven't encountered that need but it maybe other people need it.

I see. So I'll prioritize the full record view again.

> We haven't quite resolved all issues related to permissions (see #1239). I think the concerns I raised there would apply here as well.

I'll take that into account, I didn't know it, thanks for the pointer.
