### ISSUE TITLE
Keep your place in folder navigation

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#932]
I'm working with a folder, pieces sorted by title A-Z, and would like to edit from the first record to the last record. If I am on "M" for "Marches" and change the title to "The rangers" and save, I want the next record to start with an M. However, since the title now starts with a T, I have skipped to later in the list and am on the Ts. It is difficult to know when I have edited everything.

Is it possible to retain your place when navigating within a folder?

**Comment by xhero** [comment]
Since I'm working with searches, where does this happen? When you filter sources by "is in folder"?

**Comment by xhero** [comment]
This is actually a more generic problem with the prev/next navigation bar. If a search is ordered and a record in the search changes the field it is ordered in (i.e. 240 order by standard title), the item will change its position in the next search (as it should). The implementation of prev/next runs a new search each time these buttons are pressed, so if 240 changes, also the position of the record in the order changes, causing the navigation to "jump".
A solution is to be careful not to modify the field that the search is ordered in (for example, to modify 240 order by rism id).
There is no way at the moment to fix this, as it is not possible to cache the first, "original" search before any editing is done. We can see in the future if this becomes a big problem (also with the new tab implementation) if/how to implement a cache for navigation.
