### ISSUE TITLE
Remove fields 563 $u and 963

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#971]
The fields 563$u (bibliographic level) and 963 (holdings) to indicate bound material have been replaced by the composite template. Can we think about removing those fields from the editor?

963 is used by CH in about 100 records. Maybe @baccia should edit those first?

@xhero Can you give me a list of records where 563$u is used?

**Comment by baccia** [comment]
The 963 is now removed from all CH records.

**Comment by jenniferward** [comment]
Thank you, @baccia ! 
Actually I think I can find all the 563$u fields. I will work on cleaning that up, then report back here.

**Comment by xhero** [comment]
Any news here? I would like to remove this field in 7.2.

**Comment by jenniferward** [comment]
Please get rid of it, but could you do a data pull of 563$u just before? I have discovered that the field has been used since my inital ticket above, and I suspect it is in some unpublished records as well (the unpublished records aren't in the data dump).

**Comment by xhero** [comment]
It is used only in these two records:

1) 1001053587 `=563  ##$u990026165$801`
2) 1001147246 `=563  ##$aBound in partbooks with other overtures$u1001145164$801`

I will make it disappear before it is discovered again...
