### ISSUE TITLE
Sortierung Personen (diakritische Zeichen)

### ISSUE THREAD

**Issue by alexandermarxen** [rism-digital/muscat#978]
Wäre es möglich, die diakritischen Zeichen bei der Sortierung (und Suche) zur ignorieren?
Das könnte helfen, zahlreiche Dubletten zu vermeiden.
![Personen-Muscat](https://user-images.githubusercontent.com/42838336/91834020-c890fe00-ec47-11ea-85bd-d016a23671dc.png)

**Comment by jenniferward** [comment]
See also #622, #690, #881

**Comment by jenniferward** [comment]
The search works on muscat-test (Muller/Müller, Wroclaw/Wrocław), thanks to @fjorba's patch in #690.

**Comment by HirschSt** [comment]
@alexandermarxen kannst Du bitte nochmal die Sortierung prüfen? Bei mir hat sich die nicht verändert auf muscat-test

**Comment by alexandermarxen** [comment]
Ja, das betrifft nur die Suche, die Sortierung müsste noch angepasst werden.

**Comment by jenniferward** [comment]
Siehe auch #306 - eigentlich noch relevant.

**Comment by xhero** [comment]
Yes it is my bad, it was closed during the ticket cleanup and it provided the same solution as this one! sorry!

**Comment by alexandermarxen** [comment]
A small push for this issue. This sorting would make my work much easier and help to avoid numerous duplicates.
