### ISSUE TITLE
Personen - Kontrollfelder

### ISSUE THREAD

**Issue by alexandermarxen** [rism-digital/muscat#989]
Die Kontrollfelder in der Personendatei sind zur Zeit teilweise manuell ausfüllbar. Dies betrifft die Felder "Katalogiserungsquelle (040) mit den Subfields Original-Katalogisierungsstelle, Übertragende Katalogisierungsstelle, Modifizierende Katalogisierungsstelle und Katalogisierungssprache. In der Regel werden die Felder ohnehin automatisch ausgefüllt, Änderungen können zu Fehlern bei Datenlieferungen (beispielsweise an die VIAF) führen. Daher sollten diese Felder gesperrt werden.
Siehe: https://github.com/rism-international/tasks/issues/852

**Comment by jenniferward** [comment]
Relevant: https://github.com/rism-international/tasks/issues/849

**Comment by jenniferward** [comment]
Was this changed? 040 in Personal names https://muscat-test.rism.info/admin/people/new is still full of free-text fields.
